// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.1
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#include "cordic_sincos_generi.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_logic cordic_sincos_generi::ap_const_logic_1 = sc_dt::Log_1;
const sc_logic cordic_sincos_generi::ap_const_logic_0 = sc_dt::Log_0;
const sc_lv<7> cordic_sincos_generi::ap_ST_fsm_state1 = "1";
const sc_lv<7> cordic_sincos_generi::ap_ST_fsm_state2 = "10";
const sc_lv<7> cordic_sincos_generi::ap_ST_fsm_state3 = "100";
const sc_lv<7> cordic_sincos_generi::ap_ST_fsm_state4 = "1000";
const sc_lv<7> cordic_sincos_generi::ap_ST_fsm_state5 = "10000";
const sc_lv<7> cordic_sincos_generi::ap_ST_fsm_state6 = "100000";
const sc_lv<7> cordic_sincos_generi::ap_ST_fsm_state7 = "1000000";
const bool cordic_sincos_generi::ap_const_boolean_1 = true;
const sc_lv<32> cordic_sincos_generi::ap_const_lv32_0 = "00000000000000000000000000000000";
const sc_lv<1> cordic_sincos_generi::ap_const_lv1_0 = "0";
const sc_lv<32> cordic_sincos_generi::ap_const_lv32_1 = "1";
const sc_lv<32> cordic_sincos_generi::ap_const_lv32_2 = "10";
const sc_lv<1> cordic_sincos_generi::ap_const_lv1_1 = "1";
const sc_lv<32> cordic_sincos_generi::ap_const_lv32_3 = "11";
const sc_lv<32> cordic_sincos_generi::ap_const_lv32_4 = "100";
const sc_lv<32> cordic_sincos_generi::ap_const_lv32_5 = "101";
const sc_lv<43> cordic_sincos_generi::ap_const_lv43_0 = "0000000000000000000000000000000000000000000";
const sc_lv<43> cordic_sincos_generi::ap_const_lv43_9B74EDA843 = "1001101101110100111011011010100001000011";
const sc_lv<6> cordic_sincos_generi::ap_const_lv6_0 = "000000";
const sc_lv<43> cordic_sincos_generi::ap_const_lv43_10000000000 = "10000000000000000000000000000000000000000";
const sc_lv<32> cordic_sincos_generi::ap_const_lv32_6 = "110";
const bool cordic_sincos_generi::ap_const_boolean_0 = false;
const sc_lv<3> cordic_sincos_generi::ap_const_lv3_7 = "111";
const sc_lv<3> cordic_sincos_generi::ap_const_lv3_6 = "110";
const sc_lv<3> cordic_sincos_generi::ap_const_lv3_5 = "101";
const sc_lv<3> cordic_sincos_generi::ap_const_lv3_4 = "100";
const sc_lv<3> cordic_sincos_generi::ap_const_lv3_3 = "11";
const sc_lv<3> cordic_sincos_generi::ap_const_lv3_2 = "10";
const sc_lv<3> cordic_sincos_generi::ap_const_lv3_1 = "1";
const sc_lv<3> cordic_sincos_generi::ap_const_lv3_0 = "000";
const sc_lv<32> cordic_sincos_generi::ap_const_lv32_7FFFFFFF = "1111111111111111111111111111111";
const sc_lv<32> cordic_sincos_generi::ap_const_lv32_3F800000 = "111111100000000000000000000000";
const sc_lv<32> cordic_sincos_generi::ap_const_lv32_1F = "11111";
const sc_lv<32> cordic_sincos_generi::ap_const_lv32_17 = "10111";
const sc_lv<32> cordic_sincos_generi::ap_const_lv32_1E = "11110";
const sc_lv<8> cordic_sincos_generi::ap_const_lv8_FF = "11111111";
const sc_lv<8> cordic_sincos_generi::ap_const_lv8_73 = "1110011";
const sc_lv<8> cordic_sincos_generi::ap_const_lv8_7E = "1111110";
const sc_lv<32> cordic_sincos_generi::ap_const_lv32_1B = "11011";
const sc_lv<8> cordic_sincos_generi::ap_const_lv8_C2 = "11000010";
const sc_lv<8> cordic_sincos_generi::ap_const_lv8_3F = "111111";
const sc_lv<32> cordic_sincos_generi::ap_const_lv32_7 = "111";
const sc_lv<32> cordic_sincos_generi::ap_const_lv32_14 = "10100";
const sc_lv<32> cordic_sincos_generi::ap_const_lv32_63 = "1100011";
const sc_lv<32> cordic_sincos_generi::ap_const_lv32_8 = "1000";
const sc_lv<32> cordic_sincos_generi::ap_const_lv32_4C = "1001100";
const sc_lv<32> cordic_sincos_generi::ap_const_lv32_4D = "1001101";
const sc_lv<32> cordic_sincos_generi::ap_const_lv32_4F = "1001111";
const sc_lv<5> cordic_sincos_generi::ap_const_lv5_3 = "11";
const sc_lv<5> cordic_sincos_generi::ap_const_lv5_0 = "00000";
const sc_lv<69> cordic_sincos_generi::ap_const_lv69_0 = "000000000000000000000000000000000000000000000000000000000000000000000";
const sc_lv<32> cordic_sincos_generi::ap_const_lv32_28 = "101000";
const sc_lv<32> cordic_sincos_generi::ap_const_lv32_44 = "1000100";
const sc_lv<32> cordic_sincos_generi::ap_const_lv32_1D = "11101";
const sc_lv<2> cordic_sincos_generi::ap_const_lv2_3 = "11";
const sc_lv<7> cordic_sincos_generi::ap_const_lv7_0 = "0000000";
const sc_lv<7> cordic_sincos_generi::ap_const_lv7_74 = "1110100";
const sc_lv<80> cordic_sincos_generi::ap_const_lv80_C90FDAA221 = "1100100100001111110110101010001000100001";
const sc_lv<6> cordic_sincos_generi::ap_const_lv6_2B = "101011";
const sc_lv<6> cordic_sincos_generi::ap_const_lv6_1 = "1";
const sc_lv<32> cordic_sincos_generi::ap_const_lv32_2A = "101010";
const sc_lv<32> cordic_sincos_generi::ap_const_lv32_56 = "1010110";
const sc_lv<32> cordic_sincos_generi::ap_const_lv32_7D = "1111101";
const sc_lv<32> cordic_sincos_generi::ap_const_lv32_55 = "1010101";
const sc_lv<32> cordic_sincos_generi::ap_const_lv32_80000000 = "10000000000000000000000000000000";

cordic_sincos_generi::cordic_sincos_generi(sc_module_name name) : sc_module(name), mVcdFile(0) {
    ref_4oPi_table_100_V_U = new cordic_sincos_geneOg("ref_4oPi_table_100_V_U");
    ref_4oPi_table_100_V_U->clk(ap_clk);
    ref_4oPi_table_100_V_U->reset(ap_rst);
    ref_4oPi_table_100_V_U->address0(ref_4oPi_table_100_V_address0);
    ref_4oPi_table_100_V_U->ce0(ref_4oPi_table_100_V_ce0);
    ref_4oPi_table_100_V_U->q0(ref_4oPi_table_100_V_q0);
    cordic_ctab_table_12_1_U = new cordic_sincos_genfYi("cordic_ctab_table_12_1_U");
    cordic_ctab_table_12_1_U->clk(ap_clk);
    cordic_ctab_table_12_1_U->reset(ap_rst);
    cordic_ctab_table_12_1_U->address0(cordic_ctab_table_12_1_address0);
    cordic_ctab_table_12_1_U->ce0(cordic_ctab_table_12_1_ce0);
    cordic_ctab_table_12_1_U->q0(cordic_ctab_table_12_1_q0);
    grp_scaled_fixed2ieee_fu_344 = new scaled_fixed2ieee("grp_scaled_fixed2ieee_fu_344");
    grp_scaled_fixed2ieee_fu_344->ap_clk(ap_clk);
    grp_scaled_fixed2ieee_fu_344->ap_rst(ap_rst);
    grp_scaled_fixed2ieee_fu_344->ap_start(grp_scaled_fixed2ieee_fu_344_ap_start);
    grp_scaled_fixed2ieee_fu_344->ap_done(grp_scaled_fixed2ieee_fu_344_ap_done);
    grp_scaled_fixed2ieee_fu_344->ap_idle(grp_scaled_fixed2ieee_fu_344_ap_idle);
    grp_scaled_fixed2ieee_fu_344->ap_ready(grp_scaled_fixed2ieee_fu_344_ap_ready);
    grp_scaled_fixed2ieee_fu_344->in_V(p_1_reg_266);
    grp_scaled_fixed2ieee_fu_344->prescale(p_s_reg_277);
    grp_scaled_fixed2ieee_fu_344->ap_return(grp_scaled_fixed2ieee_fu_344_ap_return);
    grp_scaled_fixed2ieee_fu_356 = new scaled_fixed2ieee("grp_scaled_fixed2ieee_fu_356");
    grp_scaled_fixed2ieee_fu_356->ap_clk(ap_clk);
    grp_scaled_fixed2ieee_fu_356->ap_rst(ap_rst);
    grp_scaled_fixed2ieee_fu_356->ap_start(grp_scaled_fixed2ieee_fu_356_ap_start);
    grp_scaled_fixed2ieee_fu_356->ap_done(grp_scaled_fixed2ieee_fu_356_ap_done);
    grp_scaled_fixed2ieee_fu_356->ap_idle(grp_scaled_fixed2ieee_fu_356_ap_idle);
    grp_scaled_fixed2ieee_fu_356->ap_ready(grp_scaled_fixed2ieee_fu_356_ap_ready);
    grp_scaled_fixed2ieee_fu_356->in_V(p_0_reg_253);
    grp_scaled_fixed2ieee_fu_356->prescale(ap_var_for_const0);
    grp_scaled_fixed2ieee_fu_356->ap_return(grp_scaled_fixed2ieee_fu_356_ap_return);

    SC_METHOD(thread_ap_clk_no_reset_);
    dont_initialize();
    sensitive << ( ap_clk.pos() );

    SC_METHOD(thread_Ex_V_fu_625_p2);
    sensitive << ( storemerge_i_cast_fu_527_p1 );
    sensitive << ( tmp_20_i_cast_fu_621_p1 );

    SC_METHOD(thread_Med_V_fu_471_p4);
    sensitive << ( r_V_fu_465_p2 );

    SC_METHOD(thread_Mx_V_fu_611_p4);
    sensitive << ( p_Val2_17_fu_605_p2 );

    SC_METHOD(thread_Mx_zeros_V_fu_597_p1);
    sensitive << ( val_assign_fu_589_p3 );

    SC_METHOD(thread_addr_V_fu_428_p3);
    sensitive << ( closepath_fu_402_p2 );
    sensitive << ( expv_op_fu_422_p2 );

    SC_METHOD(thread_ap_CS_fsm_state1);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state2);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state3);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state4);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state5);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state6);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state7);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_block_state7_on_subcall_done);
    sensitive << ( grp_scaled_fixed2ieee_fu_344_ap_done );
    sensitive << ( grp_scaled_fixed2ieee_fu_356_ap_done );
    sensitive << ( ap_predicate_op125_call_state7 );

    SC_METHOD(thread_ap_done);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( ap_CS_fsm_state7 );
    sensitive << ( ap_block_state7_on_subcall_done );

    SC_METHOD(thread_ap_idle);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );

    SC_METHOD(thread_ap_phi_mux_c_out_write_assign_phi_fu_320_p20);
    sensitive << ( tmp_s_reg_1029 );
    sensitive << ( tmp_36_reg_1033 );
    sensitive << ( sel_reg_1132 );
    sensitive << ( grp_scaled_fixed2ieee_fu_344_ap_return );
    sensitive << ( grp_scaled_fixed2ieee_fu_356_ap_return );
    sensitive << ( ap_CS_fsm_state7 );
    sensitive << ( c_out_write_assign_reg_315 );
    sensitive << ( tmp_49_fu_927_p1 );
    sensitive << ( tmp_47_fu_957_p1 );
    sensitive << ( tmp_45_fu_972_p1 );
    sensitive << ( tmp_44_fu_987_p1 );

    SC_METHOD(thread_ap_phi_mux_s_out_write_assign_phi_fu_292_p20);
    sensitive << ( tmp_s_reg_1029 );
    sensitive << ( tmp_36_reg_1033 );
    sensitive << ( sel_reg_1132 );
    sensitive << ( grp_scaled_fixed2ieee_fu_344_ap_return );
    sensitive << ( grp_scaled_fixed2ieee_fu_356_ap_return );
    sensitive << ( tmp_43_fu_1002_p1 );
    sensitive << ( s_out_write_assign_reg_288 );
    sensitive << ( ap_CS_fsm_state7 );
    sensitive << ( tmp_50_fu_897_p1 );
    sensitive << ( tmp_48_fu_912_p1 );
    sensitive << ( tmp_46_fu_942_p1 );

    SC_METHOD(thread_ap_predicate_op125_call_state7);
    sensitive << ( tmp_s_reg_1029 );
    sensitive << ( tmp_36_reg_1033 );

    SC_METHOD(thread_ap_ready);
    sensitive << ( ap_CS_fsm_state7 );
    sensitive << ( ap_block_state7_on_subcall_done );

    SC_METHOD(thread_ap_return_0);
    sensitive << ( ap_phi_mux_s_out_write_assign_phi_fu_292_p20 );
    sensitive << ( ap_CS_fsm_state7 );
    sensitive << ( ap_block_state7_on_subcall_done );
    sensitive << ( ap_return_0_preg );

    SC_METHOD(thread_ap_return_1);
    sensitive << ( ap_CS_fsm_state7 );
    sensitive << ( ap_block_state7_on_subcall_done );
    sensitive << ( ap_phi_mux_c_out_write_assign_phi_fu_320_p20 );
    sensitive << ( ap_return_1_preg );

    SC_METHOD(thread_closepath_fu_402_p2);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( tmp_s_fu_390_p2 );
    sensitive << ( tmp_36_fu_396_p2 );
    sensitive << ( loc_V_fu_380_p4 );

    SC_METHOD(thread_cordic_ctab_table_12_1_address0);
    sensitive << ( ap_CS_fsm_state5 );
    sensitive << ( tmp_40_fu_820_p1 );

    SC_METHOD(thread_cordic_ctab_table_12_1_ce0);
    sensitive << ( ap_CS_fsm_state5 );

    SC_METHOD(thread_d_V_fu_756_p3);
    sensitive << ( p_Val2_18_reg_210 );

    SC_METHOD(thread_exitcond_i_fu_744_p2);
    sensitive << ( tmp_37_reg_1085 );
    sensitive << ( ap_CS_fsm_state5 );
    sensitive << ( sh_assign_reg_242 );

    SC_METHOD(thread_expv_op_fu_422_p2);
    sensitive << ( loc_V_fu_380_p4 );

    SC_METHOD(thread_fout_V_fu_673_p3);
    sensitive << ( isNeg_fu_631_p3 );
    sensitive << ( tmp_24_i_fu_661_p2 );
    sensitive << ( tmp_25_i_fu_667_p2 );

    SC_METHOD(thread_grp_scaled_fixed2ieee_fu_344_ap_start);
    sensitive << ( grp_scaled_fixed2ieee_fu_344_ap_start_reg );

    SC_METHOD(thread_grp_scaled_fixed2ieee_fu_356_ap_start);
    sensitive << ( grp_scaled_fixed2ieee_fu_356_ap_start_reg );

    SC_METHOD(thread_isNeg_fu_631_p3);
    sensitive << ( Ex_V_fu_625_p2 );

    SC_METHOD(thread_k_fu_750_p2);
    sensitive << ( sh_assign_reg_242 );

    SC_METHOD(thread_loc_V_fu_380_p4);
    sensitive << ( p_Val2_7_fu_368_p1 );

    SC_METHOD(thread_p_Result_10_fu_455_p3);
    sensitive << ( p_Result_9_reg_1048 );

    SC_METHOD(thread_p_Result_11_fu_563_p3);
    sensitive << ( p_Result_i2_i_fu_553_p4 );

    SC_METHOD(thread_p_Result_12_fu_571_p4);
    sensitive << ( p_Result_11_fu_563_p3 );

    SC_METHOD(thread_p_Result_13_fu_581_p3);
    sensitive << ( p_Result_12_fu_571_p4 );

    SC_METHOD(thread_p_Result_9_fu_418_p1);
    sensitive << ( p_Val2_7_fu_368_p1 );

    SC_METHOD(thread_p_Result_i2_i_fu_553_p4);
    sensitive << ( p_Val2_15_fu_546_p3 );

    SC_METHOD(thread_p_Val2_15_fu_546_p3);
    sensitive << ( p_Val2_13_reg_1063 );
    sensitive << ( tmp_35_fu_537_p1 );
    sensitive << ( p_Val2_i_fu_541_p2 );

    SC_METHOD(thread_p_Val2_17_fu_605_p2);
    sensitive << ( p_Val2_15_fu_546_p3 );
    sensitive << ( tmp_17_i_fu_601_p1 );

    SC_METHOD(thread_p_Val2_23_fu_531_p3);
    sensitive << ( closepath_reg_1037 );
    sensitive << ( tmp_16_i_reg_1069 );

    SC_METHOD(thread_p_Val2_27_cast_fu_836_p4);
    sensitive << ( cordic_ctab_table_12_1_q0 );

    SC_METHOD(thread_p_Val2_7_fu_368_p1);
    sensitive << ( t_in );

    SC_METHOD(thread_p_Val2_9_fu_691_p1);
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( p_Val2_9_fu_691_p10 );

    SC_METHOD(thread_p_Val2_9_fu_691_p10);
    sensitive << ( Mx_V_fu_611_p4 );

    SC_METHOD(thread_p_Val2_9_fu_691_p2);
    sensitive << ( p_Val2_9_fu_691_p1 );

    SC_METHOD(thread_p_Val2_i_fu_541_p2);
    sensitive << ( p_Val2_13_reg_1063 );

    SC_METHOD(thread_p_Val2_s_fu_724_p0);
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( p_Val2_s_fu_724_p00 );

    SC_METHOD(thread_p_Val2_s_fu_724_p00);
    sensitive << ( fout_V_reg_1080 );

    SC_METHOD(thread_p_Val2_s_fu_724_p2);
    sensitive << ( p_Val2_s_fu_724_p0 );

    SC_METHOD(thread_p_i_cast_fu_515_p2);
    sensitive << ( tmp_reg_1043 );

    SC_METHOD(thread_r_V_1_fu_489_p0);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( r_V_1_fu_489_p00 );

    SC_METHOD(thread_r_V_1_fu_489_p00);
    sensitive << ( Med_V_fu_471_p4 );

    SC_METHOD(thread_r_V_1_fu_489_p1);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( r_V_1_fu_489_p10 );

    SC_METHOD(thread_r_V_1_fu_489_p10);
    sensitive << ( p_Result_10_fu_455_p3 );

    SC_METHOD(thread_r_V_1_fu_489_p2);
    sensitive << ( r_V_1_fu_489_p0 );
    sensitive << ( r_V_1_fu_489_p1 );

    SC_METHOD(thread_r_V_1_i_fu_800_p2);
    sensitive << ( p_Val2_1_reg_220 );
    sensitive << ( x_s_V_fu_794_p2 );

    SC_METHOD(thread_r_V_4_i_fu_774_p2);
    sensitive << ( p_Val2_2_reg_231 );
    sensitive << ( y_s_V_fu_768_p2 );

    SC_METHOD(thread_r_V_5_i_fu_868_p2);
    sensitive << ( p_Val2_18_reg_210 );
    sensitive << ( z_s_V_cast_fu_864_p1 );

    SC_METHOD(thread_r_V_fu_465_p2);
    sensitive << ( ref_4oPi_table_100_V_q0 );
    sensitive << ( tmp_7_i_i_fu_462_p1 );

    SC_METHOD(thread_r_V_i2_fu_780_p2);
    sensitive << ( p_Val2_2_reg_231 );
    sensitive << ( y_s_V_fu_768_p2 );

    SC_METHOD(thread_r_V_i7_fu_806_p2);
    sensitive << ( p_Val2_1_reg_220 );
    sensitive << ( x_s_V_fu_794_p2 );

    SC_METHOD(thread_r_V_i_fu_874_p2);
    sensitive << ( p_Val2_18_reg_210 );
    sensitive << ( z_s_V_cast_fu_864_p1 );

    SC_METHOD(thread_ref_4oPi_table_100_V_address0);
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( tmp_5_i_i_fu_446_p1 );

    SC_METHOD(thread_ref_4oPi_table_100_V_ce0);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );

    SC_METHOD(thread_sel_fu_830_p3);
    sensitive << ( p_Result_s_reg_1024 );
    sensitive << ( p_Val2_23_reg_1074 );
    sensitive << ( tmp_42_fu_825_p2 );

    SC_METHOD(thread_sh_assign_2_fu_645_p3);
    sensitive << ( Ex_V_fu_625_p2 );
    sensitive << ( isNeg_fu_631_p3 );
    sensitive << ( tmp_22_i_fu_639_p2 );

    SC_METHOD(thread_sh_assign_3_cast_fu_653_p1);
    sensitive << ( sh_assign_2_fu_645_p3 );

    SC_METHOD(thread_storemerge_i_cast_fu_527_p1);
    sensitive << ( storemerge_i_fu_520_p3 );

    SC_METHOD(thread_storemerge_i_fu_520_p3);
    sensitive << ( closepath_reg_1037 );
    sensitive << ( p_i_cast_fu_515_p2 );

    SC_METHOD(thread_tmp_12_fu_436_p4);
    sensitive << ( addr_V_fu_428_p3 );

    SC_METHOD(thread_tmp_14_fu_697_p4);
    sensitive << ( p_Val2_9_fu_691_p2 );

    SC_METHOD(thread_tmp_15_fu_730_p4);
    sensitive << ( p_Val2_s_fu_724_p2 );

    SC_METHOD(thread_tmp_17_i_fu_601_p1);
    sensitive << ( Mx_zeros_V_fu_597_p1 );

    SC_METHOD(thread_tmp_20_i_cast_fu_621_p1);
    sensitive << ( Mx_zeros_V_fu_597_p1 );

    SC_METHOD(thread_tmp_212_neg_fu_981_p2);
    sensitive << ( tmp_212_to_int_fu_977_p1 );

    SC_METHOD(thread_tmp_212_to_int_fu_977_p1);
    sensitive << ( grp_scaled_fixed2ieee_fu_344_ap_return );

    SC_METHOD(thread_tmp_213_neg_fu_966_p2);
    sensitive << ( tmp_213_to_int_fu_962_p1 );

    SC_METHOD(thread_tmp_213_to_int_fu_962_p1);
    sensitive << ( grp_scaled_fixed2ieee_fu_356_ap_return );

    SC_METHOD(thread_tmp_214_neg_fu_936_p2);
    sensitive << ( tmp_214_to_int_fu_932_p1 );

    SC_METHOD(thread_tmp_214_to_int_fu_932_p1);
    sensitive << ( grp_scaled_fixed2ieee_fu_344_ap_return );

    SC_METHOD(thread_tmp_215_neg_fu_951_p2);
    sensitive << ( tmp_215_to_int_fu_947_p1 );

    SC_METHOD(thread_tmp_215_to_int_fu_947_p1);
    sensitive << ( grp_scaled_fixed2ieee_fu_356_ap_return );

    SC_METHOD(thread_tmp_216_neg_fu_906_p2);
    sensitive << ( tmp_216_to_int_fu_902_p1 );

    SC_METHOD(thread_tmp_216_to_int_fu_902_p1);
    sensitive << ( grp_scaled_fixed2ieee_fu_356_ap_return );

    SC_METHOD(thread_tmp_217_neg_fu_921_p2);
    sensitive << ( tmp_217_to_int_fu_917_p1 );

    SC_METHOD(thread_tmp_217_to_int_fu_917_p1);
    sensitive << ( grp_scaled_fixed2ieee_fu_344_ap_return );

    SC_METHOD(thread_tmp_218_neg_fu_891_p2);
    sensitive << ( tmp_218_to_int_fu_887_p1 );

    SC_METHOD(thread_tmp_218_to_int_fu_887_p1);
    sensitive << ( grp_scaled_fixed2ieee_fu_356_ap_return );

    SC_METHOD(thread_tmp_219_neg_fu_996_p2);
    sensitive << ( tmp_219_to_int_fu_992_p1 );

    SC_METHOD(thread_tmp_219_to_int_fu_992_p1);
    sensitive << ( grp_scaled_fixed2ieee_fu_344_ap_return );

    SC_METHOD(thread_tmp_22_i_fu_639_p2);
    sensitive << ( Ex_V_fu_625_p2 );

    SC_METHOD(thread_tmp_23_i_fu_657_p1);
    sensitive << ( sh_assign_3_cast_fu_653_p1 );

    SC_METHOD(thread_tmp_24_i_fu_661_p2);
    sensitive << ( Mx_V_fu_611_p4 );
    sensitive << ( tmp_23_i_fu_657_p1 );

    SC_METHOD(thread_tmp_25_i_fu_667_p2);
    sensitive << ( Mx_V_fu_611_p4 );
    sensitive << ( tmp_23_i_fu_657_p1 );

    SC_METHOD(thread_tmp_34_fu_451_p1);
    sensitive << ( addr_V_fu_428_p3 );

    SC_METHOD(thread_tmp_35_fu_537_p1);
    sensitive << ( p_Val2_23_fu_531_p3 );

    SC_METHOD(thread_tmp_36_fu_396_p2);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( tmp_s_fu_390_p2 );
    sensitive << ( loc_V_fu_380_p4 );

    SC_METHOD(thread_tmp_37_fu_681_p2);
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( Ex_V_fu_625_p2 );

    SC_METHOD(thread_tmp_38_fu_764_p1);
    sensitive << ( sh_assign_reg_242 );

    SC_METHOD(thread_tmp_39_fu_711_p1);
    sensitive << ( Ex_V_fu_625_p2 );

    SC_METHOD(thread_tmp_40_fu_820_p1);
    sensitive << ( sh_assign_reg_242 );

    SC_METHOD(thread_tmp_41_fu_846_p3);
    sensitive << ( cordic_ctab_table_12_1_q0 );

    SC_METHOD(thread_tmp_42_fu_825_p2);
    sensitive << ( p_Val2_23_reg_1074 );

    SC_METHOD(thread_tmp_43_fu_1002_p1);
    sensitive << ( tmp_219_neg_fu_996_p2 );

    SC_METHOD(thread_tmp_44_fu_987_p1);
    sensitive << ( tmp_212_neg_fu_981_p2 );

    SC_METHOD(thread_tmp_45_fu_972_p1);
    sensitive << ( tmp_213_neg_fu_966_p2 );

    SC_METHOD(thread_tmp_46_cast_fu_854_p1);
    sensitive << ( tmp_41_fu_846_p3 );

    SC_METHOD(thread_tmp_46_fu_942_p1);
    sensitive << ( tmp_214_neg_fu_936_p2 );

    SC_METHOD(thread_tmp_47_fu_957_p1);
    sensitive << ( tmp_215_neg_fu_951_p2 );

    SC_METHOD(thread_tmp_48_fu_912_p1);
    sensitive << ( tmp_216_neg_fu_906_p2 );

    SC_METHOD(thread_tmp_49_fu_927_p1);
    sensitive << ( tmp_217_neg_fu_921_p2 );

    SC_METHOD(thread_tmp_50_fu_897_p1);
    sensitive << ( tmp_218_neg_fu_891_p2 );

    SC_METHOD(thread_tmp_5_i_i_fu_446_p1);
    sensitive << ( tmp_12_fu_436_p4 );

    SC_METHOD(thread_tmp_7_i_i_fu_462_p1);
    sensitive << ( tmp_34_reg_1058 );

    SC_METHOD(thread_tmp_s_fu_390_p2);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( loc_V_fu_380_p4 );

    SC_METHOD(thread_tx_V_fu_786_p3);
    sensitive << ( d_V_fu_756_p3 );
    sensitive << ( r_V_i2_fu_780_p2 );
    sensitive << ( r_V_4_i_fu_774_p2 );

    SC_METHOD(thread_ty_V_fu_812_p3);
    sensitive << ( d_V_fu_756_p3 );
    sensitive << ( r_V_1_i_fu_800_p2 );
    sensitive << ( r_V_i7_fu_806_p2 );

    SC_METHOD(thread_tz_V_fu_880_p3);
    sensitive << ( d_V_reg_1112 );
    sensitive << ( r_V_i_fu_874_p2 );
    sensitive << ( r_V_5_i_fu_868_p2 );

    SC_METHOD(thread_val_assign_fu_589_p3);
    sensitive << ( p_Result_13_fu_581_p3 );

    SC_METHOD(thread_x_s_V_fu_794_p2);
    sensitive << ( p_Val2_2_reg_231 );
    sensitive << ( tmp_38_fu_764_p1 );

    SC_METHOD(thread_y_V_fu_707_p1);
    sensitive << ( tmp_14_fu_697_p4 );

    SC_METHOD(thread_y_s_V_fu_768_p2);
    sensitive << ( p_Val2_1_reg_220 );
    sensitive << ( tmp_38_fu_764_p1 );

    SC_METHOD(thread_yprescale_V_cast_fu_715_p2);
    sensitive << ( tmp_39_fu_711_p1 );

    SC_METHOD(thread_z_V_fu_740_p1);
    sensitive << ( tmp_15_fu_730_p4 );

    SC_METHOD(thread_z_s_V_cast_fu_864_p1);
    sensitive << ( z_s_V_fu_858_p2 );

    SC_METHOD(thread_z_s_V_fu_858_p2);
    sensitive << ( tmp_46_cast_fu_854_p1 );
    sensitive << ( p_Val2_27_cast_fu_836_p4 );

    SC_METHOD(thread_ap_NS_fsm);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( tmp_s_fu_390_p2 );
    sensitive << ( tmp_36_fu_396_p2 );
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( tmp_37_fu_681_p2 );
    sensitive << ( tmp_37_reg_1085 );
    sensitive << ( ap_CS_fsm_state5 );
    sensitive << ( exitcond_i_fu_744_p2 );
    sensitive << ( ap_CS_fsm_state7 );
    sensitive << ( ap_block_state7_on_subcall_done );

    SC_THREAD(thread_ap_var_for_const0);

    ap_CS_fsm = "0000001";
    grp_scaled_fixed2ieee_fu_344_ap_start_reg = SC_LOGIC_0;
    grp_scaled_fixed2ieee_fu_356_ap_start_reg = SC_LOGIC_0;
    ap_return_0_preg = "00000000000000000000000000000000";
    ap_return_1_preg = "00000000000000000000000000000000";
    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "cordic_sincos_generi_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT_HIER__
    sc_trace(mVcdFile, ap_clk, "(port)ap_clk");
    sc_trace(mVcdFile, ap_rst, "(port)ap_rst");
    sc_trace(mVcdFile, ap_start, "(port)ap_start");
    sc_trace(mVcdFile, ap_done, "(port)ap_done");
    sc_trace(mVcdFile, ap_idle, "(port)ap_idle");
    sc_trace(mVcdFile, ap_ready, "(port)ap_ready");
    sc_trace(mVcdFile, t_in, "(port)t_in");
    sc_trace(mVcdFile, ap_return_0, "(port)ap_return_0");
    sc_trace(mVcdFile, ap_return_1, "(port)ap_return_1");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, ap_CS_fsm, "ap_CS_fsm");
    sc_trace(mVcdFile, ap_CS_fsm_state1, "ap_CS_fsm_state1");
    sc_trace(mVcdFile, ref_4oPi_table_100_V_address0, "ref_4oPi_table_100_V_address0");
    sc_trace(mVcdFile, ref_4oPi_table_100_V_ce0, "ref_4oPi_table_100_V_ce0");
    sc_trace(mVcdFile, ref_4oPi_table_100_V_q0, "ref_4oPi_table_100_V_q0");
    sc_trace(mVcdFile, cordic_ctab_table_12_1_address0, "cordic_ctab_table_12_1_address0");
    sc_trace(mVcdFile, cordic_ctab_table_12_1_ce0, "cordic_ctab_table_12_1_ce0");
    sc_trace(mVcdFile, cordic_ctab_table_12_1_q0, "cordic_ctab_table_12_1_q0");
    sc_trace(mVcdFile, p_Result_s_reg_1024, "p_Result_s_reg_1024");
    sc_trace(mVcdFile, tmp_s_fu_390_p2, "tmp_s_fu_390_p2");
    sc_trace(mVcdFile, tmp_s_reg_1029, "tmp_s_reg_1029");
    sc_trace(mVcdFile, tmp_36_fu_396_p2, "tmp_36_fu_396_p2");
    sc_trace(mVcdFile, tmp_36_reg_1033, "tmp_36_reg_1033");
    sc_trace(mVcdFile, closepath_fu_402_p2, "closepath_fu_402_p2");
    sc_trace(mVcdFile, closepath_reg_1037, "closepath_reg_1037");
    sc_trace(mVcdFile, tmp_reg_1043, "tmp_reg_1043");
    sc_trace(mVcdFile, p_Result_9_fu_418_p1, "p_Result_9_fu_418_p1");
    sc_trace(mVcdFile, p_Result_9_reg_1048, "p_Result_9_reg_1048");
    sc_trace(mVcdFile, tmp_34_fu_451_p1, "tmp_34_fu_451_p1");
    sc_trace(mVcdFile, tmp_34_reg_1058, "tmp_34_reg_1058");
    sc_trace(mVcdFile, p_Val2_13_reg_1063, "p_Val2_13_reg_1063");
    sc_trace(mVcdFile, ap_CS_fsm_state2, "ap_CS_fsm_state2");
    sc_trace(mVcdFile, tmp_16_i_reg_1069, "tmp_16_i_reg_1069");
    sc_trace(mVcdFile, p_Val2_23_fu_531_p3, "p_Val2_23_fu_531_p3");
    sc_trace(mVcdFile, p_Val2_23_reg_1074, "p_Val2_23_reg_1074");
    sc_trace(mVcdFile, ap_CS_fsm_state3, "ap_CS_fsm_state3");
    sc_trace(mVcdFile, fout_V_fu_673_p3, "fout_V_fu_673_p3");
    sc_trace(mVcdFile, fout_V_reg_1080, "fout_V_reg_1080");
    sc_trace(mVcdFile, tmp_37_fu_681_p2, "tmp_37_fu_681_p2");
    sc_trace(mVcdFile, tmp_37_reg_1085, "tmp_37_reg_1085");
    sc_trace(mVcdFile, y_V_fu_707_p1, "y_V_fu_707_p1");
    sc_trace(mVcdFile, yprescale_V_cast_fu_715_p2, "yprescale_V_cast_fu_715_p2");
    sc_trace(mVcdFile, z_V_fu_740_p1, "z_V_fu_740_p1");
    sc_trace(mVcdFile, ap_CS_fsm_state4, "ap_CS_fsm_state4");
    sc_trace(mVcdFile, k_fu_750_p2, "k_fu_750_p2");
    sc_trace(mVcdFile, k_reg_1107, "k_reg_1107");
    sc_trace(mVcdFile, ap_CS_fsm_state5, "ap_CS_fsm_state5");
    sc_trace(mVcdFile, d_V_fu_756_p3, "d_V_fu_756_p3");
    sc_trace(mVcdFile, d_V_reg_1112, "d_V_reg_1112");
    sc_trace(mVcdFile, exitcond_i_fu_744_p2, "exitcond_i_fu_744_p2");
    sc_trace(mVcdFile, tx_V_fu_786_p3, "tx_V_fu_786_p3");
    sc_trace(mVcdFile, tx_V_reg_1117, "tx_V_reg_1117");
    sc_trace(mVcdFile, ty_V_fu_812_p3, "ty_V_fu_812_p3");
    sc_trace(mVcdFile, ty_V_reg_1122, "ty_V_reg_1122");
    sc_trace(mVcdFile, sel_fu_830_p3, "sel_fu_830_p3");
    sc_trace(mVcdFile, sel_reg_1132, "sel_reg_1132");
    sc_trace(mVcdFile, tz_V_fu_880_p3, "tz_V_fu_880_p3");
    sc_trace(mVcdFile, ap_CS_fsm_state6, "ap_CS_fsm_state6");
    sc_trace(mVcdFile, grp_scaled_fixed2ieee_fu_344_ap_start, "grp_scaled_fixed2ieee_fu_344_ap_start");
    sc_trace(mVcdFile, grp_scaled_fixed2ieee_fu_344_ap_done, "grp_scaled_fixed2ieee_fu_344_ap_done");
    sc_trace(mVcdFile, grp_scaled_fixed2ieee_fu_344_ap_idle, "grp_scaled_fixed2ieee_fu_344_ap_idle");
    sc_trace(mVcdFile, grp_scaled_fixed2ieee_fu_344_ap_ready, "grp_scaled_fixed2ieee_fu_344_ap_ready");
    sc_trace(mVcdFile, grp_scaled_fixed2ieee_fu_344_ap_return, "grp_scaled_fixed2ieee_fu_344_ap_return");
    sc_trace(mVcdFile, grp_scaled_fixed2ieee_fu_356_ap_start, "grp_scaled_fixed2ieee_fu_356_ap_start");
    sc_trace(mVcdFile, grp_scaled_fixed2ieee_fu_356_ap_done, "grp_scaled_fixed2ieee_fu_356_ap_done");
    sc_trace(mVcdFile, grp_scaled_fixed2ieee_fu_356_ap_idle, "grp_scaled_fixed2ieee_fu_356_ap_idle");
    sc_trace(mVcdFile, grp_scaled_fixed2ieee_fu_356_ap_ready, "grp_scaled_fixed2ieee_fu_356_ap_ready");
    sc_trace(mVcdFile, grp_scaled_fixed2ieee_fu_356_ap_return, "grp_scaled_fixed2ieee_fu_356_ap_return");
    sc_trace(mVcdFile, p_Val2_18_reg_210, "p_Val2_18_reg_210");
    sc_trace(mVcdFile, p_Val2_1_reg_220, "p_Val2_1_reg_220");
    sc_trace(mVcdFile, p_Val2_2_reg_231, "p_Val2_2_reg_231");
    sc_trace(mVcdFile, sh_assign_reg_242, "sh_assign_reg_242");
    sc_trace(mVcdFile, p_0_reg_253, "p_0_reg_253");
    sc_trace(mVcdFile, p_1_reg_266, "p_1_reg_266");
    sc_trace(mVcdFile, p_s_reg_277, "p_s_reg_277");
    sc_trace(mVcdFile, tmp_43_fu_1002_p1, "tmp_43_fu_1002_p1");
    sc_trace(mVcdFile, ap_phi_mux_s_out_write_assign_phi_fu_292_p20, "ap_phi_mux_s_out_write_assign_phi_fu_292_p20");
    sc_trace(mVcdFile, s_out_write_assign_reg_288, "s_out_write_assign_reg_288");
    sc_trace(mVcdFile, ap_CS_fsm_state7, "ap_CS_fsm_state7");
    sc_trace(mVcdFile, ap_predicate_op125_call_state7, "ap_predicate_op125_call_state7");
    sc_trace(mVcdFile, ap_block_state7_on_subcall_done, "ap_block_state7_on_subcall_done");
    sc_trace(mVcdFile, tmp_50_fu_897_p1, "tmp_50_fu_897_p1");
    sc_trace(mVcdFile, tmp_48_fu_912_p1, "tmp_48_fu_912_p1");
    sc_trace(mVcdFile, tmp_46_fu_942_p1, "tmp_46_fu_942_p1");
    sc_trace(mVcdFile, ap_phi_mux_c_out_write_assign_phi_fu_320_p20, "ap_phi_mux_c_out_write_assign_phi_fu_320_p20");
    sc_trace(mVcdFile, c_out_write_assign_reg_315, "c_out_write_assign_reg_315");
    sc_trace(mVcdFile, tmp_49_fu_927_p1, "tmp_49_fu_927_p1");
    sc_trace(mVcdFile, tmp_47_fu_957_p1, "tmp_47_fu_957_p1");
    sc_trace(mVcdFile, tmp_45_fu_972_p1, "tmp_45_fu_972_p1");
    sc_trace(mVcdFile, tmp_44_fu_987_p1, "tmp_44_fu_987_p1");
    sc_trace(mVcdFile, grp_scaled_fixed2ieee_fu_344_ap_start_reg, "grp_scaled_fixed2ieee_fu_344_ap_start_reg");
    sc_trace(mVcdFile, grp_scaled_fixed2ieee_fu_356_ap_start_reg, "grp_scaled_fixed2ieee_fu_356_ap_start_reg");
    sc_trace(mVcdFile, tmp_5_i_i_fu_446_p1, "tmp_5_i_i_fu_446_p1");
    sc_trace(mVcdFile, tmp_40_fu_820_p1, "tmp_40_fu_820_p1");
    sc_trace(mVcdFile, p_Val2_7_fu_368_p1, "p_Val2_7_fu_368_p1");
    sc_trace(mVcdFile, loc_V_fu_380_p4, "loc_V_fu_380_p4");
    sc_trace(mVcdFile, expv_op_fu_422_p2, "expv_op_fu_422_p2");
    sc_trace(mVcdFile, addr_V_fu_428_p3, "addr_V_fu_428_p3");
    sc_trace(mVcdFile, tmp_12_fu_436_p4, "tmp_12_fu_436_p4");
    sc_trace(mVcdFile, tmp_7_i_i_fu_462_p1, "tmp_7_i_i_fu_462_p1");
    sc_trace(mVcdFile, r_V_fu_465_p2, "r_V_fu_465_p2");
    sc_trace(mVcdFile, Med_V_fu_471_p4, "Med_V_fu_471_p4");
    sc_trace(mVcdFile, p_Result_10_fu_455_p3, "p_Result_10_fu_455_p3");
    sc_trace(mVcdFile, r_V_1_fu_489_p0, "r_V_1_fu_489_p0");
    sc_trace(mVcdFile, r_V_1_fu_489_p1, "r_V_1_fu_489_p1");
    sc_trace(mVcdFile, r_V_1_fu_489_p2, "r_V_1_fu_489_p2");
    sc_trace(mVcdFile, p_i_cast_fu_515_p2, "p_i_cast_fu_515_p2");
    sc_trace(mVcdFile, storemerge_i_fu_520_p3, "storemerge_i_fu_520_p3");
    sc_trace(mVcdFile, tmp_35_fu_537_p1, "tmp_35_fu_537_p1");
    sc_trace(mVcdFile, p_Val2_i_fu_541_p2, "p_Val2_i_fu_541_p2");
    sc_trace(mVcdFile, p_Val2_15_fu_546_p3, "p_Val2_15_fu_546_p3");
    sc_trace(mVcdFile, p_Result_i2_i_fu_553_p4, "p_Result_i2_i_fu_553_p4");
    sc_trace(mVcdFile, p_Result_11_fu_563_p3, "p_Result_11_fu_563_p3");
    sc_trace(mVcdFile, p_Result_12_fu_571_p4, "p_Result_12_fu_571_p4");
    sc_trace(mVcdFile, p_Result_13_fu_581_p3, "p_Result_13_fu_581_p3");
    sc_trace(mVcdFile, val_assign_fu_589_p3, "val_assign_fu_589_p3");
    sc_trace(mVcdFile, Mx_zeros_V_fu_597_p1, "Mx_zeros_V_fu_597_p1");
    sc_trace(mVcdFile, tmp_17_i_fu_601_p1, "tmp_17_i_fu_601_p1");
    sc_trace(mVcdFile, p_Val2_17_fu_605_p2, "p_Val2_17_fu_605_p2");
    sc_trace(mVcdFile, storemerge_i_cast_fu_527_p1, "storemerge_i_cast_fu_527_p1");
    sc_trace(mVcdFile, tmp_20_i_cast_fu_621_p1, "tmp_20_i_cast_fu_621_p1");
    sc_trace(mVcdFile, Ex_V_fu_625_p2, "Ex_V_fu_625_p2");
    sc_trace(mVcdFile, isNeg_fu_631_p3, "isNeg_fu_631_p3");
    sc_trace(mVcdFile, tmp_22_i_fu_639_p2, "tmp_22_i_fu_639_p2");
    sc_trace(mVcdFile, sh_assign_2_fu_645_p3, "sh_assign_2_fu_645_p3");
    sc_trace(mVcdFile, sh_assign_3_cast_fu_653_p1, "sh_assign_3_cast_fu_653_p1");
    sc_trace(mVcdFile, Mx_V_fu_611_p4, "Mx_V_fu_611_p4");
    sc_trace(mVcdFile, tmp_23_i_fu_657_p1, "tmp_23_i_fu_657_p1");
    sc_trace(mVcdFile, tmp_24_i_fu_661_p2, "tmp_24_i_fu_661_p2");
    sc_trace(mVcdFile, tmp_25_i_fu_667_p2, "tmp_25_i_fu_667_p2");
    sc_trace(mVcdFile, p_Val2_9_fu_691_p1, "p_Val2_9_fu_691_p1");
    sc_trace(mVcdFile, p_Val2_9_fu_691_p2, "p_Val2_9_fu_691_p2");
    sc_trace(mVcdFile, tmp_14_fu_697_p4, "tmp_14_fu_697_p4");
    sc_trace(mVcdFile, tmp_39_fu_711_p1, "tmp_39_fu_711_p1");
    sc_trace(mVcdFile, p_Val2_s_fu_724_p0, "p_Val2_s_fu_724_p0");
    sc_trace(mVcdFile, p_Val2_s_fu_724_p2, "p_Val2_s_fu_724_p2");
    sc_trace(mVcdFile, tmp_15_fu_730_p4, "tmp_15_fu_730_p4");
    sc_trace(mVcdFile, tmp_38_fu_764_p1, "tmp_38_fu_764_p1");
    sc_trace(mVcdFile, y_s_V_fu_768_p2, "y_s_V_fu_768_p2");
    sc_trace(mVcdFile, r_V_i2_fu_780_p2, "r_V_i2_fu_780_p2");
    sc_trace(mVcdFile, r_V_4_i_fu_774_p2, "r_V_4_i_fu_774_p2");
    sc_trace(mVcdFile, x_s_V_fu_794_p2, "x_s_V_fu_794_p2");
    sc_trace(mVcdFile, r_V_1_i_fu_800_p2, "r_V_1_i_fu_800_p2");
    sc_trace(mVcdFile, r_V_i7_fu_806_p2, "r_V_i7_fu_806_p2");
    sc_trace(mVcdFile, tmp_42_fu_825_p2, "tmp_42_fu_825_p2");
    sc_trace(mVcdFile, tmp_41_fu_846_p3, "tmp_41_fu_846_p3");
    sc_trace(mVcdFile, tmp_46_cast_fu_854_p1, "tmp_46_cast_fu_854_p1");
    sc_trace(mVcdFile, p_Val2_27_cast_fu_836_p4, "p_Val2_27_cast_fu_836_p4");
    sc_trace(mVcdFile, z_s_V_fu_858_p2, "z_s_V_fu_858_p2");
    sc_trace(mVcdFile, z_s_V_cast_fu_864_p1, "z_s_V_cast_fu_864_p1");
    sc_trace(mVcdFile, r_V_i_fu_874_p2, "r_V_i_fu_874_p2");
    sc_trace(mVcdFile, r_V_5_i_fu_868_p2, "r_V_5_i_fu_868_p2");
    sc_trace(mVcdFile, tmp_218_to_int_fu_887_p1, "tmp_218_to_int_fu_887_p1");
    sc_trace(mVcdFile, tmp_218_neg_fu_891_p2, "tmp_218_neg_fu_891_p2");
    sc_trace(mVcdFile, tmp_216_to_int_fu_902_p1, "tmp_216_to_int_fu_902_p1");
    sc_trace(mVcdFile, tmp_216_neg_fu_906_p2, "tmp_216_neg_fu_906_p2");
    sc_trace(mVcdFile, tmp_217_to_int_fu_917_p1, "tmp_217_to_int_fu_917_p1");
    sc_trace(mVcdFile, tmp_217_neg_fu_921_p2, "tmp_217_neg_fu_921_p2");
    sc_trace(mVcdFile, tmp_214_to_int_fu_932_p1, "tmp_214_to_int_fu_932_p1");
    sc_trace(mVcdFile, tmp_214_neg_fu_936_p2, "tmp_214_neg_fu_936_p2");
    sc_trace(mVcdFile, tmp_215_to_int_fu_947_p1, "tmp_215_to_int_fu_947_p1");
    sc_trace(mVcdFile, tmp_215_neg_fu_951_p2, "tmp_215_neg_fu_951_p2");
    sc_trace(mVcdFile, tmp_213_to_int_fu_962_p1, "tmp_213_to_int_fu_962_p1");
    sc_trace(mVcdFile, tmp_213_neg_fu_966_p2, "tmp_213_neg_fu_966_p2");
    sc_trace(mVcdFile, tmp_212_to_int_fu_977_p1, "tmp_212_to_int_fu_977_p1");
    sc_trace(mVcdFile, tmp_212_neg_fu_981_p2, "tmp_212_neg_fu_981_p2");
    sc_trace(mVcdFile, tmp_219_to_int_fu_992_p1, "tmp_219_to_int_fu_992_p1");
    sc_trace(mVcdFile, tmp_219_neg_fu_996_p2, "tmp_219_neg_fu_996_p2");
    sc_trace(mVcdFile, ap_return_0_preg, "ap_return_0_preg");
    sc_trace(mVcdFile, ap_return_1_preg, "ap_return_1_preg");
    sc_trace(mVcdFile, ap_NS_fsm, "ap_NS_fsm");
    sc_trace(mVcdFile, p_Val2_9_fu_691_p10, "p_Val2_9_fu_691_p10");
    sc_trace(mVcdFile, p_Val2_s_fu_724_p00, "p_Val2_s_fu_724_p00");
    sc_trace(mVcdFile, r_V_1_fu_489_p00, "r_V_1_fu_489_p00");
    sc_trace(mVcdFile, r_V_1_fu_489_p10, "r_V_1_fu_489_p10");
#endif

    }
}

cordic_sincos_generi::~cordic_sincos_generi() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

    delete ref_4oPi_table_100_V_U;
    delete cordic_ctab_table_12_1_U;
    delete grp_scaled_fixed2ieee_fu_344;
    delete grp_scaled_fixed2ieee_fu_356;
}

void cordic_sincos_generi::thread_ap_var_for_const0() {
    ap_var_for_const0 = ap_const_lv6_0;
}

void cordic_sincos_generi::thread_ap_clk_no_reset_() {
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_CS_fsm = ap_ST_fsm_state1;
    } else {
        ap_CS_fsm = ap_NS_fsm.read();
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_return_0_preg = ap_const_lv32_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read()) && 
             esl_seteq<1,1,1>(ap_const_boolean_0, ap_block_state7_on_subcall_done.read()))) {
            ap_return_0_preg = ap_phi_mux_s_out_write_assign_phi_fu_292_p20.read();
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_return_1_preg = ap_const_lv32_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read()) && 
             esl_seteq<1,1,1>(ap_const_boolean_0, ap_block_state7_on_subcall_done.read()))) {
            ap_return_1_preg = ap_phi_mux_c_out_write_assign_phi_fu_320_p20.read();
        }
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
         esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1) && 
         esl_seteq<1,1,1>(tmp_s_fu_390_p2.read(), ap_const_lv1_1))) {
        c_out_write_assign_reg_315 = ap_const_lv32_7FFFFFFF;
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
                esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1) && 
                esl_seteq<1,1,1>(tmp_s_fu_390_p2.read(), ap_const_lv1_0) && 
                esl_seteq<1,1,1>(tmp_36_fu_396_p2.read(), ap_const_lv1_1))) {
        c_out_write_assign_reg_315 = ap_const_lv32_3F800000;
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read()) && 
                esl_seteq<1,1,1>(tmp_s_reg_1029.read(), ap_const_lv1_0) && 
                esl_seteq<1,1,1>(tmp_36_reg_1033.read(), ap_const_lv1_0) && 
                esl_seteq<1,1,1>(ap_const_boolean_0, ap_block_state7_on_subcall_done.read()) && 
                esl_seteq<1,3,3>(sel_reg_1132.read(), ap_const_lv3_2))) {
        c_out_write_assign_reg_315 = tmp_44_fu_987_p1.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read()) && 
                esl_seteq<1,1,1>(tmp_s_reg_1029.read(), ap_const_lv1_0) && 
                esl_seteq<1,1,1>(tmp_36_reg_1033.read(), ap_const_lv1_0) && 
                esl_seteq<1,1,1>(ap_const_boolean_0, ap_block_state7_on_subcall_done.read()) && 
                esl_seteq<1,3,3>(sel_reg_1132.read(), ap_const_lv3_3))) {
        c_out_write_assign_reg_315 = tmp_45_fu_972_p1.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read()) && 
                esl_seteq<1,1,1>(tmp_s_reg_1029.read(), ap_const_lv1_0) && 
                esl_seteq<1,1,1>(tmp_36_reg_1033.read(), ap_const_lv1_0) && 
                esl_seteq<1,1,1>(ap_const_boolean_0, ap_block_state7_on_subcall_done.read()) && 
                esl_seteq<1,3,3>(sel_reg_1132.read(), ap_const_lv3_4))) {
        c_out_write_assign_reg_315 = tmp_47_fu_957_p1.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read()) && 
                esl_seteq<1,1,1>(tmp_s_reg_1029.read(), ap_const_lv1_0) && 
                esl_seteq<1,1,1>(tmp_36_reg_1033.read(), ap_const_lv1_0) && 
                esl_seteq<1,1,1>(ap_const_boolean_0, ap_block_state7_on_subcall_done.read()) && 
                esl_seteq<1,3,3>(sel_reg_1132.read(), ap_const_lv3_5))) {
        c_out_write_assign_reg_315 = tmp_49_fu_927_p1.read();
    } else if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read()) && 
                 esl_seteq<1,1,1>(tmp_s_reg_1029.read(), ap_const_lv1_0) && 
                 esl_seteq<1,1,1>(tmp_36_reg_1033.read(), ap_const_lv1_0) && 
                 esl_seteq<1,1,1>(ap_const_boolean_0, ap_block_state7_on_subcall_done.read()) && 
                 esl_seteq<1,3,3>(sel_reg_1132.read(), ap_const_lv3_6)) || 
                (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read()) && 
                 esl_seteq<1,1,1>(tmp_s_reg_1029.read(), ap_const_lv1_0) && 
                 esl_seteq<1,1,1>(tmp_36_reg_1033.read(), ap_const_lv1_0) && 
                 esl_seteq<1,1,1>(ap_const_boolean_0, ap_block_state7_on_subcall_done.read()) && 
                 esl_seteq<1,3,3>(sel_reg_1132.read(), ap_const_lv3_1)))) {
        c_out_write_assign_reg_315 = grp_scaled_fixed2ieee_fu_344_ap_return.read();
    } else if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read()) && 
                 esl_seteq<1,1,1>(tmp_s_reg_1029.read(), ap_const_lv1_0) && 
                 esl_seteq<1,1,1>(tmp_36_reg_1033.read(), ap_const_lv1_0) && 
                 esl_seteq<1,1,1>(ap_const_boolean_0, ap_block_state7_on_subcall_done.read()) && 
                 esl_seteq<1,3,3>(sel_reg_1132.read(), ap_const_lv3_7)) || 
                (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read()) && 
                 esl_seteq<1,1,1>(tmp_s_reg_1029.read(), ap_const_lv1_0) && 
                 esl_seteq<1,1,1>(tmp_36_reg_1033.read(), ap_const_lv1_0) && 
                 esl_seteq<1,1,1>(ap_const_boolean_0, ap_block_state7_on_subcall_done.read()) && 
                 esl_seteq<1,3,3>(sel_reg_1132.read(), ap_const_lv3_0)))) {
        c_out_write_assign_reg_315 = grp_scaled_fixed2ieee_fu_356_ap_return.read();
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        grp_scaled_fixed2ieee_fu_344_ap_start_reg = ap_const_logic_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read()) && 
             (esl_seteq<1,1,1>(exitcond_i_fu_744_p2.read(), ap_const_lv1_1) || 
              esl_seteq<1,1,1>(tmp_37_reg_1085.read(), ap_const_lv1_1)))) {
            grp_scaled_fixed2ieee_fu_344_ap_start_reg = ap_const_logic_1;
        } else if (esl_seteq<1,1,1>(ap_const_logic_1, grp_scaled_fixed2ieee_fu_344_ap_ready.read())) {
            grp_scaled_fixed2ieee_fu_344_ap_start_reg = ap_const_logic_0;
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        grp_scaled_fixed2ieee_fu_356_ap_start_reg = ap_const_logic_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read()) && 
             (esl_seteq<1,1,1>(exitcond_i_fu_744_p2.read(), ap_const_lv1_1) || 
              esl_seteq<1,1,1>(tmp_37_reg_1085.read(), ap_const_lv1_1)))) {
            grp_scaled_fixed2ieee_fu_356_ap_start_reg = ap_const_logic_1;
        } else if (esl_seteq<1,1,1>(ap_const_logic_1, grp_scaled_fixed2ieee_fu_356_ap_ready.read())) {
            grp_scaled_fixed2ieee_fu_356_ap_start_reg = ap_const_logic_0;
        }
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read()) && 
         esl_seteq<1,1,1>(tmp_37_reg_1085.read(), ap_const_lv1_0) && 
         esl_seteq<1,1,1>(exitcond_i_fu_744_p2.read(), ap_const_lv1_1))) {
        p_0_reg_253 = p_Val2_2_reg_231.read();
    } else if ((esl_seteq<1,1,1>(tmp_37_fu_681_p2.read(), ap_const_lv1_1) && 
                esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()))) {
        p_0_reg_253 = ap_const_lv43_10000000000;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read()) && 
         esl_seteq<1,1,1>(tmp_37_reg_1085.read(), ap_const_lv1_0) && 
         esl_seteq<1,1,1>(exitcond_i_fu_744_p2.read(), ap_const_lv1_1))) {
        p_1_reg_266 = p_Val2_1_reg_220.read();
    } else if ((esl_seteq<1,1,1>(tmp_37_fu_681_p2.read(), ap_const_lv1_1) && 
                esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()))) {
        p_1_reg_266 = y_V_fu_707_p1.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read())) {
        p_Val2_18_reg_210 = tz_V_fu_880_p3.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read())) {
        p_Val2_18_reg_210 = z_V_fu_740_p1.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read())) {
        p_Val2_1_reg_220 = ty_V_reg_1122.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read())) {
        p_Val2_1_reg_220 = ap_const_lv43_0;
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read())) {
        p_Val2_2_reg_231 = tx_V_reg_1117.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read())) {
        p_Val2_2_reg_231 = ap_const_lv43_9B74EDA843;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read()) && 
         esl_seteq<1,1,1>(tmp_37_reg_1085.read(), ap_const_lv1_0) && 
         esl_seteq<1,1,1>(exitcond_i_fu_744_p2.read(), ap_const_lv1_1))) {
        p_s_reg_277 = ap_const_lv6_0;
    } else if ((esl_seteq<1,1,1>(tmp_37_fu_681_p2.read(), ap_const_lv1_1) && 
                esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()))) {
        p_s_reg_277 = yprescale_V_cast_fu_715_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
         esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1) && 
         esl_seteq<1,1,1>(tmp_s_fu_390_p2.read(), ap_const_lv1_1))) {
        s_out_write_assign_reg_288 = ap_const_lv32_7FFFFFFF;
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
                esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1) && 
                esl_seteq<1,1,1>(tmp_s_fu_390_p2.read(), ap_const_lv1_0) && 
                esl_seteq<1,1,1>(tmp_36_fu_396_p2.read(), ap_const_lv1_1))) {
        s_out_write_assign_reg_288 = t_in.read();
    } else if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read()) && 
                 esl_seteq<1,1,1>(tmp_s_reg_1029.read(), ap_const_lv1_0) && 
                 esl_seteq<1,1,1>(tmp_36_reg_1033.read(), ap_const_lv1_0) && 
                 esl_seteq<1,1,1>(ap_const_boolean_0, ap_block_state7_on_subcall_done.read()) && 
                 esl_seteq<1,3,3>(sel_reg_1132.read(), ap_const_lv3_2)) || 
                (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read()) && 
                 esl_seteq<1,1,1>(tmp_s_reg_1029.read(), ap_const_lv1_0) && 
                 esl_seteq<1,1,1>(tmp_36_reg_1033.read(), ap_const_lv1_0) && 
                 esl_seteq<1,1,1>(ap_const_boolean_0, ap_block_state7_on_subcall_done.read()) && 
                 esl_seteq<1,3,3>(sel_reg_1132.read(), ap_const_lv3_1)))) {
        s_out_write_assign_reg_288 = grp_scaled_fixed2ieee_fu_356_ap_return.read();
    } else if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read()) && 
                 esl_seteq<1,1,1>(tmp_s_reg_1029.read(), ap_const_lv1_0) && 
                 esl_seteq<1,1,1>(tmp_36_reg_1033.read(), ap_const_lv1_0) && 
                 esl_seteq<1,1,1>(ap_const_boolean_0, ap_block_state7_on_subcall_done.read()) && 
                 esl_seteq<1,3,3>(sel_reg_1132.read(), ap_const_lv3_3)) || 
                (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read()) && 
                 esl_seteq<1,1,1>(tmp_s_reg_1029.read(), ap_const_lv1_0) && 
                 esl_seteq<1,1,1>(tmp_36_reg_1033.read(), ap_const_lv1_0) && 
                 esl_seteq<1,1,1>(ap_const_boolean_0, ap_block_state7_on_subcall_done.read()) && 
                 esl_seteq<1,3,3>(sel_reg_1132.read(), ap_const_lv3_0)))) {
        s_out_write_assign_reg_288 = grp_scaled_fixed2ieee_fu_344_ap_return.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read()) && 
                esl_seteq<1,1,1>(tmp_s_reg_1029.read(), ap_const_lv1_0) && 
                esl_seteq<1,1,1>(tmp_36_reg_1033.read(), ap_const_lv1_0) && 
                esl_seteq<1,1,1>(ap_const_boolean_0, ap_block_state7_on_subcall_done.read()) && 
                esl_seteq<1,3,3>(sel_reg_1132.read(), ap_const_lv3_4))) {
        s_out_write_assign_reg_288 = tmp_46_fu_942_p1.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read()) && 
                esl_seteq<1,1,1>(tmp_s_reg_1029.read(), ap_const_lv1_0) && 
                esl_seteq<1,1,1>(tmp_36_reg_1033.read(), ap_const_lv1_0) && 
                esl_seteq<1,1,1>(ap_const_boolean_0, ap_block_state7_on_subcall_done.read()) && 
                esl_seteq<1,3,3>(sel_reg_1132.read(), ap_const_lv3_5))) {
        s_out_write_assign_reg_288 = tmp_48_fu_912_p1.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read()) && 
                esl_seteq<1,1,1>(tmp_s_reg_1029.read(), ap_const_lv1_0) && 
                esl_seteq<1,1,1>(tmp_36_reg_1033.read(), ap_const_lv1_0) && 
                esl_seteq<1,1,1>(ap_const_boolean_0, ap_block_state7_on_subcall_done.read()) && 
                esl_seteq<1,3,3>(sel_reg_1132.read(), ap_const_lv3_6))) {
        s_out_write_assign_reg_288 = tmp_50_fu_897_p1.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read()) && 
                esl_seteq<1,1,1>(tmp_s_reg_1029.read(), ap_const_lv1_0) && 
                esl_seteq<1,1,1>(tmp_36_reg_1033.read(), ap_const_lv1_0) && 
                esl_seteq<1,1,1>(ap_const_boolean_0, ap_block_state7_on_subcall_done.read()) && 
                esl_seteq<1,3,3>(sel_reg_1132.read(), ap_const_lv3_7))) {
        s_out_write_assign_reg_288 = tmp_43_fu_1002_p1.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read())) {
        sh_assign_reg_242 = k_reg_1107.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read())) {
        sh_assign_reg_242 = ap_const_lv6_0;
    }
    if ((esl_seteq<1,1,1>(tmp_36_fu_396_p2.read(), ap_const_lv1_0) && esl_seteq<1,1,1>(tmp_s_fu_390_p2.read(), ap_const_lv1_0) && esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
        closepath_reg_1037 = closepath_fu_402_p2.read();
        p_Result_9_reg_1048 = p_Result_9_fu_418_p1.read();
        tmp_34_reg_1058 = tmp_34_fu_451_p1.read();
        tmp_reg_1043 = p_Val2_7_fu_368_p1.read().range(27, 23);
    }
    if ((esl_seteq<1,1,1>(tmp_37_reg_1085.read(), ap_const_lv1_0) && esl_seteq<1,1,1>(exitcond_i_fu_744_p2.read(), ap_const_lv1_0) && esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read()))) {
        d_V_reg_1112 = p_Val2_18_reg_210.read().range(42, 42);
        tx_V_reg_1117 = tx_V_fu_786_p3.read();
        ty_V_reg_1122 = ty_V_fu_812_p3.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read())) {
        fout_V_reg_1080 = fout_V_fu_673_p3.read();
        p_Val2_23_reg_1074 = p_Val2_23_fu_531_p3.read();
        tmp_37_reg_1085 = tmp_37_fu_681_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read()) && esl_seteq<1,1,1>(tmp_37_reg_1085.read(), ap_const_lv1_0))) {
        k_reg_1107 = k_fu_750_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
        p_Result_s_reg_1024 = p_Val2_7_fu_368_p1.read().range(31, 31);
        tmp_s_reg_1029 = tmp_s_fu_390_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read())) {
        p_Val2_13_reg_1063 = r_V_1_fu_489_p2.read().range(76, 8);
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read()) && (esl_seteq<1,1,1>(exitcond_i_fu_744_p2.read(), ap_const_lv1_1) || 
  esl_seteq<1,1,1>(tmp_37_reg_1085.read(), ap_const_lv1_1)))) {
        sel_reg_1132 = sel_fu_830_p3.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, closepath_reg_1037.read()))) {
        tmp_16_i_reg_1069 = r_V_1_fu_489_p2.read().range(79, 77);
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1) && esl_seteq<1,1,1>(tmp_s_fu_390_p2.read(), ap_const_lv1_0))) {
        tmp_36_reg_1033 = tmp_36_fu_396_p2.read();
    }
}

void cordic_sincos_generi::thread_Ex_V_fu_625_p2() {
    Ex_V_fu_625_p2 = (!storemerge_i_cast_fu_527_p1.read().is_01() || !tmp_20_i_cast_fu_621_p1.read().is_01())? sc_lv<7>(): (sc_bigint<7>(storemerge_i_cast_fu_527_p1.read()) - sc_biguint<7>(tmp_20_i_cast_fu_621_p1.read()));
}

void cordic_sincos_generi::thread_Med_V_fu_471_p4() {
    Med_V_fu_471_p4 = r_V_fu_465_p2.read().range(99, 20);
}

void cordic_sincos_generi::thread_Mx_V_fu_611_p4() {
    Mx_V_fu_611_p4 = p_Val2_17_fu_605_p2.read().range(68, 29);
}

void cordic_sincos_generi::thread_Mx_zeros_V_fu_597_p1() {
    Mx_zeros_V_fu_597_p1 = val_assign_fu_589_p3.read().range(5-1, 0);
}

void cordic_sincos_generi::thread_addr_V_fu_428_p3() {
    addr_V_fu_428_p3 = (!closepath_fu_402_p2.read()[0].is_01())? sc_lv<8>(): ((closepath_fu_402_p2.read()[0].to_bool())? ap_const_lv8_3F: expv_op_fu_422_p2.read());
}

void cordic_sincos_generi::thread_ap_CS_fsm_state1() {
    ap_CS_fsm_state1 = ap_CS_fsm.read()[0];
}

void cordic_sincos_generi::thread_ap_CS_fsm_state2() {
    ap_CS_fsm_state2 = ap_CS_fsm.read()[1];
}

void cordic_sincos_generi::thread_ap_CS_fsm_state3() {
    ap_CS_fsm_state3 = ap_CS_fsm.read()[2];
}

void cordic_sincos_generi::thread_ap_CS_fsm_state4() {
    ap_CS_fsm_state4 = ap_CS_fsm.read()[3];
}

void cordic_sincos_generi::thread_ap_CS_fsm_state5() {
    ap_CS_fsm_state5 = ap_CS_fsm.read()[4];
}

void cordic_sincos_generi::thread_ap_CS_fsm_state6() {
    ap_CS_fsm_state6 = ap_CS_fsm.read()[5];
}

void cordic_sincos_generi::thread_ap_CS_fsm_state7() {
    ap_CS_fsm_state7 = ap_CS_fsm.read()[6];
}

void cordic_sincos_generi::thread_ap_block_state7_on_subcall_done() {
    ap_block_state7_on_subcall_done = ((esl_seteq<1,1,1>(ap_const_logic_0, grp_scaled_fixed2ieee_fu_344_ap_done.read()) && 
  esl_seteq<1,1,1>(ap_const_boolean_1, ap_predicate_op125_call_state7.read())) || (esl_seteq<1,1,1>(ap_const_boolean_1, ap_predicate_op125_call_state7.read()) && 
  esl_seteq<1,1,1>(ap_const_logic_0, grp_scaled_fixed2ieee_fu_356_ap_done.read())));
}

void cordic_sincos_generi::thread_ap_done() {
    if (((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read())) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read()) && 
          esl_seteq<1,1,1>(ap_const_boolean_0, ap_block_state7_on_subcall_done.read())))) {
        ap_done = ap_const_logic_1;
    } else {
        ap_done = ap_const_logic_0;
    }
}

void cordic_sincos_generi::thread_ap_idle() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()))) {
        ap_idle = ap_const_logic_1;
    } else {
        ap_idle = ap_const_logic_0;
    }
}

void cordic_sincos_generi::thread_ap_phi_mux_c_out_write_assign_phi_fu_320_p20() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read()) && 
         esl_seteq<1,1,1>(tmp_s_reg_1029.read(), ap_const_lv1_0) && 
         esl_seteq<1,1,1>(tmp_36_reg_1033.read(), ap_const_lv1_0) && 
         esl_seteq<1,3,3>(sel_reg_1132.read(), ap_const_lv3_2))) {
        ap_phi_mux_c_out_write_assign_phi_fu_320_p20 = tmp_44_fu_987_p1.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read()) && 
                esl_seteq<1,1,1>(tmp_s_reg_1029.read(), ap_const_lv1_0) && 
                esl_seteq<1,1,1>(tmp_36_reg_1033.read(), ap_const_lv1_0) && 
                esl_seteq<1,3,3>(sel_reg_1132.read(), ap_const_lv3_3))) {
        ap_phi_mux_c_out_write_assign_phi_fu_320_p20 = tmp_45_fu_972_p1.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read()) && 
                esl_seteq<1,1,1>(tmp_s_reg_1029.read(), ap_const_lv1_0) && 
                esl_seteq<1,1,1>(tmp_36_reg_1033.read(), ap_const_lv1_0) && 
                esl_seteq<1,3,3>(sel_reg_1132.read(), ap_const_lv3_4))) {
        ap_phi_mux_c_out_write_assign_phi_fu_320_p20 = tmp_47_fu_957_p1.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read()) && 
                esl_seteq<1,1,1>(tmp_s_reg_1029.read(), ap_const_lv1_0) && 
                esl_seteq<1,1,1>(tmp_36_reg_1033.read(), ap_const_lv1_0) && 
                esl_seteq<1,3,3>(sel_reg_1132.read(), ap_const_lv3_5))) {
        ap_phi_mux_c_out_write_assign_phi_fu_320_p20 = tmp_49_fu_927_p1.read();
    } else if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read()) && 
                 esl_seteq<1,1,1>(tmp_s_reg_1029.read(), ap_const_lv1_0) && 
                 esl_seteq<1,1,1>(tmp_36_reg_1033.read(), ap_const_lv1_0) && 
                 esl_seteq<1,3,3>(sel_reg_1132.read(), ap_const_lv3_6)) || 
                (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read()) && 
                 esl_seteq<1,1,1>(tmp_s_reg_1029.read(), ap_const_lv1_0) && 
                 esl_seteq<1,1,1>(tmp_36_reg_1033.read(), ap_const_lv1_0) && 
                 esl_seteq<1,3,3>(sel_reg_1132.read(), ap_const_lv3_1)))) {
        ap_phi_mux_c_out_write_assign_phi_fu_320_p20 = grp_scaled_fixed2ieee_fu_344_ap_return.read();
    } else if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read()) && 
                 esl_seteq<1,1,1>(tmp_s_reg_1029.read(), ap_const_lv1_0) && 
                 esl_seteq<1,1,1>(tmp_36_reg_1033.read(), ap_const_lv1_0) && 
                 esl_seteq<1,3,3>(sel_reg_1132.read(), ap_const_lv3_7)) || 
                (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read()) && 
                 esl_seteq<1,1,1>(tmp_s_reg_1029.read(), ap_const_lv1_0) && 
                 esl_seteq<1,1,1>(tmp_36_reg_1033.read(), ap_const_lv1_0) && 
                 esl_seteq<1,3,3>(sel_reg_1132.read(), ap_const_lv3_0)))) {
        ap_phi_mux_c_out_write_assign_phi_fu_320_p20 = grp_scaled_fixed2ieee_fu_356_ap_return.read();
    } else {
        ap_phi_mux_c_out_write_assign_phi_fu_320_p20 = c_out_write_assign_reg_315.read();
    }
}

void cordic_sincos_generi::thread_ap_phi_mux_s_out_write_assign_phi_fu_292_p20() {
    if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read()) && 
          esl_seteq<1,1,1>(tmp_s_reg_1029.read(), ap_const_lv1_0) && 
          esl_seteq<1,1,1>(tmp_36_reg_1033.read(), ap_const_lv1_0) && 
          esl_seteq<1,3,3>(sel_reg_1132.read(), ap_const_lv3_2)) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read()) && 
          esl_seteq<1,1,1>(tmp_s_reg_1029.read(), ap_const_lv1_0) && 
          esl_seteq<1,1,1>(tmp_36_reg_1033.read(), ap_const_lv1_0) && 
          esl_seteq<1,3,3>(sel_reg_1132.read(), ap_const_lv3_1)))) {
        ap_phi_mux_s_out_write_assign_phi_fu_292_p20 = grp_scaled_fixed2ieee_fu_356_ap_return.read();
    } else if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read()) && 
                 esl_seteq<1,1,1>(tmp_s_reg_1029.read(), ap_const_lv1_0) && 
                 esl_seteq<1,1,1>(tmp_36_reg_1033.read(), ap_const_lv1_0) && 
                 esl_seteq<1,3,3>(sel_reg_1132.read(), ap_const_lv3_3)) || 
                (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read()) && 
                 esl_seteq<1,1,1>(tmp_s_reg_1029.read(), ap_const_lv1_0) && 
                 esl_seteq<1,1,1>(tmp_36_reg_1033.read(), ap_const_lv1_0) && 
                 esl_seteq<1,3,3>(sel_reg_1132.read(), ap_const_lv3_0)))) {
        ap_phi_mux_s_out_write_assign_phi_fu_292_p20 = grp_scaled_fixed2ieee_fu_344_ap_return.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read()) && 
                esl_seteq<1,1,1>(tmp_s_reg_1029.read(), ap_const_lv1_0) && 
                esl_seteq<1,1,1>(tmp_36_reg_1033.read(), ap_const_lv1_0) && 
                esl_seteq<1,3,3>(sel_reg_1132.read(), ap_const_lv3_4))) {
        ap_phi_mux_s_out_write_assign_phi_fu_292_p20 = tmp_46_fu_942_p1.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read()) && 
                esl_seteq<1,1,1>(tmp_s_reg_1029.read(), ap_const_lv1_0) && 
                esl_seteq<1,1,1>(tmp_36_reg_1033.read(), ap_const_lv1_0) && 
                esl_seteq<1,3,3>(sel_reg_1132.read(), ap_const_lv3_5))) {
        ap_phi_mux_s_out_write_assign_phi_fu_292_p20 = tmp_48_fu_912_p1.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read()) && 
                esl_seteq<1,1,1>(tmp_s_reg_1029.read(), ap_const_lv1_0) && 
                esl_seteq<1,1,1>(tmp_36_reg_1033.read(), ap_const_lv1_0) && 
                esl_seteq<1,3,3>(sel_reg_1132.read(), ap_const_lv3_6))) {
        ap_phi_mux_s_out_write_assign_phi_fu_292_p20 = tmp_50_fu_897_p1.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read()) && 
                esl_seteq<1,1,1>(tmp_s_reg_1029.read(), ap_const_lv1_0) && 
                esl_seteq<1,1,1>(tmp_36_reg_1033.read(), ap_const_lv1_0) && 
                esl_seteq<1,3,3>(sel_reg_1132.read(), ap_const_lv3_7))) {
        ap_phi_mux_s_out_write_assign_phi_fu_292_p20 = tmp_43_fu_1002_p1.read();
    } else {
        ap_phi_mux_s_out_write_assign_phi_fu_292_p20 = s_out_write_assign_reg_288.read();
    }
}

void cordic_sincos_generi::thread_ap_predicate_op125_call_state7() {
    ap_predicate_op125_call_state7 = (esl_seteq<1,1,1>(tmp_s_reg_1029.read(), ap_const_lv1_0) && esl_seteq<1,1,1>(tmp_36_reg_1033.read(), ap_const_lv1_0));
}

void cordic_sincos_generi::thread_ap_ready() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read()) && 
         esl_seteq<1,1,1>(ap_const_boolean_0, ap_block_state7_on_subcall_done.read()))) {
        ap_ready = ap_const_logic_1;
    } else {
        ap_ready = ap_const_logic_0;
    }
}

void cordic_sincos_generi::thread_ap_return_0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read()) && 
         esl_seteq<1,1,1>(ap_const_boolean_0, ap_block_state7_on_subcall_done.read()))) {
        ap_return_0 = ap_phi_mux_s_out_write_assign_phi_fu_292_p20.read();
    } else {
        ap_return_0 = ap_return_0_preg.read();
    }
}

void cordic_sincos_generi::thread_ap_return_1() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read()) && 
         esl_seteq<1,1,1>(ap_const_boolean_0, ap_block_state7_on_subcall_done.read()))) {
        ap_return_1 = ap_phi_mux_c_out_write_assign_phi_fu_320_p20.read();
    } else {
        ap_return_1 = ap_return_1_preg.read();
    }
}

void cordic_sincos_generi::thread_closepath_fu_402_p2() {
    closepath_fu_402_p2 = (!loc_V_fu_380_p4.read().is_01() || !ap_const_lv8_7E.is_01())? sc_lv<1>(): (sc_biguint<8>(loc_V_fu_380_p4.read()) < sc_biguint<8>(ap_const_lv8_7E));
}

void cordic_sincos_generi::thread_cordic_ctab_table_12_1_address0() {
    cordic_ctab_table_12_1_address0 =  (sc_lv<7>) (tmp_40_fu_820_p1.read());
}

void cordic_sincos_generi::thread_cordic_ctab_table_12_1_ce0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read())) {
        cordic_ctab_table_12_1_ce0 = ap_const_logic_1;
    } else {
        cordic_ctab_table_12_1_ce0 = ap_const_logic_0;
    }
}

void cordic_sincos_generi::thread_d_V_fu_756_p3() {
    d_V_fu_756_p3 = p_Val2_18_reg_210.read().range(42, 42);
}

void cordic_sincos_generi::thread_exitcond_i_fu_744_p2() {
    exitcond_i_fu_744_p2 = (!sh_assign_reg_242.read().is_01() || !ap_const_lv6_2B.is_01())? sc_lv<1>(): sc_lv<1>(sh_assign_reg_242.read() == ap_const_lv6_2B);
}

void cordic_sincos_generi::thread_expv_op_fu_422_p2() {
    expv_op_fu_422_p2 = (!ap_const_lv8_C2.is_01() || !loc_V_fu_380_p4.read().is_01())? sc_lv<8>(): (sc_bigint<8>(ap_const_lv8_C2) + sc_biguint<8>(loc_V_fu_380_p4.read()));
}

void cordic_sincos_generi::thread_fout_V_fu_673_p3() {
    fout_V_fu_673_p3 = (!isNeg_fu_631_p3.read()[0].is_01())? sc_lv<40>(): ((isNeg_fu_631_p3.read()[0].to_bool())? tmp_24_i_fu_661_p2.read(): tmp_25_i_fu_667_p2.read());
}

void cordic_sincos_generi::thread_grp_scaled_fixed2ieee_fu_344_ap_start() {
    grp_scaled_fixed2ieee_fu_344_ap_start = grp_scaled_fixed2ieee_fu_344_ap_start_reg.read();
}

void cordic_sincos_generi::thread_grp_scaled_fixed2ieee_fu_356_ap_start() {
    grp_scaled_fixed2ieee_fu_356_ap_start = grp_scaled_fixed2ieee_fu_356_ap_start_reg.read();
}

void cordic_sincos_generi::thread_isNeg_fu_631_p3() {
    isNeg_fu_631_p3 = Ex_V_fu_625_p2.read().range(6, 6);
}

void cordic_sincos_generi::thread_k_fu_750_p2() {
    k_fu_750_p2 = (!sh_assign_reg_242.read().is_01() || !ap_const_lv6_1.is_01())? sc_lv<6>(): (sc_biguint<6>(sh_assign_reg_242.read()) + sc_biguint<6>(ap_const_lv6_1));
}

void cordic_sincos_generi::thread_loc_V_fu_380_p4() {
    loc_V_fu_380_p4 = p_Val2_7_fu_368_p1.read().range(30, 23);
}

void cordic_sincos_generi::thread_p_Result_10_fu_455_p3() {
    p_Result_10_fu_455_p3 = esl_concat<1,23>(ap_const_lv1_1, p_Result_9_reg_1048.read());
}

void cordic_sincos_generi::thread_p_Result_11_fu_563_p3() {
    p_Result_11_fu_563_p3 = esl_concat<29,1>(p_Result_i2_i_fu_553_p4.read(), ap_const_lv1_1);
}

void cordic_sincos_generi::thread_p_Result_12_fu_571_p4() {
    p_Result_12_fu_571_p4 = p_Result_11_fu_563_p3.read().range(0, 29);
}

void cordic_sincos_generi::thread_p_Result_13_fu_581_p3() {
    p_Result_13_fu_581_p3 = esl_concat<2,30>(ap_const_lv2_3, p_Result_12_fu_571_p4.read());
}

void cordic_sincos_generi::thread_p_Result_9_fu_418_p1() {
    p_Result_9_fu_418_p1 = p_Val2_7_fu_368_p1.read().range(23-1, 0);
}

void cordic_sincos_generi::thread_p_Result_i2_i_fu_553_p4() {
    p_Result_i2_i_fu_553_p4 = p_Val2_15_fu_546_p3.read().range(68, 40);
}

void cordic_sincos_generi::thread_p_Val2_15_fu_546_p3() {
    p_Val2_15_fu_546_p3 = (!tmp_35_fu_537_p1.read()[0].is_01())? sc_lv<69>(): ((tmp_35_fu_537_p1.read()[0].to_bool())? p_Val2_i_fu_541_p2.read(): p_Val2_13_reg_1063.read());
}

void cordic_sincos_generi::thread_p_Val2_17_fu_605_p2() {
    p_Val2_17_fu_605_p2 = (!tmp_17_i_fu_601_p1.read().is_01())? sc_lv<69>(): p_Val2_15_fu_546_p3.read() << (unsigned short)tmp_17_i_fu_601_p1.read().to_uint();
}

void cordic_sincos_generi::thread_p_Val2_23_fu_531_p3() {
    p_Val2_23_fu_531_p3 = (!closepath_reg_1037.read()[0].is_01())? sc_lv<3>(): ((closepath_reg_1037.read()[0].to_bool())? ap_const_lv3_0: tmp_16_i_reg_1069.read());
}

void cordic_sincos_generi::thread_p_Val2_27_cast_fu_836_p4() {
    p_Val2_27_cast_fu_836_p4 = cordic_ctab_table_12_1_q0.read().range(125, 86);
}

void cordic_sincos_generi::thread_p_Val2_7_fu_368_p1() {
    p_Val2_7_fu_368_p1 = t_in.read();
}

void cordic_sincos_generi::thread_p_Val2_9_fu_691_p1() {
    p_Val2_9_fu_691_p1 =  (sc_lv<40>) (p_Val2_9_fu_691_p10.read());
}

void cordic_sincos_generi::thread_p_Val2_9_fu_691_p10() {
    p_Val2_9_fu_691_p10 = esl_zext<80,40>(Mx_V_fu_611_p4.read());
}

void cordic_sincos_generi::thread_p_Val2_9_fu_691_p2() {
    p_Val2_9_fu_691_p2 = (!ap_const_lv80_C90FDAA221.is_01() || !p_Val2_9_fu_691_p1.read().is_01())? sc_lv<80>(): sc_biguint<80>(ap_const_lv80_C90FDAA221) * sc_biguint<40>(p_Val2_9_fu_691_p1.read());
}

void cordic_sincos_generi::thread_p_Val2_i_fu_541_p2() {
    p_Val2_i_fu_541_p2 = (!ap_const_lv69_0.is_01() || !p_Val2_13_reg_1063.read().is_01())? sc_lv<69>(): (sc_biguint<69>(ap_const_lv69_0) - sc_biguint<69>(p_Val2_13_reg_1063.read()));
}

void cordic_sincos_generi::thread_p_Val2_s_fu_724_p0() {
    p_Val2_s_fu_724_p0 =  (sc_lv<40>) (p_Val2_s_fu_724_p00.read());
}

void cordic_sincos_generi::thread_p_Val2_s_fu_724_p00() {
    p_Val2_s_fu_724_p00 = esl_zext<80,40>(fout_V_reg_1080.read());
}

void cordic_sincos_generi::thread_p_Val2_s_fu_724_p2() {
    p_Val2_s_fu_724_p2 = (!p_Val2_s_fu_724_p0.read().is_01() || !ap_const_lv80_C90FDAA221.is_01())? sc_lv<80>(): sc_biguint<40>(p_Val2_s_fu_724_p0.read()) * sc_biguint<80>(ap_const_lv80_C90FDAA221);
}

void cordic_sincos_generi::thread_p_i_cast_fu_515_p2() {
    p_i_cast_fu_515_p2 = (!ap_const_lv5_3.is_01() || !tmp_reg_1043.read().is_01())? sc_lv<5>(): (sc_biguint<5>(ap_const_lv5_3) + sc_biguint<5>(tmp_reg_1043.read()));
}

void cordic_sincos_generi::thread_r_V_1_fu_489_p0() {
    r_V_1_fu_489_p0 =  (sc_lv<80>) (r_V_1_fu_489_p00.read());
}

void cordic_sincos_generi::thread_r_V_1_fu_489_p00() {
    r_V_1_fu_489_p00 = esl_zext<104,80>(Med_V_fu_471_p4.read());
}

void cordic_sincos_generi::thread_r_V_1_fu_489_p1() {
    r_V_1_fu_489_p1 =  (sc_lv<24>) (r_V_1_fu_489_p10.read());
}

void cordic_sincos_generi::thread_r_V_1_fu_489_p10() {
    r_V_1_fu_489_p10 = esl_zext<104,24>(p_Result_10_fu_455_p3.read());
}

void cordic_sincos_generi::thread_r_V_1_fu_489_p2() {
    r_V_1_fu_489_p2 = (!r_V_1_fu_489_p0.read().is_01() || !r_V_1_fu_489_p1.read().is_01())? sc_lv<104>(): sc_biguint<80>(r_V_1_fu_489_p0.read()) * sc_biguint<24>(r_V_1_fu_489_p1.read());
}

void cordic_sincos_generi::thread_r_V_1_i_fu_800_p2() {
    r_V_1_i_fu_800_p2 = (!p_Val2_1_reg_220.read().is_01() || !x_s_V_fu_794_p2.read().is_01())? sc_lv<43>(): (sc_biguint<43>(p_Val2_1_reg_220.read()) - sc_biguint<43>(x_s_V_fu_794_p2.read()));
}

void cordic_sincos_generi::thread_r_V_4_i_fu_774_p2() {
    r_V_4_i_fu_774_p2 = (!p_Val2_2_reg_231.read().is_01() || !y_s_V_fu_768_p2.read().is_01())? sc_lv<43>(): (sc_biguint<43>(p_Val2_2_reg_231.read()) - sc_biguint<43>(y_s_V_fu_768_p2.read()));
}

void cordic_sincos_generi::thread_r_V_5_i_fu_868_p2() {
    r_V_5_i_fu_868_p2 = (!p_Val2_18_reg_210.read().is_01() || !z_s_V_cast_fu_864_p1.read().is_01())? sc_lv<43>(): (sc_biguint<43>(p_Val2_18_reg_210.read()) - sc_biguint<43>(z_s_V_cast_fu_864_p1.read()));
}

void cordic_sincos_generi::thread_r_V_fu_465_p2() {
    r_V_fu_465_p2 = (!tmp_7_i_i_fu_462_p1.read().is_01())? sc_lv<100>(): ref_4oPi_table_100_V_q0.read() << (unsigned short)tmp_7_i_i_fu_462_p1.read().to_uint();
}

void cordic_sincos_generi::thread_r_V_i2_fu_780_p2() {
    r_V_i2_fu_780_p2 = (!p_Val2_2_reg_231.read().is_01() || !y_s_V_fu_768_p2.read().is_01())? sc_lv<43>(): (sc_biguint<43>(p_Val2_2_reg_231.read()) + sc_biguint<43>(y_s_V_fu_768_p2.read()));
}

void cordic_sincos_generi::thread_r_V_i7_fu_806_p2() {
    r_V_i7_fu_806_p2 = (!p_Val2_1_reg_220.read().is_01() || !x_s_V_fu_794_p2.read().is_01())? sc_lv<43>(): (sc_biguint<43>(p_Val2_1_reg_220.read()) + sc_biguint<43>(x_s_V_fu_794_p2.read()));
}

void cordic_sincos_generi::thread_r_V_i_fu_874_p2() {
    r_V_i_fu_874_p2 = (!p_Val2_18_reg_210.read().is_01() || !z_s_V_cast_fu_864_p1.read().is_01())? sc_lv<43>(): (sc_biguint<43>(p_Val2_18_reg_210.read()) + sc_biguint<43>(z_s_V_cast_fu_864_p1.read()));
}

void cordic_sincos_generi::thread_ref_4oPi_table_100_V_address0() {
    ref_4oPi_table_100_V_address0 =  (sc_lv<4>) (tmp_5_i_i_fu_446_p1.read());
}

void cordic_sincos_generi::thread_ref_4oPi_table_100_V_ce0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
         esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
        ref_4oPi_table_100_V_ce0 = ap_const_logic_1;
    } else {
        ref_4oPi_table_100_V_ce0 = ap_const_logic_0;
    }
}

void cordic_sincos_generi::thread_sel_fu_830_p3() {
    sel_fu_830_p3 = (!p_Result_s_reg_1024.read()[0].is_01())? sc_lv<3>(): ((p_Result_s_reg_1024.read()[0].to_bool())? tmp_42_fu_825_p2.read(): p_Val2_23_reg_1074.read());
}

void cordic_sincos_generi::thread_sh_assign_2_fu_645_p3() {
    sh_assign_2_fu_645_p3 = (!isNeg_fu_631_p3.read()[0].is_01())? sc_lv<7>(): ((isNeg_fu_631_p3.read()[0].to_bool())? tmp_22_i_fu_639_p2.read(): Ex_V_fu_625_p2.read());
}

void cordic_sincos_generi::thread_sh_assign_3_cast_fu_653_p1() {
    sh_assign_3_cast_fu_653_p1 = esl_sext<32,7>(sh_assign_2_fu_645_p3.read());
}

void cordic_sincos_generi::thread_storemerge_i_cast_fu_527_p1() {
    storemerge_i_cast_fu_527_p1 = esl_sext<7,5>(storemerge_i_fu_520_p3.read());
}

void cordic_sincos_generi::thread_storemerge_i_fu_520_p3() {
    storemerge_i_fu_520_p3 = (!closepath_reg_1037.read()[0].is_01())? sc_lv<5>(): ((closepath_reg_1037.read()[0].to_bool())? p_i_cast_fu_515_p2.read(): ap_const_lv5_0);
}

void cordic_sincos_generi::thread_tmp_12_fu_436_p4() {
    tmp_12_fu_436_p4 = addr_V_fu_428_p3.read().range(7, 4);
}

void cordic_sincos_generi::thread_tmp_14_fu_697_p4() {
    tmp_14_fu_697_p4 = p_Val2_9_fu_691_p2.read().range(79, 40);
}

void cordic_sincos_generi::thread_tmp_15_fu_730_p4() {
    tmp_15_fu_730_p4 = p_Val2_s_fu_724_p2.read().range(79, 40);
}

void cordic_sincos_generi::thread_tmp_17_i_fu_601_p1() {
    tmp_17_i_fu_601_p1 = esl_zext<69,5>(Mx_zeros_V_fu_597_p1.read());
}

void cordic_sincos_generi::thread_tmp_20_i_cast_fu_621_p1() {
    tmp_20_i_cast_fu_621_p1 = esl_zext<7,5>(Mx_zeros_V_fu_597_p1.read());
}

void cordic_sincos_generi::thread_tmp_212_neg_fu_981_p2() {
    tmp_212_neg_fu_981_p2 = (tmp_212_to_int_fu_977_p1.read() ^ ap_const_lv32_80000000);
}

void cordic_sincos_generi::thread_tmp_212_to_int_fu_977_p1() {
    tmp_212_to_int_fu_977_p1 = grp_scaled_fixed2ieee_fu_344_ap_return.read();
}

void cordic_sincos_generi::thread_tmp_213_neg_fu_966_p2() {
    tmp_213_neg_fu_966_p2 = (tmp_213_to_int_fu_962_p1.read() ^ ap_const_lv32_80000000);
}

void cordic_sincos_generi::thread_tmp_213_to_int_fu_962_p1() {
    tmp_213_to_int_fu_962_p1 = grp_scaled_fixed2ieee_fu_356_ap_return.read();
}

void cordic_sincos_generi::thread_tmp_214_neg_fu_936_p2() {
    tmp_214_neg_fu_936_p2 = (tmp_214_to_int_fu_932_p1.read() ^ ap_const_lv32_80000000);
}

void cordic_sincos_generi::thread_tmp_214_to_int_fu_932_p1() {
    tmp_214_to_int_fu_932_p1 = grp_scaled_fixed2ieee_fu_344_ap_return.read();
}

void cordic_sincos_generi::thread_tmp_215_neg_fu_951_p2() {
    tmp_215_neg_fu_951_p2 = (tmp_215_to_int_fu_947_p1.read() ^ ap_const_lv32_80000000);
}

void cordic_sincos_generi::thread_tmp_215_to_int_fu_947_p1() {
    tmp_215_to_int_fu_947_p1 = grp_scaled_fixed2ieee_fu_356_ap_return.read();
}

void cordic_sincos_generi::thread_tmp_216_neg_fu_906_p2() {
    tmp_216_neg_fu_906_p2 = (tmp_216_to_int_fu_902_p1.read() ^ ap_const_lv32_80000000);
}

void cordic_sincos_generi::thread_tmp_216_to_int_fu_902_p1() {
    tmp_216_to_int_fu_902_p1 = grp_scaled_fixed2ieee_fu_356_ap_return.read();
}

void cordic_sincos_generi::thread_tmp_217_neg_fu_921_p2() {
    tmp_217_neg_fu_921_p2 = (tmp_217_to_int_fu_917_p1.read() ^ ap_const_lv32_80000000);
}

void cordic_sincos_generi::thread_tmp_217_to_int_fu_917_p1() {
    tmp_217_to_int_fu_917_p1 = grp_scaled_fixed2ieee_fu_344_ap_return.read();
}

void cordic_sincos_generi::thread_tmp_218_neg_fu_891_p2() {
    tmp_218_neg_fu_891_p2 = (tmp_218_to_int_fu_887_p1.read() ^ ap_const_lv32_80000000);
}

void cordic_sincos_generi::thread_tmp_218_to_int_fu_887_p1() {
    tmp_218_to_int_fu_887_p1 = grp_scaled_fixed2ieee_fu_356_ap_return.read();
}

void cordic_sincos_generi::thread_tmp_219_neg_fu_996_p2() {
    tmp_219_neg_fu_996_p2 = (tmp_219_to_int_fu_992_p1.read() ^ ap_const_lv32_80000000);
}

void cordic_sincos_generi::thread_tmp_219_to_int_fu_992_p1() {
    tmp_219_to_int_fu_992_p1 = grp_scaled_fixed2ieee_fu_344_ap_return.read();
}

void cordic_sincos_generi::thread_tmp_22_i_fu_639_p2() {
    tmp_22_i_fu_639_p2 = (!ap_const_lv7_0.is_01() || !Ex_V_fu_625_p2.read().is_01())? sc_lv<7>(): (sc_biguint<7>(ap_const_lv7_0) - sc_biguint<7>(Ex_V_fu_625_p2.read()));
}

void cordic_sincos_generi::thread_tmp_23_i_fu_657_p1() {
    tmp_23_i_fu_657_p1 = esl_zext<40,32>(sh_assign_3_cast_fu_653_p1.read());
}

void cordic_sincos_generi::thread_tmp_24_i_fu_661_p2() {
    tmp_24_i_fu_661_p2 = (!tmp_23_i_fu_657_p1.read().is_01())? sc_lv<40>(): Mx_V_fu_611_p4.read() >> (unsigned short)tmp_23_i_fu_657_p1.read().to_uint();
}

void cordic_sincos_generi::thread_tmp_25_i_fu_667_p2() {
    tmp_25_i_fu_667_p2 = (!tmp_23_i_fu_657_p1.read().is_01())? sc_lv<40>(): Mx_V_fu_611_p4.read() << (unsigned short)tmp_23_i_fu_657_p1.read().to_uint();
}

void cordic_sincos_generi::thread_tmp_34_fu_451_p1() {
    tmp_34_fu_451_p1 = addr_V_fu_428_p3.read().range(4-1, 0);
}

void cordic_sincos_generi::thread_tmp_35_fu_537_p1() {
    tmp_35_fu_537_p1 = p_Val2_23_fu_531_p3.read().range(1-1, 0);
}

void cordic_sincos_generi::thread_tmp_36_fu_396_p2() {
    tmp_36_fu_396_p2 = (!loc_V_fu_380_p4.read().is_01() || !ap_const_lv8_73.is_01())? sc_lv<1>(): (sc_biguint<8>(loc_V_fu_380_p4.read()) < sc_biguint<8>(ap_const_lv8_73));
}

void cordic_sincos_generi::thread_tmp_37_fu_681_p2() {
    tmp_37_fu_681_p2 = (!Ex_V_fu_625_p2.read().is_01() || !ap_const_lv7_74.is_01())? sc_lv<1>(): (sc_bigint<7>(Ex_V_fu_625_p2.read()) < sc_bigint<7>(ap_const_lv7_74));
}

void cordic_sincos_generi::thread_tmp_38_fu_764_p1() {
    tmp_38_fu_764_p1 = esl_zext<43,6>(sh_assign_reg_242.read());
}

void cordic_sincos_generi::thread_tmp_39_fu_711_p1() {
    tmp_39_fu_711_p1 = Ex_V_fu_625_p2.read().range(6-1, 0);
}

void cordic_sincos_generi::thread_tmp_40_fu_820_p1() {
    tmp_40_fu_820_p1 = esl_zext<64,6>(sh_assign_reg_242.read());
}

void cordic_sincos_generi::thread_tmp_41_fu_846_p3() {
    tmp_41_fu_846_p3 = cordic_ctab_table_12_1_q0.read().range(85, 85);
}

void cordic_sincos_generi::thread_tmp_42_fu_825_p2() {
    tmp_42_fu_825_p2 = (p_Val2_23_reg_1074.read() ^ ap_const_lv3_7);
}

void cordic_sincos_generi::thread_tmp_43_fu_1002_p1() {
    tmp_43_fu_1002_p1 = tmp_219_neg_fu_996_p2.read();
}

void cordic_sincos_generi::thread_tmp_44_fu_987_p1() {
    tmp_44_fu_987_p1 = tmp_212_neg_fu_981_p2.read();
}

void cordic_sincos_generi::thread_tmp_45_fu_972_p1() {
    tmp_45_fu_972_p1 = tmp_213_neg_fu_966_p2.read();
}

void cordic_sincos_generi::thread_tmp_46_cast_fu_854_p1() {
    tmp_46_cast_fu_854_p1 = esl_zext<40,1>(tmp_41_fu_846_p3.read());
}

void cordic_sincos_generi::thread_tmp_46_fu_942_p1() {
    tmp_46_fu_942_p1 = tmp_214_neg_fu_936_p2.read();
}

void cordic_sincos_generi::thread_tmp_47_fu_957_p1() {
    tmp_47_fu_957_p1 = tmp_215_neg_fu_951_p2.read();
}

void cordic_sincos_generi::thread_tmp_48_fu_912_p1() {
    tmp_48_fu_912_p1 = tmp_216_neg_fu_906_p2.read();
}

void cordic_sincos_generi::thread_tmp_49_fu_927_p1() {
    tmp_49_fu_927_p1 = tmp_217_neg_fu_921_p2.read();
}

void cordic_sincos_generi::thread_tmp_50_fu_897_p1() {
    tmp_50_fu_897_p1 = tmp_218_neg_fu_891_p2.read();
}

void cordic_sincos_generi::thread_tmp_5_i_i_fu_446_p1() {
    tmp_5_i_i_fu_446_p1 = esl_zext<64,4>(tmp_12_fu_436_p4.read());
}

void cordic_sincos_generi::thread_tmp_7_i_i_fu_462_p1() {
    tmp_7_i_i_fu_462_p1 = esl_zext<100,4>(tmp_34_reg_1058.read());
}

void cordic_sincos_generi::thread_tmp_s_fu_390_p2() {
    tmp_s_fu_390_p2 = (!loc_V_fu_380_p4.read().is_01() || !ap_const_lv8_FF.is_01())? sc_lv<1>(): sc_lv<1>(loc_V_fu_380_p4.read() == ap_const_lv8_FF);
}

void cordic_sincos_generi::thread_tx_V_fu_786_p3() {
    tx_V_fu_786_p3 = (!d_V_fu_756_p3.read()[0].is_01())? sc_lv<43>(): ((d_V_fu_756_p3.read()[0].to_bool())? r_V_i2_fu_780_p2.read(): r_V_4_i_fu_774_p2.read());
}

void cordic_sincos_generi::thread_ty_V_fu_812_p3() {
    ty_V_fu_812_p3 = (!d_V_fu_756_p3.read()[0].is_01())? sc_lv<43>(): ((d_V_fu_756_p3.read()[0].to_bool())? r_V_1_i_fu_800_p2.read(): r_V_i7_fu_806_p2.read());
}

void cordic_sincos_generi::thread_tz_V_fu_880_p3() {
    tz_V_fu_880_p3 = (!d_V_reg_1112.read()[0].is_01())? sc_lv<43>(): ((d_V_reg_1112.read()[0].to_bool())? r_V_i_fu_874_p2.read(): r_V_5_i_fu_868_p2.read());
}

void cordic_sincos_generi::thread_val_assign_fu_589_p3() {
    val_assign_fu_589_p3 = esl_cttz<32,32>(p_Result_13_fu_581_p3.read());
}

void cordic_sincos_generi::thread_x_s_V_fu_794_p2() {
    x_s_V_fu_794_p2 = (!p_Val2_2_reg_231.read().is_01() || !tmp_38_fu_764_p1.read().is_01())? sc_lv<43>(): sc_bigint<43>(p_Val2_2_reg_231.read()) >> (unsigned short)tmp_38_fu_764_p1.read().to_uint();
}

void cordic_sincos_generi::thread_y_V_fu_707_p1() {
    y_V_fu_707_p1 = esl_zext<43,40>(tmp_14_fu_697_p4.read());
}

void cordic_sincos_generi::thread_y_s_V_fu_768_p2() {
    y_s_V_fu_768_p2 = (!p_Val2_1_reg_220.read().is_01() || !tmp_38_fu_764_p1.read().is_01())? sc_lv<43>(): sc_bigint<43>(p_Val2_1_reg_220.read()) >> (unsigned short)tmp_38_fu_764_p1.read().to_uint();
}

void cordic_sincos_generi::thread_yprescale_V_cast_fu_715_p2() {
    yprescale_V_cast_fu_715_p2 = (!ap_const_lv6_0.is_01() || !tmp_39_fu_711_p1.read().is_01())? sc_lv<6>(): (sc_biguint<6>(ap_const_lv6_0) - sc_biguint<6>(tmp_39_fu_711_p1.read()));
}

void cordic_sincos_generi::thread_z_V_fu_740_p1() {
    z_V_fu_740_p1 = esl_zext<43,40>(tmp_15_fu_730_p4.read());
}

void cordic_sincos_generi::thread_z_s_V_cast_fu_864_p1() {
    z_s_V_cast_fu_864_p1 = esl_zext<43,40>(z_s_V_fu_858_p2.read());
}

void cordic_sincos_generi::thread_z_s_V_fu_858_p2() {
    z_s_V_fu_858_p2 = (!tmp_46_cast_fu_854_p1.read().is_01() || !p_Val2_27_cast_fu_836_p4.read().is_01())? sc_lv<40>(): (sc_biguint<40>(tmp_46_cast_fu_854_p1.read()) + sc_biguint<40>(p_Val2_27_cast_fu_836_p4.read()));
}

void cordic_sincos_generi::thread_ap_NS_fsm() {
    switch (ap_CS_fsm.read().to_uint64()) {
        case 1 : 
            if ((esl_seteq<1,1,1>(tmp_36_fu_396_p2.read(), ap_const_lv1_0) && esl_seteq<1,1,1>(tmp_s_fu_390_p2.read(), ap_const_lv1_0) && esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
                ap_NS_fsm = ap_ST_fsm_state2;
            } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1) && (esl_seteq<1,1,1>(tmp_36_fu_396_p2.read(), ap_const_lv1_1) || 
  esl_seteq<1,1,1>(tmp_s_fu_390_p2.read(), ap_const_lv1_1)))) {
                ap_NS_fsm = ap_ST_fsm_state7;
            } else {
                ap_NS_fsm = ap_ST_fsm_state1;
            }
            break;
        case 2 : 
            ap_NS_fsm = ap_ST_fsm_state3;
            break;
        case 4 : 
            if ((esl_seteq<1,1,1>(tmp_37_fu_681_p2.read(), ap_const_lv1_1) && esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()))) {
                ap_NS_fsm = ap_ST_fsm_state5;
            } else {
                ap_NS_fsm = ap_ST_fsm_state4;
            }
            break;
        case 8 : 
            ap_NS_fsm = ap_ST_fsm_state5;
            break;
        case 16 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read()) && (esl_seteq<1,1,1>(exitcond_i_fu_744_p2.read(), ap_const_lv1_1) || 
  esl_seteq<1,1,1>(tmp_37_reg_1085.read(), ap_const_lv1_1)))) {
                ap_NS_fsm = ap_ST_fsm_state7;
            } else {
                ap_NS_fsm = ap_ST_fsm_state6;
            }
            break;
        case 32 : 
            ap_NS_fsm = ap_ST_fsm_state5;
            break;
        case 64 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read()) && esl_seteq<1,1,1>(ap_const_boolean_0, ap_block_state7_on_subcall_done.read()))) {
                ap_NS_fsm = ap_ST_fsm_state1;
            } else {
                ap_NS_fsm = ap_ST_fsm_state7;
            }
            break;
        default : 
            ap_NS_fsm = "XXXXXXX";
            break;
    }
}

}

