// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.1
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#include "scaled_fixed2ieee.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_logic scaled_fixed2ieee::ap_const_logic_1 = sc_dt::Log_1;
const sc_logic scaled_fixed2ieee::ap_const_logic_0 = sc_dt::Log_0;
const sc_lv<4> scaled_fixed2ieee::ap_ST_fsm_state1 = "1";
const sc_lv<4> scaled_fixed2ieee::ap_ST_fsm_state2 = "10";
const sc_lv<4> scaled_fixed2ieee::ap_ST_fsm_state3 = "100";
const sc_lv<4> scaled_fixed2ieee::ap_ST_fsm_state4 = "1000";
const sc_lv<32> scaled_fixed2ieee::ap_const_lv32_0 = "00000000000000000000000000000000";
const sc_lv<32> scaled_fixed2ieee::ap_const_lv32_1 = "1";
const sc_lv<1> scaled_fixed2ieee::ap_const_lv1_0 = "0";
const sc_lv<1> scaled_fixed2ieee::ap_const_lv1_1 = "1";
const sc_lv<32> scaled_fixed2ieee::ap_const_lv32_2 = "10";
const sc_lv<32> scaled_fixed2ieee::ap_const_lv32_3 = "11";
const sc_lv<2> scaled_fixed2ieee::ap_const_lv2_0 = "00";
const sc_lv<2> scaled_fixed2ieee::ap_const_lv2_1 = "1";
const sc_lv<32> scaled_fixed2ieee::ap_const_lv32_2A = "101010";
const sc_lv<43> scaled_fixed2ieee::ap_const_lv43_0 = "0000000000000000000000000000000000000000000";
const sc_lv<2> scaled_fixed2ieee::ap_const_lv2_2 = "10";
const sc_lv<4> scaled_fixed2ieee::ap_const_lv4_0 = "0000";
const sc_lv<6> scaled_fixed2ieee::ap_const_lv6_2A = "101010";
const sc_lv<5> scaled_fixed2ieee::ap_const_lv5_1B = "11011";
const sc_lv<43> scaled_fixed2ieee::ap_const_lv43_7FFFFFFFFFF = "1111111111111111111111111111111111111111111";
const sc_lv<32> scaled_fixed2ieee::ap_const_lv32_F = "1111";
const sc_lv<32> scaled_fixed2ieee::ap_const_lv32_1F = "11111";
const sc_lv<32> scaled_fixed2ieee::ap_const_lv32_14 = "10100";
const sc_lv<2> scaled_fixed2ieee::ap_const_lv2_3 = "11";
const sc_lv<32> scaled_fixed2ieee::ap_const_lv32_10 = "10000";
const sc_lv<8> scaled_fixed2ieee::ap_const_lv8_81 = "10000001";
const sc_lv<32> scaled_fixed2ieee::ap_const_lv32_13 = "10011";
const sc_lv<32> scaled_fixed2ieee::ap_const_lv32_29 = "101001";
const sc_lv<23> scaled_fixed2ieee::ap_const_lv23_0 = "00000000000000000000000";
const sc_lv<8> scaled_fixed2ieee::ap_const_lv8_0 = "00000000";
const bool scaled_fixed2ieee::ap_const_boolean_1 = true;

scaled_fixed2ieee::scaled_fixed2ieee(sc_module_name name) : sc_module(name), mVcdFile(0) {
    filter_mux_32_32_dEe_U48 = new filter_mux_32_32_dEe<1,1,32,32,32,2,32>("filter_mux_32_32_dEe_U48");
    filter_mux_32_32_dEe_U48->din0(out_bits_0_V_s_reg_124);
    filter_mux_32_32_dEe_U48->din1(out_bits_1_V_s_reg_112);
    filter_mux_32_32_dEe_U48->din2(p_Result_6_reg_737);
    filter_mux_32_32_dEe_U48->din3(i1_reg_147);
    filter_mux_32_32_dEe_U48->dout(p_Val2_4_fu_460_p5);
    filter_mux_32_32_dEe_U49 = new filter_mux_32_32_dEe<1,1,32,32,32,2,32>("filter_mux_32_32_dEe_U49");
    filter_mux_32_32_dEe_U49->din0(c_2_1_fu_92);
    filter_mux_32_32_dEe_U49->din1(c_2_2_fu_96);
    filter_mux_32_32_dEe_U49->din2(c_2_fu_88);
    filter_mux_32_32_dEe_U49->din3(i2_reg_178);
    filter_mux_32_32_dEe_U49->dout(sh_assign_fu_525_p5);

    SC_METHOD(thread_ap_clk_no_reset_);
    dont_initialize();
    sensitive << ( ap_clk.pos() );

    SC_METHOD(thread_Hi_assign_cast_fu_265_p1);
    sensitive << ( Hi_assign_fu_259_p2 );

    SC_METHOD(thread_Hi_assign_fu_259_p2);
    sensitive << ( tmp_5_cast_fu_255_p1 );

    SC_METHOD(thread_Lo_assign_cast_fu_275_p1);
    sensitive << ( Lo_assign_fu_269_p2 );

    SC_METHOD(thread_Lo_assign_fu_269_p2);
    sensitive << ( tmp_5_fu_247_p3 );

    SC_METHOD(thread_ap_CS_fsm_state1);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state2);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state3);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state4);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_done);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( tmp_8_fu_504_p2 );
    sensitive << ( tmp_1_fu_591_p2 );

    SC_METHOD(thread_ap_idle);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );

    SC_METHOD(thread_ap_phi_mux_i1_phi_fu_151_p4);
    sensitive << ( i1_reg_147 );

    SC_METHOD(thread_ap_phi_mux_p_Val2_s_phi_fu_192_p4);
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( tmp_8_fu_504_p2 );
    sensitive << ( in_shift_V_fu_582_p3 );
    sensitive << ( in_shift_reg_158 );
    sensitive << ( tmp_1_fu_591_p2 );

    SC_METHOD(thread_ap_phi_mux_shift_1_phi_fu_202_p4);
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( shift_2_fu_537_p2 );
    sensitive << ( tmp_8_fu_504_p2 );
    sensitive << ( tmp_1_fu_591_p2 );
    sensitive << ( shift_reg_167 );

    SC_METHOD(thread_ap_ready);
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( tmp_8_fu_504_p2 );
    sensitive << ( tmp_1_fu_591_p2 );

    SC_METHOD(thread_ap_return);
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( tmp_8_fu_504_p2 );
    sensitive << ( tmp_1_fu_591_p2 );
    sensitive << ( result_write_assign_fu_674_p1 );
    sensitive << ( ap_return_preg );

    SC_METHOD(thread_c_0_fu_481_p3);
    sensitive << ( p_Result_7_fu_471_p4 );

    SC_METHOD(thread_cond_fu_371_p2);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( exitcond1_fu_231_p2 );
    sensitive << ( i_reg_136 );

    SC_METHOD(thread_exitcond1_fu_231_p2);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( i_reg_136 );

    SC_METHOD(thread_exitcond_fu_448_p2);
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( i1_reg_147 );

    SC_METHOD(thread_i_1_fu_237_p2);
    sensitive << ( i_reg_136 );

    SC_METHOD(thread_i_2_fu_454_p2);
    sensitive << ( i1_reg_147 );

    SC_METHOD(thread_i_3_fu_510_p2);
    sensitive << ( i2_reg_178 );

    SC_METHOD(thread_in_shift_V_2_fu_223_p3);
    sensitive << ( in_V );
    sensitive << ( p_Result_s_fu_209_p3 );
    sensitive << ( p_Val2_2_fu_217_p2 );

    SC_METHOD(thread_in_shift_V_fu_582_p3);
    sensitive << ( isNeg_fu_544_p3 );
    sensitive << ( tmp_s_fu_576_p2 );
    sensitive << ( tmp_9_fu_570_p2 );

    SC_METHOD(thread_isNeg_fu_544_p3);
    sensitive << ( sh_assign_fu_525_p5 );

    SC_METHOD(thread_newexp_fu_610_p2);
    sensitive << ( ap_phi_mux_shift_1_phi_fu_202_p4 );
    sensitive << ( tmp_4_cast_fu_606_p1 );

    SC_METHOD(thread_or_cond_fu_629_p2);
    sensitive << ( tmp_30_fu_616_p3 );
    sensitive << ( tmp_7_fu_624_p2 );

    SC_METHOD(thread_out_bits_1_V_1_fu_409_p3);
    sensitive << ( out_bits_1_V_s_reg_112 );
    sensitive << ( cond_fu_371_p2 );
    sensitive << ( p_Result_5_fu_397_p5 );

    SC_METHOD(thread_out_bits_1_V_2_fu_417_p3);
    sensitive << ( out_bits_0_V_s_reg_124 );
    sensitive << ( cond_fu_371_p2 );
    sensitive << ( p_Result_5_fu_397_p5 );

    SC_METHOD(thread_out_exp_V_fu_657_p3);
    sensitive << ( or_cond_fu_629_p2 );
    sensitive << ( tmp_31_fu_635_p1 );

    SC_METHOD(thread_p_Result_4_fu_365_p2);
    sensitive << ( tmp_25_fu_353_p2 );
    sensitive << ( tmp_26_fu_359_p2 );

    SC_METHOD(thread_p_Result_5_fu_397_p5);
    sensitive << ( p_Val2_3_fu_377_p3 );
    sensitive << ( tmp_3_fu_389_p3 );

    SC_METHOD(thread_p_Result_6_fu_436_p5);
    sensitive << ( tmp_fu_428_p3 );

    SC_METHOD(thread_p_Result_7_fu_471_p4);
    sensitive << ( p_Val2_4_fu_460_p5 );

    SC_METHOD(thread_p_Result_8_fu_665_p4);
    sensitive << ( p_Result_s_reg_688 );
    sensitive << ( out_exp_V_fu_657_p3 );
    sensitive << ( p_Val2_5_fu_649_p3 );

    SC_METHOD(thread_p_Result_s_fu_209_p3);
    sensitive << ( in_V );

    SC_METHOD(thread_p_Val2_2_fu_217_p2);
    sensitive << ( in_V );

    SC_METHOD(thread_p_Val2_3_fu_377_p3);
    sensitive << ( out_bits_1_V_s_reg_112 );
    sensitive << ( out_bits_0_V_s_reg_124 );
    sensitive << ( cond_fu_371_p2 );

    SC_METHOD(thread_p_Val2_5_fu_649_p3);
    sensitive << ( or_cond_fu_629_p2 );
    sensitive << ( phitmp1_fu_639_p4 );

    SC_METHOD(thread_phitmp1_fu_639_p4);
    sensitive << ( ap_phi_mux_p_Val2_s_phi_fu_192_p4 );

    SC_METHOD(thread_prescale_cast_fu_597_p1);
    sensitive << ( prescale );

    SC_METHOD(thread_result_write_assign_fu_674_p1);
    sensitive << ( p_Result_8_fu_665_p4 );

    SC_METHOD(thread_sh_assign_1_fu_558_p3);
    sensitive << ( sh_assign_fu_525_p5 );
    sensitive << ( isNeg_fu_544_p3 );
    sensitive << ( tmp_2_fu_552_p2 );

    SC_METHOD(thread_shift_2_fu_537_p2);
    sensitive << ( shift_reg_167 );
    sensitive << ( sh_assign_fu_525_p5 );

    SC_METHOD(thread_tmp_11_fu_425_p1);
    sensitive << ( in_shift_V_2_reg_693 );

    SC_METHOD(thread_tmp_12_fu_243_p1);
    sensitive << ( i_reg_136 );

    SC_METHOD(thread_tmp_13_fu_279_p2);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( exitcond1_fu_231_p2 );
    sensitive << ( Lo_assign_cast_fu_275_p1 );
    sensitive << ( Hi_assign_cast_fu_265_p1 );

    SC_METHOD(thread_tmp_14_fu_285_p1);
    sensitive << ( Lo_assign_fu_269_p2 );

    SC_METHOD(thread_tmp_15_fu_289_p4);
    sensitive << ( in_shift_V_2_reg_693 );

    SC_METHOD(thread_tmp_16_fu_298_p2);
    sensitive << ( Hi_assign_fu_259_p2 );
    sensitive << ( tmp_14_fu_285_p1 );

    SC_METHOD(thread_tmp_17_fu_304_p2);
    sensitive << ( tmp_14_fu_285_p1 );

    SC_METHOD(thread_tmp_18_fu_310_p2);
    sensitive << ( Hi_assign_fu_259_p2 );
    sensitive << ( tmp_14_fu_285_p1 );

    SC_METHOD(thread_tmp_19_fu_316_p3);
    sensitive << ( tmp_13_fu_279_p2 );
    sensitive << ( tmp_16_fu_298_p2 );
    sensitive << ( tmp_18_fu_310_p2 );

    SC_METHOD(thread_tmp_1_fu_591_p2);
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( tmp_8_fu_504_p2 );
    sensitive << ( sh_assign_fu_525_p5 );

    SC_METHOD(thread_tmp_20_fu_324_p3);
    sensitive << ( in_shift_V_2_reg_693 );
    sensitive << ( tmp_13_fu_279_p2 );
    sensitive << ( tmp_15_fu_289_p4 );

    SC_METHOD(thread_tmp_21_fu_331_p3);
    sensitive << ( tmp_14_fu_285_p1 );
    sensitive << ( tmp_13_fu_279_p2 );
    sensitive << ( tmp_17_fu_304_p2 );

    SC_METHOD(thread_tmp_22_fu_339_p2);
    sensitive << ( tmp_19_fu_316_p3 );

    SC_METHOD(thread_tmp_23_fu_345_p1);
    sensitive << ( tmp_21_fu_331_p3 );

    SC_METHOD(thread_tmp_24_fu_349_p1);
    sensitive << ( tmp_22_fu_339_p2 );

    SC_METHOD(thread_tmp_25_fu_353_p2);
    sensitive << ( tmp_20_fu_324_p3 );
    sensitive << ( tmp_23_fu_345_p1 );

    SC_METHOD(thread_tmp_26_fu_359_p2);
    sensitive << ( tmp_24_fu_349_p1 );

    SC_METHOD(thread_tmp_28_fu_385_p1);
    sensitive << ( p_Result_4_fu_365_p2 );

    SC_METHOD(thread_tmp_2_fu_552_p2);
    sensitive << ( sh_assign_fu_525_p5 );

    SC_METHOD(thread_tmp_30_fu_616_p3);
    sensitive << ( newexp_fu_610_p2 );

    SC_METHOD(thread_tmp_31_fu_635_p1);
    sensitive << ( newexp_fu_610_p2 );

    SC_METHOD(thread_tmp_3_fu_389_p3);
    sensitive << ( tmp_28_fu_385_p1 );

    SC_METHOD(thread_tmp_4_cast_fu_606_p1);
    sensitive << ( tmp_4_fu_600_p2 );

    SC_METHOD(thread_tmp_4_fu_600_p2);
    sensitive << ( prescale_cast_fu_597_p1 );

    SC_METHOD(thread_tmp_5_cast_fu_255_p1);
    sensitive << ( tmp_5_fu_247_p3 );

    SC_METHOD(thread_tmp_5_fu_247_p3);
    sensitive << ( tmp_12_fu_243_p1 );

    SC_METHOD(thread_tmp_6_fu_566_p1);
    sensitive << ( sh_assign_1_fu_558_p3 );

    SC_METHOD(thread_tmp_7_fu_624_p2);
    sensitive << ( in_V );
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( tmp_8_fu_504_p2 );
    sensitive << ( tmp_1_fu_591_p2 );

    SC_METHOD(thread_tmp_8_fu_504_p2);
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( i2_reg_178 );

    SC_METHOD(thread_tmp_9_fu_570_p2);
    sensitive << ( in_shift_reg_158 );
    sensitive << ( tmp_6_fu_566_p1 );

    SC_METHOD(thread_tmp_fu_428_p3);
    sensitive << ( tmp_11_fu_425_p1 );

    SC_METHOD(thread_tmp_s_fu_576_p2);
    sensitive << ( in_shift_reg_158 );
    sensitive << ( tmp_6_fu_566_p1 );

    SC_METHOD(thread_ap_NS_fsm);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( exitcond1_fu_231_p2 );
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( tmp_8_fu_504_p2 );
    sensitive << ( exitcond_fu_448_p2 );
    sensitive << ( tmp_1_fu_591_p2 );

    ap_CS_fsm = "0001";
    ap_return_preg = "00000000000000000000000000000000";
    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "scaled_fixed2ieee_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT_HIER__
    sc_trace(mVcdFile, ap_clk, "(port)ap_clk");
    sc_trace(mVcdFile, ap_rst, "(port)ap_rst");
    sc_trace(mVcdFile, ap_start, "(port)ap_start");
    sc_trace(mVcdFile, ap_done, "(port)ap_done");
    sc_trace(mVcdFile, ap_idle, "(port)ap_idle");
    sc_trace(mVcdFile, ap_ready, "(port)ap_ready");
    sc_trace(mVcdFile, in_V, "(port)in_V");
    sc_trace(mVcdFile, prescale, "(port)prescale");
    sc_trace(mVcdFile, ap_return, "(port)ap_return");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, ap_CS_fsm, "ap_CS_fsm");
    sc_trace(mVcdFile, ap_CS_fsm_state1, "ap_CS_fsm_state1");
    sc_trace(mVcdFile, p_Result_s_fu_209_p3, "p_Result_s_fu_209_p3");
    sc_trace(mVcdFile, p_Result_s_reg_688, "p_Result_s_reg_688");
    sc_trace(mVcdFile, in_shift_V_2_fu_223_p3, "in_shift_V_2_fu_223_p3");
    sc_trace(mVcdFile, in_shift_V_2_reg_693, "in_shift_V_2_reg_693");
    sc_trace(mVcdFile, i_1_fu_237_p2, "i_1_fu_237_p2");
    sc_trace(mVcdFile, ap_CS_fsm_state2, "ap_CS_fsm_state2");
    sc_trace(mVcdFile, out_bits_1_V_1_fu_409_p3, "out_bits_1_V_1_fu_409_p3");
    sc_trace(mVcdFile, exitcond1_fu_231_p2, "exitcond1_fu_231_p2");
    sc_trace(mVcdFile, out_bits_1_V_2_fu_417_p3, "out_bits_1_V_2_fu_417_p3");
    sc_trace(mVcdFile, p_Result_6_fu_436_p5, "p_Result_6_fu_436_p5");
    sc_trace(mVcdFile, p_Result_6_reg_737, "p_Result_6_reg_737");
    sc_trace(mVcdFile, i_2_fu_454_p2, "i_2_fu_454_p2");
    sc_trace(mVcdFile, ap_CS_fsm_state3, "ap_CS_fsm_state3");
    sc_trace(mVcdFile, i_3_fu_510_p2, "i_3_fu_510_p2");
    sc_trace(mVcdFile, ap_CS_fsm_state4, "ap_CS_fsm_state4");
    sc_trace(mVcdFile, shift_2_fu_537_p2, "shift_2_fu_537_p2");
    sc_trace(mVcdFile, tmp_8_fu_504_p2, "tmp_8_fu_504_p2");
    sc_trace(mVcdFile, in_shift_V_fu_582_p3, "in_shift_V_fu_582_p3");
    sc_trace(mVcdFile, out_bits_1_V_s_reg_112, "out_bits_1_V_s_reg_112");
    sc_trace(mVcdFile, out_bits_0_V_s_reg_124, "out_bits_0_V_s_reg_124");
    sc_trace(mVcdFile, i_reg_136, "i_reg_136");
    sc_trace(mVcdFile, ap_phi_mux_i1_phi_fu_151_p4, "ap_phi_mux_i1_phi_fu_151_p4");
    sc_trace(mVcdFile, i1_reg_147, "i1_reg_147");
    sc_trace(mVcdFile, exitcond_fu_448_p2, "exitcond_fu_448_p2");
    sc_trace(mVcdFile, in_shift_reg_158, "in_shift_reg_158");
    sc_trace(mVcdFile, tmp_1_fu_591_p2, "tmp_1_fu_591_p2");
    sc_trace(mVcdFile, shift_reg_167, "shift_reg_167");
    sc_trace(mVcdFile, i2_reg_178, "i2_reg_178");
    sc_trace(mVcdFile, ap_phi_mux_p_Val2_s_phi_fu_192_p4, "ap_phi_mux_p_Val2_s_phi_fu_192_p4");
    sc_trace(mVcdFile, ap_phi_mux_shift_1_phi_fu_202_p4, "ap_phi_mux_shift_1_phi_fu_202_p4");
    sc_trace(mVcdFile, c_2_fu_88, "c_2_fu_88");
    sc_trace(mVcdFile, c_0_fu_481_p3, "c_0_fu_481_p3");
    sc_trace(mVcdFile, c_2_1_fu_92, "c_2_1_fu_92");
    sc_trace(mVcdFile, c_2_2_fu_96, "c_2_2_fu_96");
    sc_trace(mVcdFile, p_Val2_2_fu_217_p2, "p_Val2_2_fu_217_p2");
    sc_trace(mVcdFile, tmp_12_fu_243_p1, "tmp_12_fu_243_p1");
    sc_trace(mVcdFile, tmp_5_fu_247_p3, "tmp_5_fu_247_p3");
    sc_trace(mVcdFile, tmp_5_cast_fu_255_p1, "tmp_5_cast_fu_255_p1");
    sc_trace(mVcdFile, Hi_assign_fu_259_p2, "Hi_assign_fu_259_p2");
    sc_trace(mVcdFile, Lo_assign_fu_269_p2, "Lo_assign_fu_269_p2");
    sc_trace(mVcdFile, Lo_assign_cast_fu_275_p1, "Lo_assign_cast_fu_275_p1");
    sc_trace(mVcdFile, Hi_assign_cast_fu_265_p1, "Hi_assign_cast_fu_265_p1");
    sc_trace(mVcdFile, tmp_14_fu_285_p1, "tmp_14_fu_285_p1");
    sc_trace(mVcdFile, tmp_13_fu_279_p2, "tmp_13_fu_279_p2");
    sc_trace(mVcdFile, tmp_16_fu_298_p2, "tmp_16_fu_298_p2");
    sc_trace(mVcdFile, tmp_18_fu_310_p2, "tmp_18_fu_310_p2");
    sc_trace(mVcdFile, tmp_15_fu_289_p4, "tmp_15_fu_289_p4");
    sc_trace(mVcdFile, tmp_17_fu_304_p2, "tmp_17_fu_304_p2");
    sc_trace(mVcdFile, tmp_19_fu_316_p3, "tmp_19_fu_316_p3");
    sc_trace(mVcdFile, tmp_21_fu_331_p3, "tmp_21_fu_331_p3");
    sc_trace(mVcdFile, tmp_22_fu_339_p2, "tmp_22_fu_339_p2");
    sc_trace(mVcdFile, tmp_20_fu_324_p3, "tmp_20_fu_324_p3");
    sc_trace(mVcdFile, tmp_23_fu_345_p1, "tmp_23_fu_345_p1");
    sc_trace(mVcdFile, tmp_24_fu_349_p1, "tmp_24_fu_349_p1");
    sc_trace(mVcdFile, tmp_25_fu_353_p2, "tmp_25_fu_353_p2");
    sc_trace(mVcdFile, tmp_26_fu_359_p2, "tmp_26_fu_359_p2");
    sc_trace(mVcdFile, cond_fu_371_p2, "cond_fu_371_p2");
    sc_trace(mVcdFile, p_Result_4_fu_365_p2, "p_Result_4_fu_365_p2");
    sc_trace(mVcdFile, tmp_28_fu_385_p1, "tmp_28_fu_385_p1");
    sc_trace(mVcdFile, p_Val2_3_fu_377_p3, "p_Val2_3_fu_377_p3");
    sc_trace(mVcdFile, tmp_3_fu_389_p3, "tmp_3_fu_389_p3");
    sc_trace(mVcdFile, p_Result_5_fu_397_p5, "p_Result_5_fu_397_p5");
    sc_trace(mVcdFile, tmp_11_fu_425_p1, "tmp_11_fu_425_p1");
    sc_trace(mVcdFile, tmp_fu_428_p3, "tmp_fu_428_p3");
    sc_trace(mVcdFile, p_Val2_4_fu_460_p5, "p_Val2_4_fu_460_p5");
    sc_trace(mVcdFile, p_Result_7_fu_471_p4, "p_Result_7_fu_471_p4");
    sc_trace(mVcdFile, sh_assign_fu_525_p5, "sh_assign_fu_525_p5");
    sc_trace(mVcdFile, isNeg_fu_544_p3, "isNeg_fu_544_p3");
    sc_trace(mVcdFile, tmp_2_fu_552_p2, "tmp_2_fu_552_p2");
    sc_trace(mVcdFile, sh_assign_1_fu_558_p3, "sh_assign_1_fu_558_p3");
    sc_trace(mVcdFile, tmp_6_fu_566_p1, "tmp_6_fu_566_p1");
    sc_trace(mVcdFile, tmp_s_fu_576_p2, "tmp_s_fu_576_p2");
    sc_trace(mVcdFile, tmp_9_fu_570_p2, "tmp_9_fu_570_p2");
    sc_trace(mVcdFile, prescale_cast_fu_597_p1, "prescale_cast_fu_597_p1");
    sc_trace(mVcdFile, tmp_4_fu_600_p2, "tmp_4_fu_600_p2");
    sc_trace(mVcdFile, tmp_4_cast_fu_606_p1, "tmp_4_cast_fu_606_p1");
    sc_trace(mVcdFile, newexp_fu_610_p2, "newexp_fu_610_p2");
    sc_trace(mVcdFile, tmp_30_fu_616_p3, "tmp_30_fu_616_p3");
    sc_trace(mVcdFile, tmp_7_fu_624_p2, "tmp_7_fu_624_p2");
    sc_trace(mVcdFile, or_cond_fu_629_p2, "or_cond_fu_629_p2");
    sc_trace(mVcdFile, phitmp1_fu_639_p4, "phitmp1_fu_639_p4");
    sc_trace(mVcdFile, tmp_31_fu_635_p1, "tmp_31_fu_635_p1");
    sc_trace(mVcdFile, out_exp_V_fu_657_p3, "out_exp_V_fu_657_p3");
    sc_trace(mVcdFile, p_Val2_5_fu_649_p3, "p_Val2_5_fu_649_p3");
    sc_trace(mVcdFile, p_Result_8_fu_665_p4, "p_Result_8_fu_665_p4");
    sc_trace(mVcdFile, result_write_assign_fu_674_p1, "result_write_assign_fu_674_p1");
    sc_trace(mVcdFile, ap_return_preg, "ap_return_preg");
    sc_trace(mVcdFile, ap_NS_fsm, "ap_NS_fsm");
#endif

    }
}

scaled_fixed2ieee::~scaled_fixed2ieee() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

    delete filter_mux_32_32_dEe_U48;
    delete filter_mux_32_32_dEe_U49;
}

void scaled_fixed2ieee::thread_ap_clk_no_reset_() {
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_CS_fsm = ap_ST_fsm_state1;
    } else {
        ap_CS_fsm = ap_NS_fsm.read();
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_return_preg = ap_const_lv32_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) && 
             (esl_seteq<1,1,1>(tmp_8_fu_504_p2.read(), ap_const_lv1_1) || 
              esl_seteq<1,1,1>(tmp_1_fu_591_p2.read(), ap_const_lv1_0)))) {
            ap_return_preg = result_write_assign_fu_674_p1.read();
        }
    }
    if ((esl_seteq<1,1,1>(exitcond_fu_448_p2.read(), ap_const_lv1_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()))) {
        i1_reg_147 = i_2_fu_454_p2.read();
    } else if ((esl_seteq<1,1,1>(exitcond1_fu_231_p2.read(), ap_const_lv1_1) && 
                esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()))) {
        i1_reg_147 = ap_const_lv2_0;
    }
    if ((esl_seteq<1,1,1>(exitcond_fu_448_p2.read(), ap_const_lv1_1) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()))) {
        i2_reg_178 = ap_const_lv2_0;
    } else if ((esl_seteq<1,1,1>(tmp_1_fu_591_p2.read(), ap_const_lv1_1) && 
                esl_seteq<1,1,1>(tmp_8_fu_504_p2.read(), ap_const_lv1_0) && 
                esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()))) {
        i2_reg_178 = i_3_fu_510_p2.read();
    }
    if ((esl_seteq<1,1,1>(exitcond1_fu_231_p2.read(), ap_const_lv1_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()))) {
        i_reg_136 = i_1_fu_237_p2.read();
    } else if ((esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1) && 
                esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()))) {
        i_reg_136 = ap_const_lv2_0;
    }
    if ((esl_seteq<1,1,1>(exitcond_fu_448_p2.read(), ap_const_lv1_1) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()))) {
        in_shift_reg_158 = in_shift_V_2_reg_693.read();
    } else if ((esl_seteq<1,1,1>(tmp_1_fu_591_p2.read(), ap_const_lv1_1) && 
                esl_seteq<1,1,1>(tmp_8_fu_504_p2.read(), ap_const_lv1_0) && 
                esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()))) {
        in_shift_reg_158 = in_shift_V_fu_582_p3.read();
    }
    if ((esl_seteq<1,1,1>(exitcond_fu_448_p2.read(), ap_const_lv1_1) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()))) {
        shift_reg_167 = ap_const_lv32_0;
    } else if ((esl_seteq<1,1,1>(tmp_1_fu_591_p2.read(), ap_const_lv1_1) && 
                esl_seteq<1,1,1>(tmp_8_fu_504_p2.read(), ap_const_lv1_0) && 
                esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()))) {
        shift_reg_167 = shift_2_fu_537_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && esl_seteq<1,1,1>(exitcond_fu_448_p2.read(), ap_const_lv1_0) && esl_seteq<1,2,2>(ap_const_lv2_0, ap_phi_mux_i1_phi_fu_151_p4.read()))) {
        c_2_1_fu_92 = c_0_fu_481_p3.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && esl_seteq<1,1,1>(exitcond_fu_448_p2.read(), ap_const_lv1_0) && esl_seteq<1,2,2>(ap_phi_mux_i1_phi_fu_151_p4.read(), ap_const_lv2_1))) {
        c_2_2_fu_96 = c_0_fu_481_p3.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && esl_seteq<1,1,1>(exitcond_fu_448_p2.read(), ap_const_lv1_0) && !esl_seteq<1,2,2>(ap_const_lv2_0, ap_phi_mux_i1_phi_fu_151_p4.read()) && !esl_seteq<1,2,2>(ap_phi_mux_i1_phi_fu_151_p4.read(), ap_const_lv2_1))) {
        c_2_fu_88 = c_0_fu_481_p3.read();
    }
    if ((esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1) && esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()))) {
        in_shift_V_2_reg_693 = in_shift_V_2_fu_223_p3.read();
        p_Result_s_reg_688 = in_V.read().range(42, 42);
    }
    if ((esl_seteq<1,1,1>(exitcond1_fu_231_p2.read(), ap_const_lv1_0) && esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()))) {
        out_bits_0_V_s_reg_124 = out_bits_1_V_2_fu_417_p3.read();
        out_bits_1_V_s_reg_112 = out_bits_1_V_1_fu_409_p3.read();
    }
    if ((esl_seteq<1,1,1>(exitcond1_fu_231_p2.read(), ap_const_lv1_1) && esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()))) {
        p_Result_6_reg_737 = p_Result_6_fu_436_p5.read();
    }
}

void scaled_fixed2ieee::thread_Hi_assign_cast_fu_265_p1() {
    Hi_assign_cast_fu_265_p1 = esl_zext<32,6>(Hi_assign_fu_259_p2.read());
}

void scaled_fixed2ieee::thread_Hi_assign_fu_259_p2() {
    Hi_assign_fu_259_p2 = (!ap_const_lv6_2A.is_01() || !tmp_5_cast_fu_255_p1.read().is_01())? sc_lv<6>(): (sc_bigint<6>(ap_const_lv6_2A) - sc_biguint<6>(tmp_5_cast_fu_255_p1.read()));
}

void scaled_fixed2ieee::thread_Lo_assign_cast_fu_275_p1() {
    Lo_assign_cast_fu_275_p1 = esl_zext<32,5>(Lo_assign_fu_269_p2.read());
}

void scaled_fixed2ieee::thread_Lo_assign_fu_269_p2() {
    Lo_assign_fu_269_p2 = (!ap_const_lv5_1B.is_01() || !tmp_5_fu_247_p3.read().is_01())? sc_lv<5>(): (sc_bigint<5>(ap_const_lv5_1B) - sc_biguint<5>(tmp_5_fu_247_p3.read()));
}

void scaled_fixed2ieee::thread_ap_CS_fsm_state1() {
    ap_CS_fsm_state1 = ap_CS_fsm.read()[0];
}

void scaled_fixed2ieee::thread_ap_CS_fsm_state2() {
    ap_CS_fsm_state2 = ap_CS_fsm.read()[1];
}

void scaled_fixed2ieee::thread_ap_CS_fsm_state3() {
    ap_CS_fsm_state3 = ap_CS_fsm.read()[2];
}

void scaled_fixed2ieee::thread_ap_CS_fsm_state4() {
    ap_CS_fsm_state4 = ap_CS_fsm.read()[3];
}

void scaled_fixed2ieee::thread_ap_done() {
    if (((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read())) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) && 
          (esl_seteq<1,1,1>(tmp_8_fu_504_p2.read(), ap_const_lv1_1) || 
           esl_seteq<1,1,1>(tmp_1_fu_591_p2.read(), ap_const_lv1_0))))) {
        ap_done = ap_const_logic_1;
    } else {
        ap_done = ap_const_logic_0;
    }
}

void scaled_fixed2ieee::thread_ap_idle() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()))) {
        ap_idle = ap_const_logic_1;
    } else {
        ap_idle = ap_const_logic_0;
    }
}

void scaled_fixed2ieee::thread_ap_phi_mux_i1_phi_fu_151_p4() {
    ap_phi_mux_i1_phi_fu_151_p4 = i1_reg_147.read();
}

void scaled_fixed2ieee::thread_ap_phi_mux_p_Val2_s_phi_fu_192_p4() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read())) {
        if ((esl_seteq<1,1,1>(tmp_8_fu_504_p2.read(), ap_const_lv1_0) && 
             esl_seteq<1,1,1>(tmp_1_fu_591_p2.read(), ap_const_lv1_0))) {
            ap_phi_mux_p_Val2_s_phi_fu_192_p4 = in_shift_V_fu_582_p3.read();
        } else if (esl_seteq<1,1,1>(tmp_8_fu_504_p2.read(), ap_const_lv1_1)) {
            ap_phi_mux_p_Val2_s_phi_fu_192_p4 = in_shift_reg_158.read();
        } else {
            ap_phi_mux_p_Val2_s_phi_fu_192_p4 = "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        }
    } else {
        ap_phi_mux_p_Val2_s_phi_fu_192_p4 = "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
    }
}

void scaled_fixed2ieee::thread_ap_phi_mux_shift_1_phi_fu_202_p4() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read())) {
        if ((esl_seteq<1,1,1>(tmp_8_fu_504_p2.read(), ap_const_lv1_0) && 
             esl_seteq<1,1,1>(tmp_1_fu_591_p2.read(), ap_const_lv1_0))) {
            ap_phi_mux_shift_1_phi_fu_202_p4 = shift_2_fu_537_p2.read();
        } else if (esl_seteq<1,1,1>(tmp_8_fu_504_p2.read(), ap_const_lv1_1)) {
            ap_phi_mux_shift_1_phi_fu_202_p4 = shift_reg_167.read();
        } else {
            ap_phi_mux_shift_1_phi_fu_202_p4 =  (sc_lv<32>) ("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX");
        }
    } else {
        ap_phi_mux_shift_1_phi_fu_202_p4 =  (sc_lv<32>) ("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX");
    }
}

void scaled_fixed2ieee::thread_ap_ready() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) && 
         (esl_seteq<1,1,1>(tmp_8_fu_504_p2.read(), ap_const_lv1_1) || 
          esl_seteq<1,1,1>(tmp_1_fu_591_p2.read(), ap_const_lv1_0)))) {
        ap_ready = ap_const_logic_1;
    } else {
        ap_ready = ap_const_logic_0;
    }
}

void scaled_fixed2ieee::thread_ap_return() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) && 
         (esl_seteq<1,1,1>(tmp_8_fu_504_p2.read(), ap_const_lv1_1) || 
          esl_seteq<1,1,1>(tmp_1_fu_591_p2.read(), ap_const_lv1_0)))) {
        ap_return = result_write_assign_fu_674_p1.read();
    } else {
        ap_return = ap_return_preg.read();
    }
}

void scaled_fixed2ieee::thread_c_0_fu_481_p3() {
    c_0_fu_481_p3 = esl_cttz<32,32>(p_Result_7_fu_471_p4.read());
}

void scaled_fixed2ieee::thread_cond_fu_371_p2() {
    cond_fu_371_p2 = (!i_reg_136.read().is_01() || !ap_const_lv2_0.is_01())? sc_lv<1>(): sc_lv<1>(i_reg_136.read() == ap_const_lv2_0);
}

void scaled_fixed2ieee::thread_exitcond1_fu_231_p2() {
    exitcond1_fu_231_p2 = (!i_reg_136.read().is_01() || !ap_const_lv2_2.is_01())? sc_lv<1>(): sc_lv<1>(i_reg_136.read() == ap_const_lv2_2);
}

void scaled_fixed2ieee::thread_exitcond_fu_448_p2() {
    exitcond_fu_448_p2 = (!i1_reg_147.read().is_01() || !ap_const_lv2_3.is_01())? sc_lv<1>(): sc_lv<1>(i1_reg_147.read() == ap_const_lv2_3);
}

void scaled_fixed2ieee::thread_i_1_fu_237_p2() {
    i_1_fu_237_p2 = (!i_reg_136.read().is_01() || !ap_const_lv2_1.is_01())? sc_lv<2>(): (sc_biguint<2>(i_reg_136.read()) + sc_biguint<2>(ap_const_lv2_1));
}

void scaled_fixed2ieee::thread_i_2_fu_454_p2() {
    i_2_fu_454_p2 = (!i1_reg_147.read().is_01() || !ap_const_lv2_1.is_01())? sc_lv<2>(): (sc_biguint<2>(i1_reg_147.read()) + sc_biguint<2>(ap_const_lv2_1));
}

void scaled_fixed2ieee::thread_i_3_fu_510_p2() {
    i_3_fu_510_p2 = (!i2_reg_178.read().is_01() || !ap_const_lv2_1.is_01())? sc_lv<2>(): (sc_biguint<2>(i2_reg_178.read()) + sc_biguint<2>(ap_const_lv2_1));
}

void scaled_fixed2ieee::thread_in_shift_V_2_fu_223_p3() {
    in_shift_V_2_fu_223_p3 = (!p_Result_s_fu_209_p3.read()[0].is_01())? sc_lv<43>(): ((p_Result_s_fu_209_p3.read()[0].to_bool())? p_Val2_2_fu_217_p2.read(): in_V.read());
}

void scaled_fixed2ieee::thread_in_shift_V_fu_582_p3() {
    in_shift_V_fu_582_p3 = (!isNeg_fu_544_p3.read()[0].is_01())? sc_lv<43>(): ((isNeg_fu_544_p3.read()[0].to_bool())? tmp_s_fu_576_p2.read(): tmp_9_fu_570_p2.read());
}

void scaled_fixed2ieee::thread_isNeg_fu_544_p3() {
    isNeg_fu_544_p3 = sh_assign_fu_525_p5.read().range(31, 31);
}

void scaled_fixed2ieee::thread_newexp_fu_610_p2() {
    newexp_fu_610_p2 = (!tmp_4_cast_fu_606_p1.read().is_01() || !ap_phi_mux_shift_1_phi_fu_202_p4.read().is_01())? sc_lv<32>(): (sc_biguint<32>(tmp_4_cast_fu_606_p1.read()) - sc_biguint<32>(ap_phi_mux_shift_1_phi_fu_202_p4.read()));
}

void scaled_fixed2ieee::thread_or_cond_fu_629_p2() {
    or_cond_fu_629_p2 = (tmp_30_fu_616_p3.read() | tmp_7_fu_624_p2.read());
}

void scaled_fixed2ieee::thread_out_bits_1_V_1_fu_409_p3() {
    out_bits_1_V_1_fu_409_p3 = (!cond_fu_371_p2.read()[0].is_01())? sc_lv<32>(): ((cond_fu_371_p2.read()[0].to_bool())? out_bits_1_V_s_reg_112.read(): p_Result_5_fu_397_p5.read());
}

void scaled_fixed2ieee::thread_out_bits_1_V_2_fu_417_p3() {
    out_bits_1_V_2_fu_417_p3 = (!cond_fu_371_p2.read()[0].is_01())? sc_lv<32>(): ((cond_fu_371_p2.read()[0].to_bool())? p_Result_5_fu_397_p5.read(): out_bits_0_V_s_reg_124.read());
}

void scaled_fixed2ieee::thread_out_exp_V_fu_657_p3() {
    out_exp_V_fu_657_p3 = (!or_cond_fu_629_p2.read()[0].is_01())? sc_lv<8>(): ((or_cond_fu_629_p2.read()[0].to_bool())? ap_const_lv8_0: tmp_31_fu_635_p1.read());
}

void scaled_fixed2ieee::thread_p_Result_4_fu_365_p2() {
    p_Result_4_fu_365_p2 = (tmp_25_fu_353_p2.read() & tmp_26_fu_359_p2.read());
}

void scaled_fixed2ieee::thread_p_Result_5_fu_397_p5() {
    p_Result_5_fu_397_p5 = esl_partset<32,32,17,32,32>(p_Val2_3_fu_377_p3.read(), tmp_3_fu_389_p3.read(), ap_const_lv32_F, ap_const_lv32_1F);
}

void scaled_fixed2ieee::thread_p_Result_6_fu_436_p5() {
    p_Result_6_fu_436_p5 = esl_partset<32,32,12,32,32>(ap_const_lv32_0, tmp_fu_428_p3.read(), ap_const_lv32_14, ap_const_lv32_1F);
}

void scaled_fixed2ieee::thread_p_Result_7_fu_471_p4() {
    p_Result_7_fu_471_p4 = p_Val2_4_fu_460_p5.read().range(0, 31);
}

void scaled_fixed2ieee::thread_p_Result_8_fu_665_p4() {
    p_Result_8_fu_665_p4 = esl_concat<9,23>(esl_concat<1,8>(p_Result_s_reg_688.read(), out_exp_V_fu_657_p3.read()), p_Val2_5_fu_649_p3.read());
}

void scaled_fixed2ieee::thread_p_Result_s_fu_209_p3() {
    p_Result_s_fu_209_p3 = in_V.read().range(42, 42);
}

void scaled_fixed2ieee::thread_p_Val2_2_fu_217_p2() {
    p_Val2_2_fu_217_p2 = (!ap_const_lv43_0.is_01() || !in_V.read().is_01())? sc_lv<43>(): (sc_biguint<43>(ap_const_lv43_0) - sc_biguint<43>(in_V.read()));
}

void scaled_fixed2ieee::thread_p_Val2_3_fu_377_p3() {
    p_Val2_3_fu_377_p3 = (!cond_fu_371_p2.read()[0].is_01())? sc_lv<32>(): ((cond_fu_371_p2.read()[0].to_bool())? out_bits_0_V_s_reg_124.read(): out_bits_1_V_s_reg_112.read());
}

void scaled_fixed2ieee::thread_p_Val2_5_fu_649_p3() {
    p_Val2_5_fu_649_p3 = (!or_cond_fu_629_p2.read()[0].is_01())? sc_lv<23>(): ((or_cond_fu_629_p2.read()[0].to_bool())? ap_const_lv23_0: phitmp1_fu_639_p4.read());
}

void scaled_fixed2ieee::thread_phitmp1_fu_639_p4() {
    phitmp1_fu_639_p4 = ap_phi_mux_p_Val2_s_phi_fu_192_p4.read().range(41, 19);
}

void scaled_fixed2ieee::thread_prescale_cast_fu_597_p1() {
    prescale_cast_fu_597_p1 = esl_zext<8,6>(prescale.read());
}

void scaled_fixed2ieee::thread_result_write_assign_fu_674_p1() {
    result_write_assign_fu_674_p1 = p_Result_8_fu_665_p4.read();
}

void scaled_fixed2ieee::thread_sh_assign_1_fu_558_p3() {
    sh_assign_1_fu_558_p3 = (!isNeg_fu_544_p3.read()[0].is_01())? sc_lv<32>(): ((isNeg_fu_544_p3.read()[0].to_bool())? tmp_2_fu_552_p2.read(): sh_assign_fu_525_p5.read());
}

void scaled_fixed2ieee::thread_shift_2_fu_537_p2() {
    shift_2_fu_537_p2 = (!sh_assign_fu_525_p5.read().is_01() || !shift_reg_167.read().is_01())? sc_lv<32>(): (sc_biguint<32>(sh_assign_fu_525_p5.read()) + sc_biguint<32>(shift_reg_167.read()));
}

void scaled_fixed2ieee::thread_tmp_11_fu_425_p1() {
    tmp_11_fu_425_p1 = in_shift_V_2_reg_693.read().range(11-1, 0);
}

void scaled_fixed2ieee::thread_tmp_12_fu_243_p1() {
    tmp_12_fu_243_p1 = i_reg_136.read().range(1-1, 0);
}

void scaled_fixed2ieee::thread_tmp_13_fu_279_p2() {
    tmp_13_fu_279_p2 = (!Lo_assign_cast_fu_275_p1.read().is_01() || !Hi_assign_cast_fu_265_p1.read().is_01())? sc_lv<1>(): (sc_biguint<32>(Lo_assign_cast_fu_275_p1.read()) > sc_biguint<32>(Hi_assign_cast_fu_265_p1.read()));
}

void scaled_fixed2ieee::thread_tmp_14_fu_285_p1() {
    tmp_14_fu_285_p1 = esl_zext<6,5>(Lo_assign_fu_269_p2.read());
}

void scaled_fixed2ieee::thread_tmp_15_fu_289_p4() {
    tmp_15_fu_289_p4 = in_shift_V_2_reg_693.read().range(0, 42);
}

void scaled_fixed2ieee::thread_tmp_16_fu_298_p2() {
    tmp_16_fu_298_p2 = (!tmp_14_fu_285_p1.read().is_01() || !Hi_assign_fu_259_p2.read().is_01())? sc_lv<6>(): (sc_biguint<6>(tmp_14_fu_285_p1.read()) - sc_biguint<6>(Hi_assign_fu_259_p2.read()));
}

void scaled_fixed2ieee::thread_tmp_17_fu_304_p2() {
    tmp_17_fu_304_p2 = (!ap_const_lv6_2A.is_01() || !tmp_14_fu_285_p1.read().is_01())? sc_lv<6>(): (sc_bigint<6>(ap_const_lv6_2A) - sc_biguint<6>(tmp_14_fu_285_p1.read()));
}

void scaled_fixed2ieee::thread_tmp_18_fu_310_p2() {
    tmp_18_fu_310_p2 = (!Hi_assign_fu_259_p2.read().is_01() || !tmp_14_fu_285_p1.read().is_01())? sc_lv<6>(): (sc_biguint<6>(Hi_assign_fu_259_p2.read()) - sc_biguint<6>(tmp_14_fu_285_p1.read()));
}

void scaled_fixed2ieee::thread_tmp_19_fu_316_p3() {
    tmp_19_fu_316_p3 = (!tmp_13_fu_279_p2.read()[0].is_01())? sc_lv<6>(): ((tmp_13_fu_279_p2.read()[0].to_bool())? tmp_16_fu_298_p2.read(): tmp_18_fu_310_p2.read());
}

void scaled_fixed2ieee::thread_tmp_1_fu_591_p2() {
    tmp_1_fu_591_p2 = (!sh_assign_fu_525_p5.read().is_01() || !ap_const_lv32_10.is_01())? sc_lv<1>(): sc_lv<1>(sh_assign_fu_525_p5.read() == ap_const_lv32_10);
}

void scaled_fixed2ieee::thread_tmp_20_fu_324_p3() {
    tmp_20_fu_324_p3 = (!tmp_13_fu_279_p2.read()[0].is_01())? sc_lv<43>(): ((tmp_13_fu_279_p2.read()[0].to_bool())? tmp_15_fu_289_p4.read(): in_shift_V_2_reg_693.read());
}

void scaled_fixed2ieee::thread_tmp_21_fu_331_p3() {
    tmp_21_fu_331_p3 = (!tmp_13_fu_279_p2.read()[0].is_01())? sc_lv<6>(): ((tmp_13_fu_279_p2.read()[0].to_bool())? tmp_17_fu_304_p2.read(): tmp_14_fu_285_p1.read());
}

void scaled_fixed2ieee::thread_tmp_22_fu_339_p2() {
    tmp_22_fu_339_p2 = (!ap_const_lv6_2A.is_01() || !tmp_19_fu_316_p3.read().is_01())? sc_lv<6>(): (sc_bigint<6>(ap_const_lv6_2A) - sc_biguint<6>(tmp_19_fu_316_p3.read()));
}

void scaled_fixed2ieee::thread_tmp_23_fu_345_p1() {
    tmp_23_fu_345_p1 = esl_zext<43,6>(tmp_21_fu_331_p3.read());
}

void scaled_fixed2ieee::thread_tmp_24_fu_349_p1() {
    tmp_24_fu_349_p1 = esl_zext<43,6>(tmp_22_fu_339_p2.read());
}

void scaled_fixed2ieee::thread_tmp_25_fu_353_p2() {
    tmp_25_fu_353_p2 = (!tmp_23_fu_345_p1.read().is_01())? sc_lv<43>(): tmp_20_fu_324_p3.read() >> (unsigned short)tmp_23_fu_345_p1.read().to_uint();
}

void scaled_fixed2ieee::thread_tmp_26_fu_359_p2() {
    tmp_26_fu_359_p2 = (!tmp_24_fu_349_p1.read().is_01())? sc_lv<43>(): ap_const_lv43_7FFFFFFFFFF >> (unsigned short)tmp_24_fu_349_p1.read().to_uint();
}

void scaled_fixed2ieee::thread_tmp_28_fu_385_p1() {
    tmp_28_fu_385_p1 = p_Result_4_fu_365_p2.read().range(16-1, 0);
}

void scaled_fixed2ieee::thread_tmp_2_fu_552_p2() {
    tmp_2_fu_552_p2 = (!ap_const_lv32_0.is_01() || !sh_assign_fu_525_p5.read().is_01())? sc_lv<32>(): (sc_biguint<32>(ap_const_lv32_0) - sc_biguint<32>(sh_assign_fu_525_p5.read()));
}

void scaled_fixed2ieee::thread_tmp_30_fu_616_p3() {
    tmp_30_fu_616_p3 = newexp_fu_610_p2.read().range(31, 31);
}

void scaled_fixed2ieee::thread_tmp_31_fu_635_p1() {
    tmp_31_fu_635_p1 = newexp_fu_610_p2.read().range(8-1, 0);
}

void scaled_fixed2ieee::thread_tmp_3_fu_389_p3() {
    tmp_3_fu_389_p3 = esl_concat<16,1>(tmp_28_fu_385_p1.read(), ap_const_lv1_1);
}

void scaled_fixed2ieee::thread_tmp_4_cast_fu_606_p1() {
    tmp_4_cast_fu_606_p1 = esl_zext<32,8>(tmp_4_fu_600_p2.read());
}

void scaled_fixed2ieee::thread_tmp_4_fu_600_p2() {
    tmp_4_fu_600_p2 = (!ap_const_lv8_81.is_01() || !prescale_cast_fu_597_p1.read().is_01())? sc_lv<8>(): (sc_bigint<8>(ap_const_lv8_81) - sc_biguint<8>(prescale_cast_fu_597_p1.read()));
}

void scaled_fixed2ieee::thread_tmp_5_cast_fu_255_p1() {
    tmp_5_cast_fu_255_p1 = esl_zext<6,5>(tmp_5_fu_247_p3.read());
}

void scaled_fixed2ieee::thread_tmp_5_fu_247_p3() {
    tmp_5_fu_247_p3 = esl_concat<1,4>(tmp_12_fu_243_p1.read(), ap_const_lv4_0);
}

void scaled_fixed2ieee::thread_tmp_6_fu_566_p1() {
    tmp_6_fu_566_p1 = esl_zext<43,32>(sh_assign_1_fu_558_p3.read());
}

void scaled_fixed2ieee::thread_tmp_7_fu_624_p2() {
    tmp_7_fu_624_p2 = (!in_V.read().is_01() || !ap_const_lv43_0.is_01())? sc_lv<1>(): sc_lv<1>(in_V.read() == ap_const_lv43_0);
}

void scaled_fixed2ieee::thread_tmp_8_fu_504_p2() {
    tmp_8_fu_504_p2 = (!i2_reg_178.read().is_01() || !ap_const_lv2_3.is_01())? sc_lv<1>(): sc_lv<1>(i2_reg_178.read() == ap_const_lv2_3);
}

void scaled_fixed2ieee::thread_tmp_9_fu_570_p2() {
    tmp_9_fu_570_p2 = (!tmp_6_fu_566_p1.read().is_01())? sc_lv<43>(): in_shift_reg_158.read() << (unsigned short)tmp_6_fu_566_p1.read().to_uint();
}

void scaled_fixed2ieee::thread_tmp_fu_428_p3() {
    tmp_fu_428_p3 = esl_concat<11,1>(tmp_11_fu_425_p1.read(), ap_const_lv1_1);
}

void scaled_fixed2ieee::thread_tmp_s_fu_576_p2() {
    tmp_s_fu_576_p2 = (!tmp_6_fu_566_p1.read().is_01())? sc_lv<43>(): in_shift_reg_158.read() >> (unsigned short)tmp_6_fu_566_p1.read().to_uint();
}

void scaled_fixed2ieee::thread_ap_NS_fsm() {
    switch (ap_CS_fsm.read().to_uint64()) {
        case 1 : 
            if ((esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1) && esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()))) {
                ap_NS_fsm = ap_ST_fsm_state2;
            } else {
                ap_NS_fsm = ap_ST_fsm_state1;
            }
            break;
        case 2 : 
            if ((esl_seteq<1,1,1>(exitcond1_fu_231_p2.read(), ap_const_lv1_1) && esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()))) {
                ap_NS_fsm = ap_ST_fsm_state3;
            } else {
                ap_NS_fsm = ap_ST_fsm_state2;
            }
            break;
        case 4 : 
            if ((esl_seteq<1,1,1>(exitcond_fu_448_p2.read(), ap_const_lv1_1) && esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()))) {
                ap_NS_fsm = ap_ST_fsm_state4;
            } else {
                ap_NS_fsm = ap_ST_fsm_state3;
            }
            break;
        case 8 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) && (esl_seteq<1,1,1>(tmp_8_fu_504_p2.read(), ap_const_lv1_1) || 
  esl_seteq<1,1,1>(tmp_1_fu_591_p2.read(), ap_const_lv1_0)))) {
                ap_NS_fsm = ap_ST_fsm_state1;
            } else {
                ap_NS_fsm = ap_ST_fsm_state4;
            }
            break;
        default : 
            ap_NS_fsm =  (sc_lv<4>) ("XXXX");
            break;
    }
}

}

