// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.1
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module cordic_sincos_generi (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        t_in,
        ap_return_0,
        ap_return_1
);

parameter    ap_ST_fsm_state1 = 7'd1;
parameter    ap_ST_fsm_state2 = 7'd2;
parameter    ap_ST_fsm_state3 = 7'd4;
parameter    ap_ST_fsm_state4 = 7'd8;
parameter    ap_ST_fsm_state5 = 7'd16;
parameter    ap_ST_fsm_state6 = 7'd32;
parameter    ap_ST_fsm_state7 = 7'd64;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [31:0] t_in;
output  [31:0] ap_return_0;
output  [31:0] ap_return_1;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg[31:0] ap_return_0;
reg[31:0] ap_return_1;

(* fsm_encoding = "none" *) reg   [6:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
wire   [3:0] ref_4oPi_table_100_V_address0;
reg    ref_4oPi_table_100_V_ce0;
wire   [99:0] ref_4oPi_table_100_V_q0;
wire   [6:0] cordic_ctab_table_12_1_address0;
reg    cordic_ctab_table_12_1_ce0;
wire   [125:0] cordic_ctab_table_12_1_q0;
reg   [0:0] p_Result_s_reg_1024;
wire   [0:0] tmp_s_fu_390_p2;
reg   [0:0] tmp_s_reg_1029;
wire   [0:0] tmp_36_fu_396_p2;
reg   [0:0] tmp_36_reg_1033;
wire   [0:0] closepath_fu_402_p2;
reg   [0:0] closepath_reg_1037;
reg   [4:0] tmp_reg_1043;
wire   [22:0] p_Result_9_fu_418_p1;
reg   [22:0] p_Result_9_reg_1048;
wire   [3:0] tmp_34_fu_451_p1;
reg   [3:0] tmp_34_reg_1058;
reg   [68:0] p_Val2_13_reg_1063;
wire    ap_CS_fsm_state2;
reg   [2:0] tmp_16_i_reg_1069;
wire   [2:0] p_Val2_23_fu_531_p3;
reg   [2:0] p_Val2_23_reg_1074;
wire    ap_CS_fsm_state3;
wire   [39:0] fout_V_fu_673_p3;
reg   [39:0] fout_V_reg_1080;
wire   [0:0] tmp_37_fu_681_p2;
reg   [0:0] tmp_37_reg_1085;
wire   [42:0] y_V_fu_707_p1;
wire   [5:0] yprescale_V_cast_fu_715_p2;
wire   [42:0] z_V_fu_740_p1;
wire    ap_CS_fsm_state4;
wire   [5:0] k_fu_750_p2;
reg   [5:0] k_reg_1107;
wire    ap_CS_fsm_state5;
wire   [0:0] d_V_fu_756_p3;
reg   [0:0] d_V_reg_1112;
wire   [0:0] exitcond_i_fu_744_p2;
wire   [42:0] tx_V_fu_786_p3;
reg   [42:0] tx_V_reg_1117;
wire   [42:0] ty_V_fu_812_p3;
reg   [42:0] ty_V_reg_1122;
wire   [2:0] sel_fu_830_p3;
reg   [2:0] sel_reg_1132;
wire   [42:0] tz_V_fu_880_p3;
wire    ap_CS_fsm_state6;
wire    grp_scaled_fixed2ieee_fu_344_ap_start;
wire    grp_scaled_fixed2ieee_fu_344_ap_done;
wire    grp_scaled_fixed2ieee_fu_344_ap_idle;
wire    grp_scaled_fixed2ieee_fu_344_ap_ready;
wire   [31:0] grp_scaled_fixed2ieee_fu_344_ap_return;
wire    grp_scaled_fixed2ieee_fu_356_ap_start;
wire    grp_scaled_fixed2ieee_fu_356_ap_done;
wire    grp_scaled_fixed2ieee_fu_356_ap_idle;
wire    grp_scaled_fixed2ieee_fu_356_ap_ready;
wire   [31:0] grp_scaled_fixed2ieee_fu_356_ap_return;
reg   [42:0] p_Val2_18_reg_210;
reg   [42:0] p_Val2_1_reg_220;
reg   [42:0] p_Val2_2_reg_231;
reg   [5:0] sh_assign_reg_242;
reg   [42:0] p_0_reg_253;
reg   [42:0] p_1_reg_266;
reg   [5:0] p_s_reg_277;
wire   [31:0] tmp_43_fu_1002_p1;
reg   [31:0] ap_phi_mux_s_out_write_assign_phi_fu_292_p20;
reg   [31:0] s_out_write_assign_reg_288;
wire    ap_CS_fsm_state7;
reg    ap_predicate_op125_call_state7;
reg    ap_block_state7_on_subcall_done;
wire   [31:0] tmp_50_fu_897_p1;
wire   [31:0] tmp_48_fu_912_p1;
wire   [31:0] tmp_46_fu_942_p1;
reg   [31:0] ap_phi_mux_c_out_write_assign_phi_fu_320_p20;
reg   [31:0] c_out_write_assign_reg_315;
wire   [31:0] tmp_49_fu_927_p1;
wire   [31:0] tmp_47_fu_957_p1;
wire   [31:0] tmp_45_fu_972_p1;
wire   [31:0] tmp_44_fu_987_p1;
reg    grp_scaled_fixed2ieee_fu_344_ap_start_reg;
reg    grp_scaled_fixed2ieee_fu_356_ap_start_reg;
wire   [63:0] tmp_5_i_i_fu_446_p1;
wire   [63:0] tmp_40_fu_820_p1;
wire   [31:0] p_Val2_7_fu_368_p1;
wire   [7:0] loc_V_fu_380_p4;
wire   [7:0] expv_op_fu_422_p2;
wire   [7:0] addr_V_fu_428_p3;
wire   [3:0] tmp_12_fu_436_p4;
wire   [99:0] tmp_7_i_i_fu_462_p1;
wire   [99:0] r_V_fu_465_p2;
wire   [79:0] Med_V_fu_471_p4;
wire   [23:0] p_Result_10_fu_455_p3;
wire   [79:0] r_V_1_fu_489_p0;
wire   [23:0] r_V_1_fu_489_p1;
wire   [103:0] r_V_1_fu_489_p2;
wire   [4:0] p_i_cast_fu_515_p2;
wire   [4:0] storemerge_i_fu_520_p3;
wire   [0:0] tmp_35_fu_537_p1;
wire   [68:0] p_Val2_i_fu_541_p2;
wire   [68:0] p_Val2_15_fu_546_p3;
wire   [28:0] p_Result_i2_i_fu_553_p4;
wire   [29:0] p_Result_11_fu_563_p3;
reg   [29:0] p_Result_12_fu_571_p4;
wire   [31:0] p_Result_13_fu_581_p3;
reg   [31:0] val_assign_fu_589_p3;
wire   [4:0] Mx_zeros_V_fu_597_p1;
wire   [68:0] tmp_17_i_fu_601_p1;
wire   [68:0] p_Val2_17_fu_605_p2;
wire  signed [6:0] storemerge_i_cast_fu_527_p1;
wire   [6:0] tmp_20_i_cast_fu_621_p1;
wire   [6:0] Ex_V_fu_625_p2;
wire   [0:0] isNeg_fu_631_p3;
wire   [6:0] tmp_22_i_fu_639_p2;
wire   [6:0] sh_assign_2_fu_645_p3;
wire  signed [31:0] sh_assign_3_cast_fu_653_p1;
wire   [39:0] Mx_V_fu_611_p4;
wire   [39:0] tmp_23_i_fu_657_p1;
wire   [39:0] tmp_24_i_fu_661_p2;
wire   [39:0] tmp_25_i_fu_667_p2;
wire   [39:0] p_Val2_9_fu_691_p1;
wire   [79:0] p_Val2_9_fu_691_p2;
wire   [39:0] tmp_14_fu_697_p4;
wire   [5:0] tmp_39_fu_711_p1;
wire   [39:0] p_Val2_s_fu_724_p0;
wire   [79:0] p_Val2_s_fu_724_p2;
wire   [39:0] tmp_15_fu_730_p4;
wire   [42:0] tmp_38_fu_764_p1;
wire   [42:0] y_s_V_fu_768_p2;
wire   [42:0] r_V_i2_fu_780_p2;
wire   [42:0] r_V_4_i_fu_774_p2;
wire   [42:0] x_s_V_fu_794_p2;
wire   [42:0] r_V_1_i_fu_800_p2;
wire   [42:0] r_V_i7_fu_806_p2;
wire   [2:0] tmp_42_fu_825_p2;
wire   [0:0] tmp_41_fu_846_p3;
wire   [39:0] tmp_46_cast_fu_854_p1;
wire   [39:0] p_Val2_27_cast_fu_836_p4;
wire   [39:0] z_s_V_fu_858_p2;
wire   [42:0] z_s_V_cast_fu_864_p1;
wire   [42:0] r_V_i_fu_874_p2;
wire   [42:0] r_V_5_i_fu_868_p2;
wire   [31:0] tmp_218_to_int_fu_887_p1;
wire   [31:0] tmp_218_neg_fu_891_p2;
wire   [31:0] tmp_216_to_int_fu_902_p1;
wire   [31:0] tmp_216_neg_fu_906_p2;
wire   [31:0] tmp_217_to_int_fu_917_p1;
wire   [31:0] tmp_217_neg_fu_921_p2;
wire   [31:0] tmp_214_to_int_fu_932_p1;
wire   [31:0] tmp_214_neg_fu_936_p2;
wire   [31:0] tmp_215_to_int_fu_947_p1;
wire   [31:0] tmp_215_neg_fu_951_p2;
wire   [31:0] tmp_213_to_int_fu_962_p1;
wire   [31:0] tmp_213_neg_fu_966_p2;
wire   [31:0] tmp_212_to_int_fu_977_p1;
wire   [31:0] tmp_212_neg_fu_981_p2;
wire   [31:0] tmp_219_to_int_fu_992_p1;
wire   [31:0] tmp_219_neg_fu_996_p2;
reg   [31:0] ap_return_0_preg;
reg   [31:0] ap_return_1_preg;
reg   [6:0] ap_NS_fsm;
wire   [79:0] p_Val2_9_fu_691_p10;
wire   [79:0] p_Val2_s_fu_724_p00;
wire   [103:0] r_V_1_fu_489_p00;
wire   [103:0] r_V_1_fu_489_p10;

// power-on initialization
initial begin
#0 ap_CS_fsm = 7'd1;
#0 grp_scaled_fixed2ieee_fu_344_ap_start_reg = 1'b0;
#0 grp_scaled_fixed2ieee_fu_356_ap_start_reg = 1'b0;
#0 ap_return_0_preg = 32'd0;
#0 ap_return_1_preg = 32'd0;
end

cordic_sincos_geneOg #(
    .DataWidth( 100 ),
    .AddressRange( 13 ),
    .AddressWidth( 4 ))
ref_4oPi_table_100_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(ref_4oPi_table_100_V_address0),
    .ce0(ref_4oPi_table_100_V_ce0),
    .q0(ref_4oPi_table_100_V_q0)
);

cordic_sincos_genfYi #(
    .DataWidth( 126 ),
    .AddressRange( 128 ),
    .AddressWidth( 7 ))
cordic_ctab_table_12_1_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(cordic_ctab_table_12_1_address0),
    .ce0(cordic_ctab_table_12_1_ce0),
    .q0(cordic_ctab_table_12_1_q0)
);

scaled_fixed2ieee grp_scaled_fixed2ieee_fu_344(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_scaled_fixed2ieee_fu_344_ap_start),
    .ap_done(grp_scaled_fixed2ieee_fu_344_ap_done),
    .ap_idle(grp_scaled_fixed2ieee_fu_344_ap_idle),
    .ap_ready(grp_scaled_fixed2ieee_fu_344_ap_ready),
    .in_V(p_1_reg_266),
    .prescale(p_s_reg_277),
    .ap_return(grp_scaled_fixed2ieee_fu_344_ap_return)
);

scaled_fixed2ieee grp_scaled_fixed2ieee_fu_356(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_scaled_fixed2ieee_fu_356_ap_start),
    .ap_done(grp_scaled_fixed2ieee_fu_356_ap_done),
    .ap_idle(grp_scaled_fixed2ieee_fu_356_ap_idle),
    .ap_ready(grp_scaled_fixed2ieee_fu_356_ap_ready),
    .in_V(p_0_reg_253),
    .prescale(6'd0),
    .ap_return(grp_scaled_fixed2ieee_fu_356_ap_return)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_return_0_preg <= 32'd0;
    end else begin
        if (((1'b1 == ap_CS_fsm_state7) & (1'b0 == ap_block_state7_on_subcall_done))) begin
            ap_return_0_preg <= ap_phi_mux_s_out_write_assign_phi_fu_292_p20;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_return_1_preg <= 32'd0;
    end else begin
        if (((1'b1 == ap_CS_fsm_state7) & (1'b0 == ap_block_state7_on_subcall_done))) begin
            ap_return_1_preg <= ap_phi_mux_c_out_write_assign_phi_fu_320_p20;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_scaled_fixed2ieee_fu_344_ap_start_reg <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_state5) & ((exitcond_i_fu_744_p2 == 1'd1) | (tmp_37_reg_1085 == 1'd1)))) begin
            grp_scaled_fixed2ieee_fu_344_ap_start_reg <= 1'b1;
        end else if ((grp_scaled_fixed2ieee_fu_344_ap_ready == 1'b1)) begin
            grp_scaled_fixed2ieee_fu_344_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_scaled_fixed2ieee_fu_356_ap_start_reg <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_state5) & ((exitcond_i_fu_744_p2 == 1'd1) | (tmp_37_reg_1085 == 1'd1)))) begin
            grp_scaled_fixed2ieee_fu_356_ap_start_reg <= 1'b1;
        end else if ((grp_scaled_fixed2ieee_fu_356_ap_ready == 1'b1)) begin
            grp_scaled_fixed2ieee_fu_356_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_s_fu_390_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        c_out_write_assign_reg_315 <= 32'd2147483647;
    end else if (((tmp_36_fu_396_p2 == 1'd1) & (tmp_s_fu_390_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        c_out_write_assign_reg_315 <= 32'd1065353216;
    end else if (((tmp_36_reg_1033 == 1'd0) & (tmp_s_reg_1029 == 1'd0) & (1'b1 == ap_CS_fsm_state7) & (1'b0 == ap_block_state7_on_subcall_done) & (sel_reg_1132 == 3'd2))) begin
        c_out_write_assign_reg_315 <= tmp_44_fu_987_p1;
    end else if (((tmp_36_reg_1033 == 1'd0) & (tmp_s_reg_1029 == 1'd0) & (1'b1 == ap_CS_fsm_state7) & (1'b0 == ap_block_state7_on_subcall_done) & (sel_reg_1132 == 3'd3))) begin
        c_out_write_assign_reg_315 <= tmp_45_fu_972_p1;
    end else if (((tmp_36_reg_1033 == 1'd0) & (tmp_s_reg_1029 == 1'd0) & (1'b1 == ap_CS_fsm_state7) & (1'b0 == ap_block_state7_on_subcall_done) & (sel_reg_1132 == 3'd4))) begin
        c_out_write_assign_reg_315 <= tmp_47_fu_957_p1;
    end else if (((tmp_36_reg_1033 == 1'd0) & (tmp_s_reg_1029 == 1'd0) & (1'b1 == ap_CS_fsm_state7) & (1'b0 == ap_block_state7_on_subcall_done) & (sel_reg_1132 == 3'd5))) begin
        c_out_write_assign_reg_315 <= tmp_49_fu_927_p1;
    end else if ((((tmp_36_reg_1033 == 1'd0) & (tmp_s_reg_1029 == 1'd0) & (1'b1 == ap_CS_fsm_state7) & (1'b0 == ap_block_state7_on_subcall_done) & (sel_reg_1132 == 3'd1)) | ((tmp_36_reg_1033 == 1'd0) & (tmp_s_reg_1029 == 1'd0) & (1'b1 == ap_CS_fsm_state7) & (1'b0 == ap_block_state7_on_subcall_done) & (sel_reg_1132 == 3'd6)))) begin
        c_out_write_assign_reg_315 <= grp_scaled_fixed2ieee_fu_344_ap_return;
    end else if ((((tmp_36_reg_1033 == 1'd0) & (tmp_s_reg_1029 == 1'd0) & (1'b1 == ap_CS_fsm_state7) & (1'b0 == ap_block_state7_on_subcall_done) & (sel_reg_1132 == 3'd0)) | ((tmp_36_reg_1033 == 1'd0) & (tmp_s_reg_1029 == 1'd0) & (1'b1 == ap_CS_fsm_state7) & (1'b0 == ap_block_state7_on_subcall_done) & (sel_reg_1132 == 3'd7)))) begin
        c_out_write_assign_reg_315 <= grp_scaled_fixed2ieee_fu_356_ap_return;
    end
end

always @ (posedge ap_clk) begin
    if (((exitcond_i_fu_744_p2 == 1'd1) & (tmp_37_reg_1085 == 1'd0) & (1'b1 == ap_CS_fsm_state5))) begin
        p_0_reg_253 <= p_Val2_2_reg_231;
    end else if (((tmp_37_fu_681_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state3))) begin
        p_0_reg_253 <= 43'd1099511627776;
    end
end

always @ (posedge ap_clk) begin
    if (((exitcond_i_fu_744_p2 == 1'd1) & (tmp_37_reg_1085 == 1'd0) & (1'b1 == ap_CS_fsm_state5))) begin
        p_1_reg_266 <= p_Val2_1_reg_220;
    end else if (((tmp_37_fu_681_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state3))) begin
        p_1_reg_266 <= y_V_fu_707_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        p_Val2_18_reg_210 <= tz_V_fu_880_p3;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        p_Val2_18_reg_210 <= z_V_fu_740_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        p_Val2_1_reg_220 <= ty_V_reg_1122;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        p_Val2_1_reg_220 <= 43'd0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        p_Val2_2_reg_231 <= tx_V_reg_1117;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        p_Val2_2_reg_231 <= 43'd667681663043;
    end
end

always @ (posedge ap_clk) begin
    if (((exitcond_i_fu_744_p2 == 1'd1) & (tmp_37_reg_1085 == 1'd0) & (1'b1 == ap_CS_fsm_state5))) begin
        p_s_reg_277 <= 6'd0;
    end else if (((tmp_37_fu_681_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state3))) begin
        p_s_reg_277 <= yprescale_V_cast_fu_715_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_s_fu_390_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        s_out_write_assign_reg_288 <= 32'd2147483647;
    end else if (((tmp_36_fu_396_p2 == 1'd1) & (tmp_s_fu_390_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        s_out_write_assign_reg_288 <= t_in;
    end else if ((((tmp_36_reg_1033 == 1'd0) & (tmp_s_reg_1029 == 1'd0) & (1'b1 == ap_CS_fsm_state7) & (1'b0 == ap_block_state7_on_subcall_done) & (sel_reg_1132 == 3'd1)) | ((tmp_36_reg_1033 == 1'd0) & (tmp_s_reg_1029 == 1'd0) & (1'b1 == ap_CS_fsm_state7) & (1'b0 == ap_block_state7_on_subcall_done) & (sel_reg_1132 == 3'd2)))) begin
        s_out_write_assign_reg_288 <= grp_scaled_fixed2ieee_fu_356_ap_return;
    end else if ((((tmp_36_reg_1033 == 1'd0) & (tmp_s_reg_1029 == 1'd0) & (1'b1 == ap_CS_fsm_state7) & (1'b0 == ap_block_state7_on_subcall_done) & (sel_reg_1132 == 3'd0)) | ((tmp_36_reg_1033 == 1'd0) & (tmp_s_reg_1029 == 1'd0) & (1'b1 == ap_CS_fsm_state7) & (1'b0 == ap_block_state7_on_subcall_done) & (sel_reg_1132 == 3'd3)))) begin
        s_out_write_assign_reg_288 <= grp_scaled_fixed2ieee_fu_344_ap_return;
    end else if (((tmp_36_reg_1033 == 1'd0) & (tmp_s_reg_1029 == 1'd0) & (1'b1 == ap_CS_fsm_state7) & (1'b0 == ap_block_state7_on_subcall_done) & (sel_reg_1132 == 3'd4))) begin
        s_out_write_assign_reg_288 <= tmp_46_fu_942_p1;
    end else if (((tmp_36_reg_1033 == 1'd0) & (tmp_s_reg_1029 == 1'd0) & (1'b1 == ap_CS_fsm_state7) & (1'b0 == ap_block_state7_on_subcall_done) & (sel_reg_1132 == 3'd5))) begin
        s_out_write_assign_reg_288 <= tmp_48_fu_912_p1;
    end else if (((tmp_36_reg_1033 == 1'd0) & (tmp_s_reg_1029 == 1'd0) & (1'b1 == ap_CS_fsm_state7) & (1'b0 == ap_block_state7_on_subcall_done) & (sel_reg_1132 == 3'd6))) begin
        s_out_write_assign_reg_288 <= tmp_50_fu_897_p1;
    end else if (((tmp_36_reg_1033 == 1'd0) & (tmp_s_reg_1029 == 1'd0) & (1'b1 == ap_CS_fsm_state7) & (1'b0 == ap_block_state7_on_subcall_done) & (sel_reg_1132 == 3'd7))) begin
        s_out_write_assign_reg_288 <= tmp_43_fu_1002_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        sh_assign_reg_242 <= k_reg_1107;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        sh_assign_reg_242 <= 6'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_36_fu_396_p2 == 1'd0) & (tmp_s_fu_390_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        closepath_reg_1037 <= closepath_fu_402_p2;
        p_Result_9_reg_1048 <= p_Result_9_fu_418_p1;
        tmp_34_reg_1058 <= tmp_34_fu_451_p1;
        tmp_reg_1043 <= {{p_Val2_7_fu_368_p1[27:23]}};
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_37_reg_1085 == 1'd0) & (exitcond_i_fu_744_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state5))) begin
        d_V_reg_1112 <= p_Val2_18_reg_210[32'd42];
        tx_V_reg_1117 <= tx_V_fu_786_p3;
        ty_V_reg_1122 <= ty_V_fu_812_p3;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        fout_V_reg_1080 <= fout_V_fu_673_p3;
        p_Val2_23_reg_1074 <= p_Val2_23_fu_531_p3;
        tmp_37_reg_1085 <= tmp_37_fu_681_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_37_reg_1085 == 1'd0) & (1'b1 == ap_CS_fsm_state5))) begin
        k_reg_1107 <= k_fu_750_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        p_Result_s_reg_1024 <= p_Val2_7_fu_368_p1[32'd31];
        tmp_s_reg_1029 <= tmp_s_fu_390_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        p_Val2_13_reg_1063 <= {{r_V_1_fu_489_p2[76:8]}};
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state5) & ((exitcond_i_fu_744_p2 == 1'd1) | (tmp_37_reg_1085 == 1'd1)))) begin
        sel_reg_1132 <= sel_fu_830_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((closepath_reg_1037 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        tmp_16_i_reg_1069 <= {{r_V_1_fu_489_p2[79:77]}};
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_s_fu_390_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        tmp_36_reg_1033 <= tmp_36_fu_396_p2;
    end
end

always @ (*) begin
    if ((((1'b1 == ap_CS_fsm_state7) & (1'b0 == ap_block_state7_on_subcall_done)) | ((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1)))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((tmp_36_reg_1033 == 1'd0) & (tmp_s_reg_1029 == 1'd0) & (1'b1 == ap_CS_fsm_state7) & (sel_reg_1132 == 3'd2))) begin
        ap_phi_mux_c_out_write_assign_phi_fu_320_p20 = tmp_44_fu_987_p1;
    end else if (((tmp_36_reg_1033 == 1'd0) & (tmp_s_reg_1029 == 1'd0) & (1'b1 == ap_CS_fsm_state7) & (sel_reg_1132 == 3'd3))) begin
        ap_phi_mux_c_out_write_assign_phi_fu_320_p20 = tmp_45_fu_972_p1;
    end else if (((tmp_36_reg_1033 == 1'd0) & (tmp_s_reg_1029 == 1'd0) & (1'b1 == ap_CS_fsm_state7) & (sel_reg_1132 == 3'd4))) begin
        ap_phi_mux_c_out_write_assign_phi_fu_320_p20 = tmp_47_fu_957_p1;
    end else if (((tmp_36_reg_1033 == 1'd0) & (tmp_s_reg_1029 == 1'd0) & (1'b1 == ap_CS_fsm_state7) & (sel_reg_1132 == 3'd5))) begin
        ap_phi_mux_c_out_write_assign_phi_fu_320_p20 = tmp_49_fu_927_p1;
    end else if ((((tmp_36_reg_1033 == 1'd0) & (tmp_s_reg_1029 == 1'd0) & (1'b1 == ap_CS_fsm_state7) & (sel_reg_1132 == 3'd1)) | ((tmp_36_reg_1033 == 1'd0) & (tmp_s_reg_1029 == 1'd0) & (1'b1 == ap_CS_fsm_state7) & (sel_reg_1132 == 3'd6)))) begin
        ap_phi_mux_c_out_write_assign_phi_fu_320_p20 = grp_scaled_fixed2ieee_fu_344_ap_return;
    end else if ((((tmp_36_reg_1033 == 1'd0) & (tmp_s_reg_1029 == 1'd0) & (1'b1 == ap_CS_fsm_state7) & (sel_reg_1132 == 3'd0)) | ((tmp_36_reg_1033 == 1'd0) & (tmp_s_reg_1029 == 1'd0) & (1'b1 == ap_CS_fsm_state7) & (sel_reg_1132 == 3'd7)))) begin
        ap_phi_mux_c_out_write_assign_phi_fu_320_p20 = grp_scaled_fixed2ieee_fu_356_ap_return;
    end else begin
        ap_phi_mux_c_out_write_assign_phi_fu_320_p20 = c_out_write_assign_reg_315;
    end
end

always @ (*) begin
    if ((((tmp_36_reg_1033 == 1'd0) & (tmp_s_reg_1029 == 1'd0) & (1'b1 == ap_CS_fsm_state7) & (sel_reg_1132 == 3'd1)) | ((tmp_36_reg_1033 == 1'd0) & (tmp_s_reg_1029 == 1'd0) & (1'b1 == ap_CS_fsm_state7) & (sel_reg_1132 == 3'd2)))) begin
        ap_phi_mux_s_out_write_assign_phi_fu_292_p20 = grp_scaled_fixed2ieee_fu_356_ap_return;
    end else if ((((tmp_36_reg_1033 == 1'd0) & (tmp_s_reg_1029 == 1'd0) & (1'b1 == ap_CS_fsm_state7) & (sel_reg_1132 == 3'd0)) | ((tmp_36_reg_1033 == 1'd0) & (tmp_s_reg_1029 == 1'd0) & (1'b1 == ap_CS_fsm_state7) & (sel_reg_1132 == 3'd3)))) begin
        ap_phi_mux_s_out_write_assign_phi_fu_292_p20 = grp_scaled_fixed2ieee_fu_344_ap_return;
    end else if (((tmp_36_reg_1033 == 1'd0) & (tmp_s_reg_1029 == 1'd0) & (1'b1 == ap_CS_fsm_state7) & (sel_reg_1132 == 3'd4))) begin
        ap_phi_mux_s_out_write_assign_phi_fu_292_p20 = tmp_46_fu_942_p1;
    end else if (((tmp_36_reg_1033 == 1'd0) & (tmp_s_reg_1029 == 1'd0) & (1'b1 == ap_CS_fsm_state7) & (sel_reg_1132 == 3'd5))) begin
        ap_phi_mux_s_out_write_assign_phi_fu_292_p20 = tmp_48_fu_912_p1;
    end else if (((tmp_36_reg_1033 == 1'd0) & (tmp_s_reg_1029 == 1'd0) & (1'b1 == ap_CS_fsm_state7) & (sel_reg_1132 == 3'd6))) begin
        ap_phi_mux_s_out_write_assign_phi_fu_292_p20 = tmp_50_fu_897_p1;
    end else if (((tmp_36_reg_1033 == 1'd0) & (tmp_s_reg_1029 == 1'd0) & (1'b1 == ap_CS_fsm_state7) & (sel_reg_1132 == 3'd7))) begin
        ap_phi_mux_s_out_write_assign_phi_fu_292_p20 = tmp_43_fu_1002_p1;
    end else begin
        ap_phi_mux_s_out_write_assign_phi_fu_292_p20 = s_out_write_assign_reg_288;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state7) & (1'b0 == ap_block_state7_on_subcall_done))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state7) & (1'b0 == ap_block_state7_on_subcall_done))) begin
        ap_return_0 = ap_phi_mux_s_out_write_assign_phi_fu_292_p20;
    end else begin
        ap_return_0 = ap_return_0_preg;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state7) & (1'b0 == ap_block_state7_on_subcall_done))) begin
        ap_return_1 = ap_phi_mux_c_out_write_assign_phi_fu_320_p20;
    end else begin
        ap_return_1 = ap_return_1_preg;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        cordic_ctab_table_12_1_ce0 = 1'b1;
    end else begin
        cordic_ctab_table_12_1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        ref_4oPi_table_100_V_ce0 = 1'b1;
    end else begin
        ref_4oPi_table_100_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((tmp_36_fu_396_p2 == 1'd0) & (tmp_s_fu_390_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1) & ((tmp_36_fu_396_p2 == 1'd1) | (tmp_s_fu_390_p2 == 1'd1)))) begin
                ap_NS_fsm = ap_ST_fsm_state7;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            ap_NS_fsm = ap_ST_fsm_state3;
        end
        ap_ST_fsm_state3 : begin
            if (((tmp_37_fu_681_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state3))) begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_state5;
        end
        ap_ST_fsm_state5 : begin
            if (((1'b1 == ap_CS_fsm_state5) & ((exitcond_i_fu_744_p2 == 1'd1) | (tmp_37_reg_1085 == 1'd1)))) begin
                ap_NS_fsm = ap_ST_fsm_state7;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state6;
            end
        end
        ap_ST_fsm_state6 : begin
            ap_NS_fsm = ap_ST_fsm_state5;
        end
        ap_ST_fsm_state7 : begin
            if (((1'b1 == ap_CS_fsm_state7) & (1'b0 == ap_block_state7_on_subcall_done))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state7;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign Ex_V_fu_625_p2 = ($signed(storemerge_i_cast_fu_527_p1) - $signed(tmp_20_i_cast_fu_621_p1));

assign Med_V_fu_471_p4 = {{r_V_fu_465_p2[99:20]}};

assign Mx_V_fu_611_p4 = {{p_Val2_17_fu_605_p2[68:29]}};

assign Mx_zeros_V_fu_597_p1 = val_assign_fu_589_p3[4:0];

assign addr_V_fu_428_p3 = ((closepath_fu_402_p2[0:0] === 1'b1) ? 8'd63 : expv_op_fu_422_p2);

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state6 = ap_CS_fsm[32'd5];

assign ap_CS_fsm_state7 = ap_CS_fsm[32'd6];

always @ (*) begin
    ap_block_state7_on_subcall_done = (((grp_scaled_fixed2ieee_fu_356_ap_done == 1'b0) & (ap_predicate_op125_call_state7 == 1'b1)) | ((grp_scaled_fixed2ieee_fu_344_ap_done == 1'b0) & (ap_predicate_op125_call_state7 == 1'b1)));
end

always @ (*) begin
    ap_predicate_op125_call_state7 = ((tmp_36_reg_1033 == 1'd0) & (tmp_s_reg_1029 == 1'd0));
end

assign closepath_fu_402_p2 = ((loc_V_fu_380_p4 < 8'd126) ? 1'b1 : 1'b0);

assign cordic_ctab_table_12_1_address0 = tmp_40_fu_820_p1;

assign d_V_fu_756_p3 = p_Val2_18_reg_210[32'd42];

assign exitcond_i_fu_744_p2 = ((sh_assign_reg_242 == 6'd43) ? 1'b1 : 1'b0);

assign expv_op_fu_422_p2 = ($signed(8'd194) + $signed(loc_V_fu_380_p4));

assign fout_V_fu_673_p3 = ((isNeg_fu_631_p3[0:0] === 1'b1) ? tmp_24_i_fu_661_p2 : tmp_25_i_fu_667_p2);

assign grp_scaled_fixed2ieee_fu_344_ap_start = grp_scaled_fixed2ieee_fu_344_ap_start_reg;

assign grp_scaled_fixed2ieee_fu_356_ap_start = grp_scaled_fixed2ieee_fu_356_ap_start_reg;

assign isNeg_fu_631_p3 = Ex_V_fu_625_p2[32'd6];

assign k_fu_750_p2 = (sh_assign_reg_242 + 6'd1);

assign loc_V_fu_380_p4 = {{p_Val2_7_fu_368_p1[30:23]}};

assign p_Result_10_fu_455_p3 = {{1'd1}, {p_Result_9_reg_1048}};

assign p_Result_11_fu_563_p3 = {{p_Result_i2_i_fu_553_p4}, {1'd1}};

integer ap_tvar_int_0;

always @ (p_Result_11_fu_563_p3) begin
    for (ap_tvar_int_0 = 30 - 1; ap_tvar_int_0 >= 0; ap_tvar_int_0 = ap_tvar_int_0 - 1) begin
        if (ap_tvar_int_0 > 29 - 0) begin
            p_Result_12_fu_571_p4[ap_tvar_int_0] = 1'b0;
        end else begin
            p_Result_12_fu_571_p4[ap_tvar_int_0] = p_Result_11_fu_563_p3[29 - ap_tvar_int_0];
        end
    end
end

assign p_Result_13_fu_581_p3 = {{2'd3}, {p_Result_12_fu_571_p4}};

assign p_Result_9_fu_418_p1 = p_Val2_7_fu_368_p1[22:0];

assign p_Result_i2_i_fu_553_p4 = {{p_Val2_15_fu_546_p3[68:40]}};

assign p_Val2_15_fu_546_p3 = ((tmp_35_fu_537_p1[0:0] === 1'b1) ? p_Val2_i_fu_541_p2 : p_Val2_13_reg_1063);

assign p_Val2_17_fu_605_p2 = p_Val2_15_fu_546_p3 << tmp_17_i_fu_601_p1;

assign p_Val2_23_fu_531_p3 = ((closepath_reg_1037[0:0] === 1'b1) ? 3'd0 : tmp_16_i_reg_1069);

assign p_Val2_27_cast_fu_836_p4 = {{cordic_ctab_table_12_1_q0[125:86]}};

assign p_Val2_7_fu_368_p1 = t_in;

assign p_Val2_9_fu_691_p1 = p_Val2_9_fu_691_p10;

assign p_Val2_9_fu_691_p10 = Mx_V_fu_611_p4;

assign p_Val2_9_fu_691_p2 = (80'd863554413089 * p_Val2_9_fu_691_p1);

assign p_Val2_i_fu_541_p2 = (69'd0 - p_Val2_13_reg_1063);

assign p_Val2_s_fu_724_p0 = p_Val2_s_fu_724_p00;

assign p_Val2_s_fu_724_p00 = fout_V_reg_1080;

assign p_Val2_s_fu_724_p2 = (p_Val2_s_fu_724_p0 * $signed(80'hC90FDAA221));

assign p_i_cast_fu_515_p2 = (5'd3 + tmp_reg_1043);

assign r_V_1_fu_489_p0 = r_V_1_fu_489_p00;

assign r_V_1_fu_489_p00 = Med_V_fu_471_p4;

assign r_V_1_fu_489_p1 = r_V_1_fu_489_p10;

assign r_V_1_fu_489_p10 = p_Result_10_fu_455_p3;

assign r_V_1_fu_489_p2 = (r_V_1_fu_489_p0 * r_V_1_fu_489_p1);

assign r_V_1_i_fu_800_p2 = (p_Val2_1_reg_220 - x_s_V_fu_794_p2);

assign r_V_4_i_fu_774_p2 = (p_Val2_2_reg_231 - y_s_V_fu_768_p2);

assign r_V_5_i_fu_868_p2 = (p_Val2_18_reg_210 - z_s_V_cast_fu_864_p1);

assign r_V_fu_465_p2 = ref_4oPi_table_100_V_q0 << tmp_7_i_i_fu_462_p1;

assign r_V_i2_fu_780_p2 = (p_Val2_2_reg_231 + y_s_V_fu_768_p2);

assign r_V_i7_fu_806_p2 = (p_Val2_1_reg_220 + x_s_V_fu_794_p2);

assign r_V_i_fu_874_p2 = (p_Val2_18_reg_210 + z_s_V_cast_fu_864_p1);

assign ref_4oPi_table_100_V_address0 = tmp_5_i_i_fu_446_p1;

assign sel_fu_830_p3 = ((p_Result_s_reg_1024[0:0] === 1'b1) ? tmp_42_fu_825_p2 : p_Val2_23_reg_1074);

assign sh_assign_2_fu_645_p3 = ((isNeg_fu_631_p3[0:0] === 1'b1) ? tmp_22_i_fu_639_p2 : Ex_V_fu_625_p2);

assign sh_assign_3_cast_fu_653_p1 = $signed(sh_assign_2_fu_645_p3);

assign storemerge_i_cast_fu_527_p1 = $signed(storemerge_i_fu_520_p3);

assign storemerge_i_fu_520_p3 = ((closepath_reg_1037[0:0] === 1'b1) ? p_i_cast_fu_515_p2 : 5'd0);

assign tmp_12_fu_436_p4 = {{addr_V_fu_428_p3[7:4]}};

assign tmp_14_fu_697_p4 = {{p_Val2_9_fu_691_p2[79:40]}};

assign tmp_15_fu_730_p4 = {{p_Val2_s_fu_724_p2[79:40]}};

assign tmp_17_i_fu_601_p1 = Mx_zeros_V_fu_597_p1;

assign tmp_20_i_cast_fu_621_p1 = Mx_zeros_V_fu_597_p1;

assign tmp_212_neg_fu_981_p2 = (tmp_212_to_int_fu_977_p1 ^ 32'd2147483648);

assign tmp_212_to_int_fu_977_p1 = grp_scaled_fixed2ieee_fu_344_ap_return;

assign tmp_213_neg_fu_966_p2 = (tmp_213_to_int_fu_962_p1 ^ 32'd2147483648);

assign tmp_213_to_int_fu_962_p1 = grp_scaled_fixed2ieee_fu_356_ap_return;

assign tmp_214_neg_fu_936_p2 = (tmp_214_to_int_fu_932_p1 ^ 32'd2147483648);

assign tmp_214_to_int_fu_932_p1 = grp_scaled_fixed2ieee_fu_344_ap_return;

assign tmp_215_neg_fu_951_p2 = (tmp_215_to_int_fu_947_p1 ^ 32'd2147483648);

assign tmp_215_to_int_fu_947_p1 = grp_scaled_fixed2ieee_fu_356_ap_return;

assign tmp_216_neg_fu_906_p2 = (tmp_216_to_int_fu_902_p1 ^ 32'd2147483648);

assign tmp_216_to_int_fu_902_p1 = grp_scaled_fixed2ieee_fu_356_ap_return;

assign tmp_217_neg_fu_921_p2 = (tmp_217_to_int_fu_917_p1 ^ 32'd2147483648);

assign tmp_217_to_int_fu_917_p1 = grp_scaled_fixed2ieee_fu_344_ap_return;

assign tmp_218_neg_fu_891_p2 = (tmp_218_to_int_fu_887_p1 ^ 32'd2147483648);

assign tmp_218_to_int_fu_887_p1 = grp_scaled_fixed2ieee_fu_356_ap_return;

assign tmp_219_neg_fu_996_p2 = (tmp_219_to_int_fu_992_p1 ^ 32'd2147483648);

assign tmp_219_to_int_fu_992_p1 = grp_scaled_fixed2ieee_fu_344_ap_return;

assign tmp_22_i_fu_639_p2 = (7'd0 - Ex_V_fu_625_p2);

assign tmp_23_i_fu_657_p1 = $unsigned(sh_assign_3_cast_fu_653_p1);

assign tmp_24_i_fu_661_p2 = Mx_V_fu_611_p4 >> tmp_23_i_fu_657_p1;

assign tmp_25_i_fu_667_p2 = Mx_V_fu_611_p4 << tmp_23_i_fu_657_p1;

assign tmp_34_fu_451_p1 = addr_V_fu_428_p3[3:0];

assign tmp_35_fu_537_p1 = p_Val2_23_fu_531_p3[0:0];

assign tmp_36_fu_396_p2 = ((loc_V_fu_380_p4 < 8'd115) ? 1'b1 : 1'b0);

assign tmp_37_fu_681_p2 = (($signed(Ex_V_fu_625_p2) < $signed(7'd116)) ? 1'b1 : 1'b0);

assign tmp_38_fu_764_p1 = sh_assign_reg_242;

assign tmp_39_fu_711_p1 = Ex_V_fu_625_p2[5:0];

assign tmp_40_fu_820_p1 = sh_assign_reg_242;

assign tmp_41_fu_846_p3 = cordic_ctab_table_12_1_q0[32'd85];

assign tmp_42_fu_825_p2 = (p_Val2_23_reg_1074 ^ 3'd7);

assign tmp_43_fu_1002_p1 = tmp_219_neg_fu_996_p2;

assign tmp_44_fu_987_p1 = tmp_212_neg_fu_981_p2;

assign tmp_45_fu_972_p1 = tmp_213_neg_fu_966_p2;

assign tmp_46_cast_fu_854_p1 = tmp_41_fu_846_p3;

assign tmp_46_fu_942_p1 = tmp_214_neg_fu_936_p2;

assign tmp_47_fu_957_p1 = tmp_215_neg_fu_951_p2;

assign tmp_48_fu_912_p1 = tmp_216_neg_fu_906_p2;

assign tmp_49_fu_927_p1 = tmp_217_neg_fu_921_p2;

assign tmp_50_fu_897_p1 = tmp_218_neg_fu_891_p2;

assign tmp_5_i_i_fu_446_p1 = tmp_12_fu_436_p4;

assign tmp_7_i_i_fu_462_p1 = tmp_34_reg_1058;

assign tmp_s_fu_390_p2 = ((loc_V_fu_380_p4 == 8'd255) ? 1'b1 : 1'b0);

assign tx_V_fu_786_p3 = ((d_V_fu_756_p3[0:0] === 1'b1) ? r_V_i2_fu_780_p2 : r_V_4_i_fu_774_p2);

assign ty_V_fu_812_p3 = ((d_V_fu_756_p3[0:0] === 1'b1) ? r_V_1_i_fu_800_p2 : r_V_i7_fu_806_p2);

assign tz_V_fu_880_p3 = ((d_V_reg_1112[0:0] === 1'b1) ? r_V_i_fu_874_p2 : r_V_5_i_fu_868_p2);


always @ (p_Result_13_fu_581_p3) begin
    if (p_Result_13_fu_581_p3[0] == 1'b1) begin
        val_assign_fu_589_p3 = 32'd0;
    end else if (p_Result_13_fu_581_p3[1] == 1'b1) begin
        val_assign_fu_589_p3 = 32'd1;
    end else if (p_Result_13_fu_581_p3[2] == 1'b1) begin
        val_assign_fu_589_p3 = 32'd2;
    end else if (p_Result_13_fu_581_p3[3] == 1'b1) begin
        val_assign_fu_589_p3 = 32'd3;
    end else if (p_Result_13_fu_581_p3[4] == 1'b1) begin
        val_assign_fu_589_p3 = 32'd4;
    end else if (p_Result_13_fu_581_p3[5] == 1'b1) begin
        val_assign_fu_589_p3 = 32'd5;
    end else if (p_Result_13_fu_581_p3[6] == 1'b1) begin
        val_assign_fu_589_p3 = 32'd6;
    end else if (p_Result_13_fu_581_p3[7] == 1'b1) begin
        val_assign_fu_589_p3 = 32'd7;
    end else if (p_Result_13_fu_581_p3[8] == 1'b1) begin
        val_assign_fu_589_p3 = 32'd8;
    end else if (p_Result_13_fu_581_p3[9] == 1'b1) begin
        val_assign_fu_589_p3 = 32'd9;
    end else if (p_Result_13_fu_581_p3[10] == 1'b1) begin
        val_assign_fu_589_p3 = 32'd10;
    end else if (p_Result_13_fu_581_p3[11] == 1'b1) begin
        val_assign_fu_589_p3 = 32'd11;
    end else if (p_Result_13_fu_581_p3[12] == 1'b1) begin
        val_assign_fu_589_p3 = 32'd12;
    end else if (p_Result_13_fu_581_p3[13] == 1'b1) begin
        val_assign_fu_589_p3 = 32'd13;
    end else if (p_Result_13_fu_581_p3[14] == 1'b1) begin
        val_assign_fu_589_p3 = 32'd14;
    end else if (p_Result_13_fu_581_p3[15] == 1'b1) begin
        val_assign_fu_589_p3 = 32'd15;
    end else if (p_Result_13_fu_581_p3[16] == 1'b1) begin
        val_assign_fu_589_p3 = 32'd16;
    end else if (p_Result_13_fu_581_p3[17] == 1'b1) begin
        val_assign_fu_589_p3 = 32'd17;
    end else if (p_Result_13_fu_581_p3[18] == 1'b1) begin
        val_assign_fu_589_p3 = 32'd18;
    end else if (p_Result_13_fu_581_p3[19] == 1'b1) begin
        val_assign_fu_589_p3 = 32'd19;
    end else if (p_Result_13_fu_581_p3[20] == 1'b1) begin
        val_assign_fu_589_p3 = 32'd20;
    end else if (p_Result_13_fu_581_p3[21] == 1'b1) begin
        val_assign_fu_589_p3 = 32'd21;
    end else if (p_Result_13_fu_581_p3[22] == 1'b1) begin
        val_assign_fu_589_p3 = 32'd22;
    end else if (p_Result_13_fu_581_p3[23] == 1'b1) begin
        val_assign_fu_589_p3 = 32'd23;
    end else if (p_Result_13_fu_581_p3[24] == 1'b1) begin
        val_assign_fu_589_p3 = 32'd24;
    end else if (p_Result_13_fu_581_p3[25] == 1'b1) begin
        val_assign_fu_589_p3 = 32'd25;
    end else if (p_Result_13_fu_581_p3[26] == 1'b1) begin
        val_assign_fu_589_p3 = 32'd26;
    end else if (p_Result_13_fu_581_p3[27] == 1'b1) begin
        val_assign_fu_589_p3 = 32'd27;
    end else if (p_Result_13_fu_581_p3[28] == 1'b1) begin
        val_assign_fu_589_p3 = 32'd28;
    end else if (p_Result_13_fu_581_p3[29] == 1'b1) begin
        val_assign_fu_589_p3 = 32'd29;
    end else if (p_Result_13_fu_581_p3[30] == 1'b1) begin
        val_assign_fu_589_p3 = 32'd30;
    end else if (p_Result_13_fu_581_p3[31] == 1'b1) begin
        val_assign_fu_589_p3 = 32'd31;
    end else begin
        val_assign_fu_589_p3 = 32'd32;
    end
end

assign x_s_V_fu_794_p2 = $signed(p_Val2_2_reg_231) >>> tmp_38_fu_764_p1;

assign y_V_fu_707_p1 = tmp_14_fu_697_p4;

assign y_s_V_fu_768_p2 = $signed(p_Val2_1_reg_220) >>> tmp_38_fu_764_p1;

assign yprescale_V_cast_fu_715_p2 = (6'd0 - tmp_39_fu_711_p1);

assign z_V_fu_740_p1 = tmp_15_fu_730_p4;

assign z_s_V_cast_fu_864_p1 = z_s_V_fu_858_p2;

assign z_s_V_fu_858_p2 = (tmp_46_cast_fu_854_p1 + p_Val2_27_cast_fu_836_p4);

endmodule //cordic_sincos_generi
